Repository OCA/social, pull requests merged in 2018-12, with the labels that each got.

#331 [11.0] Add module mail_browser_view
  mail_browser_view/README.rst
  mail_browser_view/__init__.py
  mail_browser_view/__manifest__.py
  mail_browser_view/controllers/__init__.py
  mail_browser_view/controllers/browser_view.py
  mail_browser_view/data/ir_config.xml
  mail_browser_view/demo/mail.xml
  mail_browser_view/models/__init__.py
  mail_browser_view/models/mail_mail.py
  mail_browser_view/readme/CONFIGURE.rst
  mail_browser_view/readme/CONTRIBUTORS.rst
  mail_browser_view/readme/DESCRIPTION.rst
  mail_browser_view/readme/USAGE.rst
  mail_browser_view/static/description/icon.png
  mail_browser_view/static/description/index.html
  mail_browser_view/tests/__init__.py
  mail_browser_view/tests/test_mail_browser_view.py
Labels: approved, needs review, needs tests, ready to merge

#339 [MIG] fetchmail_thread_default: Migration to 11.0
  fetchmail_thread_default/README.rst
  fetchmail_thread_default/__init__.py
  fetchmail_thread_default/__manifest__.py
  fetchmail_thread_default/demo/data.xml
  fetchmail_thread_default/i18n/.empty
  fetchmail_thread_default/i18n/ca.po
  fetchmail_thread_default/i18n/de.po
  fetchmail_thread_default/i18n/es.po
  fetchmail_thread_default/i18n/fetchmail_thread_default.pot
  fetchmail_thread_default/i18n/fr.po
  fetchmail_thread_default/i18n/hr.po
  fetchmail_thread_default/i18n/it.po
  fetchmail_thread_default/i18n/pt_BR.po
  fetchmail_thread_default/i18n/pt_PT.po
  fetchmail_thread_default/i18n/sl.po
  fetchmail_thread_default/i18n/tr.po
  fetchmail_thread_default/i18n/zh_CN.po
  fetchmail_thread_default/models/__init__.py
  fetchmail_thread_default/models/fetchmail_server.py
  fetchmail_thread_default/models/mail_thread.py
  fetchmail_thread_default/readme/CONFIGURE.rst
  fetchmail_thread_default/readme/CONTRIBUTORS.rst
  fetchmail_thread_default/readme/DESCRIPTION.rst
  fetchmail_thread_default/readme/USAGE.rst
  fetchmail_thread_default/static/description/icon.png
  fetchmail_thread_default/tests/__init__.py
  fetchmail_thread_default/tests/test_fetchmail.py
  fetchmail_thread_default/views/fetchmail_server_view.xml
Labels: approved

#317 12.0 mig mail_attach_existing_attachment
  mail_attach_existing_attachment/README.rst
  mail_attach_existing_attachment/__init__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_attach_existing_attachment/i18n/ca.po
  mail_attach_existing_attachment/i18n/de.po
  mail_attach_existing_attachment/i18n/es.po
  mail_attach_existing_attachment/i18n/es_CO.po
  mail_attach_existing_attachment/i18n/fr.po
  mail_attach_existing_attachment/i18n/hr.po
  mail_attach_existing_attachment/i18n/it.po
  mail_attach_existing_attachment/i18n/mail_attach_existing_attachment.pot
  mail_attach_existing_attachment/i18n/pt_BR.po
  mail_attach_existing_attachment/i18n/sl.po
  mail_attach_existing_attachment/i18n/zh_CN.po
  mail_attach_existing_attachment/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment/readme/DESCRIPTION.rst
  mail_attach_existing_attachment/readme/ROADMAP.rst
  mail_attach_existing_attachment/readme/USAGE.rst
  mail_attach_existing_attachment/static/description/attachment.png
  mail_attach_existing_attachment/static/description/ex_mail_compose_message.png
  mail_attach_existing_attachment/static/description/icon.png
  mail_attach_existing_attachment/static/description/index.html
  mail_attach_existing_attachment/tests/__init__.py
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment/wizard/__init__.py
  mail_attach_existing_attachment/wizard/mail_compose_message.py
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
Labels: approved, needs review

#341 12.0 mig email_template_qweb
  email_template_qweb/README.rst
  email_template_qweb/__init__.py
  email_template_qweb/__manifest__.py
  email_template_qweb/demo/ir_ui_view.xml
  email_template_qweb/demo/mail_template.xml
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/email_template_qweb.pot
  email_template_qweb/i18n/en.po
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/nl_NL.po
  email_template_qweb/i18n/pt_BR.po
  email_template_qweb/i18n/zh_CN.po
  email_template_qweb/models/__init__.py
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
  email_template_qweb/readme/DESCRIPTION.rst
  email_template_qweb/readme/USAGE.rst
  email_template_qweb/static/description/icon.png
  email_template_qweb/static/description/index.html
  email_template_qweb/tests/__init__.py
  email_template_qweb/tests/test_mail_template_qweb.py
  email_template_qweb/views/mail_template.xml
Labels: approved, needs review
