Repository OCA/social, pull requests merged in 2018-05, with the labels that each got.

#265 [11.0][MIG] mail_debrand
  mail_debrand/README.rst
  mail_debrand/__init__.py
  mail_debrand/__manifest__.py
  mail_debrand/i18n/de.po
  mail_debrand/i18n/es.po
  mail_debrand/i18n/es_MX.po
  mail_debrand/i18n/fr.po
  mail_debrand/i18n/hr.po
  mail_debrand/i18n/it.po
  mail_debrand/i18n/nl_NL.po
  mail_debrand/i18n/zh_CN.po
  mail_debrand/models/__init__.py
  mail_debrand/models/mail_template.py
  mail_debrand/static/description/icon.png
  mail_debrand/static/description/icon.svg
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand.py
Labels: needs review

#267 [IMP] mass_mailing_custom_unsubscribe: GDPR compliance
  mass_mailing_custom_unsubscribe/README.rst
  mass_mailing_custom_unsubscribe/__manifest__.py
  mass_mailing_custom_unsubscribe/controllers/main.py
  mass_mailing_custom_unsubscribe/data/mail_unsubscription_reason.xml
  mass_mailing_custom_unsubscribe/exceptions.py
  mass_mailing_custom_unsubscribe/models/mail_mass_mailing.py
  mass_mailing_custom_unsubscribe/models/mail_unsubscription.py
  mass_mailing_custom_unsubscribe/static/src/js/require_details.js
  mass_mailing_custom_unsubscribe/static/src/js/unsubscribe.js
  mass_mailing_custom_unsubscribe/tests/test_unsubscription.py
  mass_mailing_custom_unsubscribe/views/mail_unsubscription_view.xml
Labels: enhancement, needs review

#270 [FIX] mail_trackin_mailgun: partner form
  mail_tracking_mailgun/__manifest__.py
  mail_tracking_mailgun/views/res_partner.xml
Labels: needs review

#271 [FIX] mass_mailing_partner: compute fields performance
  mass_mailing_partner/__openerp__.py
  mass_mailing_partner/models/res_partner.py
Labels: needs review

#259 [FIX] mass_mailing_event: Integration tests
  mass_mailing_event/__manifest__.py
  mass_mailing_event/tests/test_mass_mailing_event.py
Labels: bug, needs review

#266 [IMP][10.0] Mail digest improvements
  mail_digest/README.rst
  mail_digest/__init__.py
  mail_digest/__manifest__.py
  mail_digest/controllers/__init__.py
  mail_digest/controllers/digest_layout_preview.py
  mail_digest/images/digest_layout_preview.png
  mail_digest/models/mail_digest.py
  mail_digest/templates/digest_default.xml
  mail_digest/templates/digest_layout_preview.xml
  mail_digest/tests/__init__.py
  mail_digest/tests/test_digest.py
  mail_digest/tests/test_preview.py
Labels: needs review

#274 [FIX] mass_mailing_event: Avoid double test
  mass_mailing_event/tests/test_mass_mailing_event.py
Labels: needs review
