Repository OCA/social, pull requests merged in 2019-01, with the labels that each got.

#336 [FIX] mail_tracking: wrong bounced partner
  mail_tracking/README.rst
  mail_tracking/__manifest__.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/res_partner.py
  mail_tracking/tests/__init__.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, needs review

#350 [FIX] mail_activity_team
  mail_activity_team/models/mail_activity.py
Labels: approved

#346 [11.0][ADD] mail_activity_partner
  mail_activity_partner/README.rst
  mail_activity_partner/__init__.py
  mail_activity_partner/__manifest__.py
  mail_activity_partner/models/__init__.py
  mail_activity_partner/models/mail_activity.py
  mail_activity_partner/readme/CONTRIBUTORS.rst
  mail_activity_partner/readme/DESCRIPTION.rst
  mail_activity_partner/readme/USAGE.rst
  mail_activity_partner/static/description/index.html
  mail_activity_partner/tests/__init__.py
  mail_activity_partner/tests/test_mail_activity_partner.py
  mail_activity_partner/views/mail_activity_views.xml
Labels: approved

#296 [11.0][mail_activity_done] add new module to keep activities that have been completed.
  mail_activity_done/LICENSE
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/DESCRIPTION.rst
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/src/js/mail_activity.js
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
  mail_activity_done/views/templates.xml
Labels: approved, needs tests
