Repository OCA/social, pull requests merged in 2019-07, with the labels that each got.

#408 [FIX] mail_debrand: Add development_status
  mail_debrand/__manifest__.py
Labels: approved, bug, needs review

#416 [11.0][FIX] mail_tracking: Repeated suggested cc emails
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved

#422 [FIX] don't break when a partner has a user
  .travis.yml
  mail_footer_notified_partners/README.rst
  mail_notification_email_template/models/mail_notification.py
  mail_notification_email_template/tests/test_mail_notification_email_template.py
  mail_optional_follower_notification/README.rst
  mail_restrict_follower_selection/README.rst
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mass_mailing_keep_archives/README.rst
  social_media_pinterest/README.rst
  social_media_pinterest_blog/README.rst
  website_mail_snippet_table_edit/README.rst
Labels: needs review

#406 [12.0][MIG] message_auto_subscribe_notify_own
  message_auto_subscribe_notify_own/README.rst
  message_auto_subscribe_notify_own/__init__.py
  message_auto_subscribe_notify_own/__manifest__.py
  message_auto_subscribe_notify_own/i18n/message_auto_subscribe_notify_own.pot
  message_auto_subscribe_notify_own/models/__init__.py
  message_auto_subscribe_notify_own/models/auto_subscribe_notify_own_model.py
  message_auto_subscribe_notify_own/models/mail_thread.py
  message_auto_subscribe_notify_own/readme/CONFIGURE.rst
  message_auto_subscribe_notify_own/readme/CONTRIBUTORS.rst
  message_auto_subscribe_notify_own/readme/DESCRIPTION.rst
  message_auto_subscribe_notify_own/readme/USAGE.rst
  message_auto_subscribe_notify_own/security/ir.model.access.csv
  message_auto_subscribe_notify_own/static/description/icon.png
  message_auto_subscribe_notify_own/static/description/index.html
  message_auto_subscribe_notify_own/tests/__init__.py
  message_auto_subscribe_notify_own/tests/test_fake_model.py
  message_auto_subscribe_notify_own/tests/test_message_auto_subscribe_notify_own.py
  message_auto_subscribe_notify_own/views/auto_subscribe_notify_own_model.xml
Labels: approved, ready to merge
