Repository OCA/social, pull requests merged in 2019-06, with the labels that each got.

#374 [11.0][ADD] mass_mailing_newsletter_welcome_mail
  mass_mailing_newsletter_welcome_mail/README.rst
  mass_mailing_newsletter_welcome_mail/__init__.py
  mass_mailing_newsletter_welcome_mail/__manifest__.py
  mass_mailing_newsletter_welcome_mail/controllers/__init__.py
  mass_mailing_newsletter_welcome_mail/controllers/main.py
  mass_mailing_newsletter_welcome_mail/data/mail_template.xml
  mass_mailing_newsletter_welcome_mail/i18n/es.po
  mass_mailing_newsletter_welcome_mail/i18n/mass_mailing_welcome_mail.pot
  mass_mailing_newsletter_welcome_mail/models/__init__.py
  mass_mailing_newsletter_welcome_mail/models/mail_mass_mailing_list.py
  mass_mailing_newsletter_welcome_mail/readme/CONFIGURE.rst
  mass_mailing_newsletter_welcome_mail/readme/CONTRIBUTORS.rst
  mass_mailing_newsletter_welcome_mail/readme/DESCRIPTION.rst
  mass_mailing_newsletter_welcome_mail/readme/ROADMAP.rst
  mass_mailing_newsletter_welcome_mail/readme/USAGE.rst
  mass_mailing_newsletter_welcome_mail/static/description/icon.png
  mass_mailing_newsletter_welcome_mail/static/description/index.html
  mass_mailing_newsletter_welcome_mail/views/mail_mass_mailing_list.xml
Labels: approved

#344 POC Depower Mail
  mail_debrand/__init__.py
  mail_debrand/__manifest__.py
  mail_debrand/models/__init__.py
  mail_debrand/models/mail_template.py
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand.py
  mail_debrand/views/mail_notification_view.xml
Labels: approved, ready to merge

#397 [FIX] green runbot 2019-06-13
  .travis.yml
  mail_sendgrid_mass_mailing/README.rst
  requirements.txt
Labels: needs review

#380 [12.0][FIX] mail_activity_done module
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/migrations/12.0.2.0.0/post-migration.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/views/mail_activity_views.xml
Labels: approved
