Repository OCA/social, pull requests merged in 2019-03, with the labels that each got.

#359 [11.0][FIX] base_search_mail_content: Move message content search to …
  base_search_mail_content/__manifest__.py
  base_search_mail_content/models/mail_thread.py
Labels: approved, ready to merge

#354 [12.0][MIG] mail_activity_done
  mail_activity_done/LICENSE
  mail_activity_done/README.rst
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/DESCRIPTION.rst
  mail_activity_done/readme/USAGE.rst
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/description/index.html
  mail_activity_done/static/src/js/mail_activity.js
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
  mail_activity_done/views/templates.xml
Labels: approved, ready to merge

#337 [11.0][IMP] mail_activity_board: filter activities by user read permissions
  mail_activity_board/__manifest__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/tests/test_mail_activity_board.py
Labels: approved, needs review

#338 [12.0][MIG] mail_activity_board
  mail_activity_board/README.rst
  mail_activity_board/__init__.py
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/__init__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/models/mail_activity_mixin.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/readme/DESCRIPTION.rst
  mail_activity_board/readme/USAGE.rst
  mail_activity_board/static/description/icon.png
  mail_activity_board/static/description/index.html
  mail_activity_board/static/src/js/override_chatter.js
  mail_activity_board/static/src/xml/inherit_chatter.xml
  mail_activity_board/tests/__init__.py
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
  mail_activity_board/views/templates.xml
  mail_activity_done/__manifest__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
Labels: approved, needs review, ready to merge

#370 [11.0][FIX] mail_activity_done: Future Activities filter doesn't break
  mail_activity_done/__manifest__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/views/mail_activity_views.xml
Labels: approved

#372 [IMP] use json library instead of simplejson
  mail_sendgrid/__manifest__.py
  mail_sendgrid/controllers/json_request.py
  requirements.txt
Labels: approved, needs review
