Repository OCA/social, pull requests merged in 2020-04, with the labels that each got.

#532 [13.0][FIX] mail_tracking: do not warn not found if already opened
  mail_tracking/controllers/main.py
Labels: bot is merging ⏳

#533 email_template_qweb: ease override of values, include defaults
  email_template_qweb/README.rst
  email_template_qweb/models/mail_template.py
Labels: approved, bot is merging ⏳, needs review

#526 [13.0][IMP] mail_tracking: Port improvements from 12.0
  mail_restrict_follower_selection/models/mail_thread.py
  mail_tracking/README.rst
  mail_tracking/models/__init__.py
  mail_tracking/models/mail_alias.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_thread.py
  mail_tracking/readme/USAGE.rst
  mail_tracking/static/description/index.html
  mail_tracking/static/src/img/anon_user.png
  mail_tracking/static/src/xml/mail_tracking.xml
  mail_tracking/tests/test_mail_tracking.py
Labels: bot is merging ⏳

#536 [12.0][IMP] mail_tracking: ignore catchall
  mail_restrict_follower_selection/models/mail_thread.py
  mail_tracking/models/__init__.py
  mail_tracking/models/ir_config_parameter.py
  mail_tracking/models/mail_alias.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳

#538 [13.0][IMP] mail_tracking: Ignore catchall
  mail_restrict_follower_selection/models/mail_thread.py
  mail_tracking/models/__init__.py
  mail_tracking/models/ir_config_parameter.py
  mail_tracking/models/mail_alias.py
  mail_tracking/tests/test_mail_tracking.py
Labels: bot is merging ⏳

#537 FIX image display
  mail_attach_existing_attachment/readme/USAGE.rst
Labels: bot is merging ⏳

#534 Fix mail_inline_css transform hook
  mail_inline_css/models/mail_template.py
Labels: approved, bot is merging ⏳, needs review
