Repository OCA/social, pull requests merged in 2020-06, with the labels that each got.

#550 [MIG] mail_tracking_mass_mailing: Migration to 13.0
  mail_tracking_mass_mailing/README.rst
  mail_tracking_mass_mailing/__init__.py
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/hooks.py
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/da.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/el_GR.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/es_CO.po
  mail_tracking_mass_mailing/i18n/eu.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/gl.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/hr_HR.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/i18n/nb_NO.po
  mail_tracking_mass_mailing/i18n/nl.po
  mail_tracking_mass_mailing/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/pl.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/pt_BR.po
  mail_tracking_mass_mailing/i18n/ro.po
  mail_tracking_mass_mailing/i18n/ru.po
  mail_tracking_mass_mailing/i18n/sl.po
  mail_tracking_mass_mailing/i18n/tr.po
  mail_tracking_mass_mailing/models/__init__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mail_tracking_email.py
  mail_tracking_mass_mailing/models/mail_tracking_event.py
  mail_tracking_mass_mailing/models/mailing_contact.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/readme/CONTRIBUTORS.rst
  mail_tracking_mass_mailing/readme/DESCRIPTION.rst
  mail_tracking_mass_mailing/readme/INSTALL.rst
  mail_tracking_mass_mailing/readme/USAGE.rst
  mail_tracking_mass_mailing/static/description/icon.png
  mail_tracking_mass_mailing/static/description/index.html
  mail_tracking_mass_mailing/tests/__init__.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mail_tracking_mass_mailing/views/mail_mass_mailing_view.xml
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mail_tracking_mass_mailing/views/mail_tracking_email_view.xml
  mail_tracking_mass_mailing/views/mailing_contact_view.xml
Labels: approved, bot is merging ⏳, needs review

#551 Update README.rst
  base_search_mail_content/README.rst
Labels: bot is merging ⏳

#559 [FIX] mail_drop_target: new attribute name
  mail_drop_target/models/mail_thread.py
Labels: bot is merging ⏳, bug, needs review

#557 [FIX] mail_tracking: do not slurp exceptions
  mail_tracking/models/ir_mail_server.py
Labels: approved, bot is merging ⏳, bug

#560 [12.0][FIX] mass_mailing_custom_unsubscribe: mailing contact contains `opt_out`
  mass_mailing_custom_unsubscribe/controllers/main.py
Labels: bot is merging ⏳
