Repository OCA/social, pull requests merged in 2020-11, with the labels that each got.

#637 [13.0] [FIX] mail_debrand: Fixed travis error.
  mail_debrand/__manifest__.py
Labels: approved, bot is merging ⏳

#639 [FIX] mail_drop_target: Fix method signature due to change into odoo v13
  mail_drop_target/models/mail_thread.py
Labels: approved, bot is merging ⏳

#633 [12.0][FIX] mass_mailing_partner: partner merge
  mass_mailing_partner/readme/CONTRIBUTORS.rst
  mass_mailing_partner/tests/test_mail_mass_mailing_contact.py
  mass_mailing_partner/wizard/__init__.py
  mass_mailing_partner/wizard/partner_merge.py
Labels: approved, bot is merging ⏳

#641 [13.0][FIX] mass_mailing_partner: partner merge
  mass_mailing_partner/readme/CONTRIBUTORS.rst
  mass_mailing_partner/tests/test_mail_mass_mailing_contact.py
  mass_mailing_partner/wizard/__init__.py
  mass_mailing_partner/wizard/partner_merge.py
Labels: approved, bot is merging ⏳

#638 [UPD] Brainbean Apps => CorporateHub
  mail_activity_reminder/__manifest__.py
  mail_activity_reminder/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#510 [11.0][FIX][IMP] mail_activity_team
  mail_activity_team/__manifest__.py
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_thread.py
  mail_activity_team/static/src/xml/activity.xml
Labels: approved, bot is merging ⏳, ready to merge

#631 [FIX] re.search will return None when nothing found. So we have to check for this
  mail_tracking/models/ir_mail_server.py
Labels: bot is merging ⏳
