Repository OCA/social, pull requests merged in 2020-12, with the labels that each got.

#642 [13.0][MIG] mass_mailing_custom_unsubscribe_event: Migration to 13.0
  mass_mailing_custom_unsubscribe_event/README.rst
  mass_mailing_custom_unsubscribe_event/__init__.py
  mass_mailing_custom_unsubscribe_event/__manifest__.py
  mass_mailing_custom_unsubscribe_event/demo/assets.xml
  mass_mailing_custom_unsubscribe_event/i18n/mass_mailing_custom_unsubscribe_event.pot
  mass_mailing_custom_unsubscribe_event/models/__init__.py
  mass_mailing_custom_unsubscribe_event/models/event_registration.py
  mass_mailing_custom_unsubscribe_event/readme/CONTRIBUTORS.rst
  mass_mailing_custom_unsubscribe_event/readme/DESCRIPTION.rst
  mass_mailing_custom_unsubscribe_event/readme/USAGE.rst
  mass_mailing_custom_unsubscribe_event/static/description/icon.png
  mass_mailing_custom_unsubscribe_event/static/description/index.html
  mass_mailing_custom_unsubscribe_event/static/src/js/tour.js
  mass_mailing_custom_unsubscribe_event/tests/__init__.py
  mass_mailing_custom_unsubscribe_event/tests/test_ui.py
  mass_mailing_custom_unsubscribe_event/views/event_registration_views.xml
Labels: approved, bot is merging ⏳

#624 [FIX] mail_tracking: Discuss failed messages: Button and domain
  mail_tracking/demo/demo.xml
  mail_tracking/models/mail_message.py
  mail_tracking/static/src/js/failed_message/discuss.js
  mail_tracking/static/src/xml/failed_message/discuss.xml
  mail_tracking/tests/test_mail_tracking.py
Labels: bot is merging ⏳

#646 [12.0][IMP] mass_mailing_partner: Add partner_name in error constrain message
  mass_mailing_partner/models/mail_mass_mailing_contact.py
Labels: approved, bot is merging ⏳

#647 [13.0][IMP] mass_mailing_partner: Add partner_name in error constrain message
  mass_mailing_partner/models/mailing_contact.py
Labels: bot is merging ⏳

#489 Add mail_layout_preview
  mail_layout_preview/README.rst
  mail_layout_preview/__init__.py
  mail_layout_preview/__manifest__.py
  mail_layout_preview/controllers/__init__.py
  mail_layout_preview/controllers/layout_preview.py
  mail_layout_preview/readme/CONTRIBUTORS.rst
  mail_layout_preview/readme/DESCRIPTION.rst
  mail_layout_preview/readme/USAGE.rst
  mail_layout_preview/static/description/icon.png
  mail_layout_preview/static/description/index.html
  mail_layout_preview/templates/email_preview.xml
  mail_layout_preview/tests/__init__.py
  mail_layout_preview/tests/test_layout_preview.py
  mail_layout_preview/wizard/__init__.py
  mail_layout_preview/wizard/email_template_preview.py
  mail_layout_preview/wizard/email_template_preview.xml
  setup/mail_layout_preview/odoo/addons/mail_layout_preview
  setup/mail_layout_preview/setup.py
Labels: bot is merging ⏳, needs review
