Repository OCA/social, pull requests merged in 2020-05, with the labels that each got.

#540 [12.0][FIX] api multi constrain mistake
  mail_activity_team/models/mail_activity.py
Labels: approved, ready to merge

#542 [12.0] [UPD] .travis.yml
  .travis.yml
Labels: bot is merging ⏳

#501 [12.0][ADD] mail_activity_reminder
  .travis.yml
  mail_activity_reminder/README.rst
  mail_activity_reminder/__init__.py
  mail_activity_reminder/__manifest__.py
  mail_activity_reminder/data/mail_activity_reminder_cron.xml
  mail_activity_reminder/models/__init__.py
  mail_activity_reminder/models/mail_activity.py
  mail_activity_reminder/models/mail_activity_type.py
  mail_activity_reminder/readme/CONFIGURE.rst
  mail_activity_reminder/readme/CONTRIBUTORS.rst
  mail_activity_reminder/readme/DESCRIPTION.rst
  mail_activity_reminder/readme/ROADMAP.rst
  mail_activity_reminder/static/description/index.html
  mail_activity_reminder/tests/__init__.py
  mail_activity_reminder/tests/test_mail_activity_reminder.py
  mail_activity_reminder/views/mail_activity_type.xml
  test-requirements.txt
Labels: bot is merging ⏳, needs review
