Repository OCA/social, pull requests merged in 2020-08, with the labels that each got.

#581 [12.0][FIX] mail_restrict_follower_selection: res_model not always in context
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
Labels: approved, bot is merging ⏳, ready to merge

#586 [12.0][ADD] addons table, translation status
  README.md
Labels: approved, ready to merge

#587 [13.0][ADD] addons table, translation status
  README.md
Labels: approved, ready to merge

#552 [12.0][MIG] mail_private
  mail_private/README.rst
  mail_private/__init__.py
  mail_private/__manifest__.py
  mail_private/models/__init__.py
  mail_private/models/ir_attachment.py
  mail_private/models/ir_model.py
  mail_private/models/mail_channel.py
  mail_private/models/mail_message.py
  mail_private/models/mail_security_group.py
  mail_private/models/mail_thread.py
  mail_private/models/res_partner.py
  mail_private/models/res_users.py
  mail_private/readme/CONFIGURE.rst
  mail_private/readme/CONTRIBUTORS.rst
  mail_private/readme/DESCRIPTION.rst
  mail_private/readme/USAGE.rst
  mail_private/security/ir.model.access.csv
  mail_private/security/security.xml
  mail_private/static/description/icon.png
  mail_private/static/description/index.html
  mail_private/static/src/js/composer.js
  mail_private/static/src/js/message.js
  mail_private/static/src/js/thread.js
  mail_private/static/src/scss/message.scss
  mail_private/static/src/xml/composer.xml
  mail_private/static/src/xml/thread.xml
  mail_private/views/assets.xml
  mail_private/views/ir_model.xml
  mail_private/views/mail_message.xml
  mail_private/views/mail_security_group.xml
  mail_private/wizards/__init__.py
  mail_private/wizards/mail_compose_message.py
  mail_private/wizards/mail_compose_message.xml
  test_mail_private/README.rst
  test_mail_private/__init__.py
  test_mail_private/__manifest__.py
  test_mail_private/readme/CONTRIBUTORS.rst
  test_mail_private/readme/DESCRIPTION.rst
  test_mail_private/static/description/icon.png
  test_mail_private/static/description/index.html
  test_mail_private/tests/__init__.py
  test_mail_private/tests/test_mail_private.py
Labels: approved, bot is merging ⏳, ready to merge

#592 [FIX] test_mail_private: manifest URL
  test_mail_private/__manifest__.py
Labels: bot is merging ⏳

#593 [ADD] mail_history: Backport from version 13.0 of the history of messages
  mail_history/README.rst
  mail_history/__init__.py
  mail_history/__manifest__.py
  mail_history/hooks.py
  mail_history/models/__init__.py
  mail_history/models/mail_message.py
  mail_history/models/mail_notification.py
  mail_history/readme/CONFIGURE.rst
  mail_history/readme/CONTRIBUTORS.rst
  mail_history/readme/DESCRIPTION.rst
  mail_history/readme/INSTALL.rst
  mail_history/readme/ROADMAP.rst
  mail_history/readme/USAGE.rst
  mail_history/static/description/index.html
  mail_history/static/src/js/discuss.js
  mail_history/static/src/js/mail_manager.js
  mail_history/static/src/js/mailbox.js
  mail_history/static/src/js/message.js
  mail_history/static/src/xml/discuss.xml
  mail_history/static/src/xml/thread.xml
  mail_history/views/assets.xml
Labels: approved, bot is merging ⏳, needs review

#597 Fix issue on empty template with premailer
  mail_inline_css/models/mail_template.py
Labels: approved, bot is merging ⏳

#594 [13.0][MIG] mail_attach_existing_attachment
  mail_attach_existing_attachment/README.rst
  mail_attach_existing_attachment/__init__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_attach_existing_attachment/i18n/ca.po
  mail_attach_existing_attachment/i18n/de.po
  mail_attach_existing_attachment/i18n/es.po
  mail_attach_existing_attachment/i18n/es_CO.po
  mail_attach_existing_attachment/i18n/fr.po
  mail_attach_existing_attachment/i18n/hr.po
  mail_attach_existing_attachment/i18n/it.po
  mail_attach_existing_attachment/i18n/mail_attach_existing_attachment.pot
  mail_attach_existing_attachment/i18n/pt_BR.po
  mail_attach_existing_attachment/i18n/sl.po
  mail_attach_existing_attachment/i18n/zh_CN.po
  mail_attach_existing_attachment/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment/readme/DESCRIPTION.rst
  mail_attach_existing_attachment/readme/ROADMAP.rst
  mail_attach_existing_attachment/readme/USAGE.rst
  mail_attach_existing_attachment/static/description/attachment.png
  mail_attach_existing_attachment/static/description/ex_mail_compose_message.png
  mail_attach_existing_attachment/static/description/icon.png
  mail_attach_existing_attachment/static/description/index.html
  mail_attach_existing_attachment/tests/__init__.py
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment/wizard/__init__.py
  mail_attach_existing_attachment/wizard/mail_compose_message.py
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
Labels: bot is merging ⏳, needs review

#599 [13.0] [FIX] mass_mailing_custom_unsubscribe and mail_activity_done: Added changes to avoid the linter warnings
  mail_activity_done/static/src/js/mail_activity.js
  mass_mailing_custom_unsubscribe/static/src/js/contact.tour.js
  mass_mailing_custom_unsubscribe/static/src/js/partner.tour.js
Labels: bot is merging ⏳

#539 [11.0][MIG] mail_outbound_static: backport from 12.0
  mail_outbound_static/README.rst
  mail_outbound_static/__init__.py
  mail_outbound_static/__manifest__.py
  mail_outbound_static/i18n/mail_outbound_static.pot
  mail_outbound_static/models/__init__.py
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/readme/CONTRIBUTORS.rst
  mail_outbound_static/readme/DESCRIPTION.rst
  mail_outbound_static/readme/ROADMAP.rst
  mail_outbound_static/readme/USAGE.rst
  mail_outbound_static/static/description/icon.png
  mail_outbound_static/static/description/index.html
  mail_outbound_static/tests/__init__.py
  mail_outbound_static/tests/test.msg
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_outbound_static/views/ir_mail_server_view.xml
Labels: approved, bot is merging ⏳
