Repository OCA/social, pull requests merged in 2020-09, with the labels that each got.

#602 [12.0][FIX] mass_mailing_resend: Incorrect warning text
  mass_mailing_resend/__manifest__.py
  mass_mailing_resend/i18n/es.po
  mass_mailing_resend/i18n/mass_mailing_resend.pot
  mass_mailing_resend/views/mass_mailing_views.xml
Labels: approved, bot is merging ⏳

#519 [13.0][MIG] mail_drop_target
  mail_drop_target/README.rst
  mail_drop_target/__init__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/i18n/mail_drop_target.pot
  mail_drop_target/models/__init__.py
  mail_drop_target/models/mail_thread.py
  mail_drop_target/models/res_config_settings.py
  mail_drop_target/readme/CONFIGURATION.rst
  mail_drop_target/readme/CONTRIBUTORS.rst
  mail_drop_target/readme/DESCRIPTION.rst
  mail_drop_target/readme/ROADMAP.rst
  mail_drop_target/readme/USAGE.rst
  mail_drop_target/static/description/icon.png
  mail_drop_target/static/description/index.html
  mail_drop_target/static/src/css/mail_drop_target.css
  mail_drop_target/static/src/js/mail_drop_target.js
  mail_drop_target/tests/__init__.py
  mail_drop_target/tests/sample.eml
  mail_drop_target/tests/sample.msg
  mail_drop_target/tests/test_mail_drop_target.py
  mail_drop_target/views/res_config_settings_views.xml
  mail_drop_target/views/templates.xml
  oca_dependencies.txt
  requirements.txt
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#608 [13.0][FWD] mail_inline_css: fix transform hook
  mail_inline_css/models/mail_template.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#612 [IMP] mail_activity_board: Open all from systray icon
  mail_activity_board/__manifest__.py
  mail_activity_board/static/src/js/systray.js
  mail_activity_board/static/src/xml/systray.xml
  mail_activity_board/views/templates.xml
  mail_activity_team/static/src/js/systray.js
  mail_activity_team/static/src/xml/systray.xml
Labels: approved, bot is merging ⏳, ready to merge

#604 [12.0][ADD] mail_preview_base & mail_preview_audio
  mail_preview_audio/README.rst
  mail_preview_audio/__init__.py
  mail_preview_audio/__manifest__.py
  mail_preview_audio/readme/CONTRIBUTORS.rst
  mail_preview_audio/readme/DESCRIPTION.rst
  mail_preview_audio/static/description/icon.png
  mail_preview_audio/static/description/index.html
  mail_preview_audio/static/src/js/preview.js
  mail_preview_audio/static/src/xml/preview.xml
  mail_preview_audio/template/assets.xml
  mail_preview_base/README.rst
  mail_preview_base/__init__.py
  mail_preview_base/__manifest__.py
  mail_preview_base/readme/CONTRIBUTORS.rst
  mail_preview_base/readme/DESCRIPTION.rst
  mail_preview_base/readme/USAGE.rst
  mail_preview_base/static/description/icon.png
  mail_preview_base/static/description/index.html
  mail_preview_base/static/src/js/preview.js
  mail_preview_base/static/src/scss/preview.scss
  mail_preview_base/static/src/xml/preview.xml
  mail_preview_base/template/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#613 [13.0][FIX] mail_debrand: support all languages
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_template.py
  mail_debrand/tests/test_mail_debrand.py
Labels: approved, bot is merging ⏳

#615 [12.0][FIX] mail_preview_audio: fix javascript dependencies loading
  mail_preview_audio/static/src/js/preview.js
  mail_preview_base/static/src/js/preview.js
Labels: approved, bot is merging ⏳
