Repository OCA/social, pull requests merged in 2020-03, with the labels that each got.

#420 [12.0][ADD] - new module: mail template substitute
  mail_template_substitute/README.rst
  mail_template_substitute/__init__.py
  mail_template_substitute/__manifest__.py
  mail_template_substitute/models/__init__.py
  mail_template_substitute/models/mail_template.py
  mail_template_substitute/models/mail_template_substitution_rule.py
  mail_template_substitute/readme/CONTRIBUTORS.rst
  mail_template_substitute/readme/DESCRIPTION.rst
  mail_template_substitute/readme/ROADMAP.rst
  mail_template_substitute/readme/USAGE.rst
  mail_template_substitute/security/mail_template_substitution_rule.xml
  mail_template_substitute/static/description/index.html
  mail_template_substitute/tests/__init__.py
  mail_template_substitute/tests/test_mail_template_substitute.py
  mail_template_substitute/views/mail_template.xml
  mail_template_substitute/wizards/__init__.py
  mail_template_substitute/wizards/mail_compose_message.py
  oca_dependencies.txt
  setup/mail_template_substitute/odoo/addons/mail_template_substitute
  setup/mail_template_substitute/setup.py
Labels: approved, needs review, ready to merge

#516 travis conf: add runnig_env
  .travis.yml
Labels: bug

#242 [ADD] mail_drop_target
  .travis.yml
  mail_drop_target/README.rst
  mail_drop_target/__init__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/models/__init__.py
  mail_drop_target/models/mail_thread.py
  mail_drop_target/static/description/icon.png
  mail_drop_target/static/src/css/mail_drop_target.css
  mail_drop_target/static/src/js/mail_drop_target.js
  mail_drop_target/tests/__init__.py
  mail_drop_target/tests/sample.eml
  mail_drop_target/tests/sample.msg
  mail_drop_target/tests/test_mail_drop_target.py
  mail_drop_target/views/templates.xml
  oca_dependencies.txt
Labels: approved, needs review, ready to merge

#503 [12.0][MIG] mail_drop_target
  mail_drop_target/README.rst
  mail_drop_target/__init__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/i18n/mail_drop_target.pot
  mail_drop_target/models/__init__.py
  mail_drop_target/models/mail_message.py
  mail_drop_target/models/mail_thread.py
  mail_drop_target/models/res_config_settings.py
  mail_drop_target/readme/CONFIGURATION.rst
  mail_drop_target/readme/CONTRIBUTORS.rst
  mail_drop_target/readme/DESCRIPTION.rst
  mail_drop_target/readme/ROADMAP.rst
  mail_drop_target/readme/USAGE.rst
  mail_drop_target/static/description/icon.png
  mail_drop_target/static/description/index.html
  mail_drop_target/static/src/css/mail_drop_target.css
  mail_drop_target/static/src/js/mail_drop_target.js
  mail_drop_target/tests/__init__.py
  mail_drop_target/tests/sample.eml
  mail_drop_target/tests/sample.msg
  mail_drop_target/tests/test_mail_drop_target.py
  mail_drop_target/views/res_config_settings_views.xml
  mail_drop_target/views/templates.xml
  oca_dependencies.txt
  requirements.txt
Labels: approved, ready to merge

#453 13.0 mig mail activity team
  mail_activity_team/README.rst
  mail_activity_team/__init__.py
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/readme/DESCRIPTION.rst
  mail_activity_team/readme/USAGE.rst
  mail_activity_team/security/ir.model.access.csv
  mail_activity_team/security/mail_activity_team_security.xml
  mail_activity_team/static/description/icon.png
  mail_activity_team/static/description/index.html
  mail_activity_team/tests/__init__.py
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/mail_activity_team_views.xml
  mail_activity_team/views/mail_activity_views.xml
  mail_activity_team/views/res_users_views.xml
Labels: approved, ready to merge

#512 12.0 mig mail restrict follower selection
  mail_restrict_follower_selection/README.rst
  mail_restrict_follower_selection/__init__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/data/ir_actions.xml
  mail_restrict_follower_selection/data/ir_config_parameter.xml
  mail_restrict_follower_selection/i18n/de.po
  mail_restrict_follower_selection/i18n/en.po
  mail_restrict_follower_selection/i18n/fr.po
  mail_restrict_follower_selection/i18n/hr.po
  mail_restrict_follower_selection/i18n/it.po
  mail_restrict_follower_selection/i18n/mail_restrict_follower_selection.pot
  mail_restrict_follower_selection/i18n/sl.po
  mail_restrict_follower_selection/models/__init__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_thread.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/static/description/icon.png
  mail_restrict_follower_selection/tests/__init__.py
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
Labels: approved, ready to merge

#507 [FIX] mail_debrand: template with original terms
  mail_debrand/models/mail_template.py
Labels: approved

#522 [IMP] mass_mailing_unique: informative constraint
  mass_mailing_unique/models/mail_mass_mailing_contact.py
Labels: approved, needs review

#517 [13.0][MIG] mail_restrict_follower_selection
  mail_restrict_follower_selection/README.rst
  mail_restrict_follower_selection/__init__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/data/ir_actions.xml
  mail_restrict_follower_selection/data/ir_config_parameter.xml
  mail_restrict_follower_selection/i18n/de.po
  mail_restrict_follower_selection/i18n/en.po
  mail_restrict_follower_selection/i18n/fr.po
  mail_restrict_follower_selection/i18n/hr.po
  mail_restrict_follower_selection/i18n/it.po
  mail_restrict_follower_selection/i18n/mail_restrict_follower_selection.pot
  mail_restrict_follower_selection/i18n/sl.po
  mail_restrict_follower_selection/models/__init__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_thread.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/readme/CONFIGURE.rst
  mail_restrict_follower_selection/readme/CONTRIBUTORS.rst
  mail_restrict_follower_selection/readme/DESCRIPTION.rst
  mail_restrict_follower_selection/static/description/icon.png
  mail_restrict_follower_selection/tests/__init__.py
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
Labels: approved, ready to merge

#494 [11.0][ADD] mail_activity_creator
  mail_activity_creator/README.rst
  mail_activity_creator/__init__.py
  mail_activity_creator/__manifest__.py
  mail_activity_creator/models/__init__.py
  mail_activity_creator/models/mail_activity.py
  mail_activity_creator/readme/CONTRIBUTORS.rst
  mail_activity_creator/readme/DESCRIPTION.rst
  mail_activity_creator/static/description/icon.png
  mail_activity_creator/static/description/index.html
  mail_activity_creator/static/src/xml/activity.xml
  mail_activity_creator/tests/__init__.py
  mail_activity_creator/tests/test_creator.py
  mail_activity_creator/views/mail_activity_views.xml
Labels: approved, ready to merge

#524 [IMP] mail_tracking: Store To recipients and omit aliases
  mail_tracking/README.rst
  mail_tracking/models/__init__.py
  mail_tracking/models/mail_alias.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_thread.py
  mail_tracking/readme/USAGE.rst
  mail_tracking/static/description/index.html
  mail_tracking/static/src/img/anon_user.png
  mail_tracking/static/src/xml/mail_tracking.xml
  mail_tracking/tests/test_mail_tracking.py
Labels: approved

#525 [13.0][MIG] mail_debrand: Migration to 13.0
  mail_debrand/README.rst
  mail_debrand/__init__.py
  mail_debrand/__manifest__.py
  mail_debrand/i18n/fr.po
  mail_debrand/i18n/mail_debrand.pot
  mail_debrand/i18n/pt.po
  mail_debrand/i18n/sl.po
  mail_debrand/i18n/sr_Latn.po
  mail_debrand/models/__init__.py
  mail_debrand/models/mail_template.py
  mail_debrand/models/mail_thread.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/readme/DESCRIPTION.rst
  mail_debrand/readme/HISTORY.rst
  mail_debrand/readme/USAGE.rst
  mail_debrand/static/description/icon.png
  mail_debrand/static/description/icon.svg
  mail_debrand/static/description/index.html
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand.py
Labels: approved

#531 [FIX] mail_tracking: do not warn not found if already opened
  mail_tracking/controllers/main.py
Labels: approved, bot is merging ⏳
