Repository OCA/social, pull requests merged in 2020-07, with the labels that each got.

#529 [IMP] mail_activity_team: include meetings
  mail_activity_team/__manifest__.py
  mail_activity_team/migrations/11.0.2.2.0/post-migration.py
  mail_activity_team/models/__init__.py
  mail_activity_team/models/calendar_event.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/security/mail_activity_team_security.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/calendar_event.xml
Labels: approved, bot is merging ⏳

#564 [13.0][FIX] mail_activity_board: unlink issue due to bad migration
  mail_activity_board/models/mail_activity.py
Labels: approved, bot is merging ⏳

#570 [10.0][FIX] travis: set premailer version fixe to last compatible with python2
  requirements.txt
Labels: bot is merging ⏳

#571 [12.0][FIX] mass_mailing_list_dynamic: list sync on send
  mass_mailing_list_dynamic/models/mail_mass_mailing.py
Labels: approved, bot is merging ⏳

#523 [13.0][FIX] mass_mailing_partner: Unsubscribe should not unlink the subscription.
  mass_mailing_partner/README.rst
  mass_mailing_partner/models/mailing_contact.py
  mass_mailing_partner/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#554 [MIG] fetchmail_thread_default: Migration to 12.0
  fetchmail_thread_default/README.rst
  fetchmail_thread_default/__init__.py
  fetchmail_thread_default/__manifest__.py
  fetchmail_thread_default/demo/data.xml
  fetchmail_thread_default/i18n/.empty
  fetchmail_thread_default/i18n/ca.po
  fetchmail_thread_default/i18n/de.po
  fetchmail_thread_default/i18n/es.po
  fetchmail_thread_default/i18n/fetchmail_thread_default.pot
  fetchmail_thread_default/i18n/fr.po
  fetchmail_thread_default/i18n/hr.po
  fetchmail_thread_default/i18n/it.po
  fetchmail_thread_default/i18n/pt_BR.po
  fetchmail_thread_default/i18n/pt_PT.po
  fetchmail_thread_default/i18n/sl.po
  fetchmail_thread_default/i18n/tr.po
  fetchmail_thread_default/i18n/zh_CN.po
  fetchmail_thread_default/models/__init__.py
  fetchmail_thread_default/models/fetchmail_server.py
  fetchmail_thread_default/models/mail_thread.py
  fetchmail_thread_default/readme/CONFIGURE.rst
  fetchmail_thread_default/readme/CONTRIBUTORS.rst
  fetchmail_thread_default/readme/DESCRIPTION.rst
  fetchmail_thread_default/readme/USAGE.rst
  fetchmail_thread_default/static/description/icon.png
  fetchmail_thread_default/static/description/index.html
  fetchmail_thread_default/tests/__init__.py
  fetchmail_thread_default/tests/test_fetchmail.py
  fetchmail_thread_default/views/fetchmail_server_view.xml
Labels: approved, bot is merging ⏳

#577 [12.0][FIX] mail_tracking: performance fix
  mail_tracking/models/mail_message.py
Labels: bot is merging ⏳, bug

#576 [13.0] [MIG] fetchmail_thread_default
  fetchmail_thread_default/README.rst
  fetchmail_thread_default/__init__.py
  fetchmail_thread_default/__manifest__.py
  fetchmail_thread_default/demo/data.xml
  fetchmail_thread_default/i18n/.empty
  fetchmail_thread_default/i18n/ca.po
  fetchmail_thread_default/i18n/de.po
  fetchmail_thread_default/i18n/es.po
  fetchmail_thread_default/i18n/fetchmail_thread_default.pot
  fetchmail_thread_default/i18n/fr.po
  fetchmail_thread_default/i18n/hr.po
  fetchmail_thread_default/i18n/it.po
  fetchmail_thread_default/i18n/pt_BR.po
  fetchmail_thread_default/i18n/pt_PT.po
  fetchmail_thread_default/i18n/sl.po
  fetchmail_thread_default/i18n/tr.po
  fetchmail_thread_default/i18n/zh_CN.po
  fetchmail_thread_default/models/__init__.py
  fetchmail_thread_default/models/fetchmail_server.py
  fetchmail_thread_default/models/mail_thread.py
  fetchmail_thread_default/readme/CONFIGURE.rst
  fetchmail_thread_default/readme/CONTRIBUTORS.rst
  fetchmail_thread_default/readme/DESCRIPTION.rst
  fetchmail_thread_default/readme/USAGE.rst
  fetchmail_thread_default/static/description/icon.png
  fetchmail_thread_default/static/description/index.html
  fetchmail_thread_default/tests/__init__.py
  fetchmail_thread_default/tests/test_fetchmail.py
  fetchmail_thread_default/views/fetchmail_server_view.xml
Labels: approved, bot is merging ⏳

#575 [12.0] FIX mail_outbound_static using sudo to get ir.config_parameter, otherwise when normal users try to send email they get AccessError
  mail_outbound_static/models/ir_mail_server.py
Labels: approved, bot is merging ⏳

#562 [13.0][MIG] mail_outbound_static
  mail_outbound_static/README.rst
  mail_outbound_static/__init__.py
  mail_outbound_static/__manifest__.py
  mail_outbound_static/i18n/mail_outbound_static.pot
  mail_outbound_static/models/__init__.py
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/readme/CONTRIBUTORS.rst
  mail_outbound_static/readme/DESCRIPTION.rst
  mail_outbound_static/readme/ROADMAP.rst
  mail_outbound_static/readme/USAGE.rst
  mail_outbound_static/static/description/icon.png
  mail_outbound_static/static/description/index.html
  mail_outbound_static/tests/__init__.py
  mail_outbound_static/tests/test.msg
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_outbound_static/views/ir_mail_server_view.xml
Labels: bot is merging ⏳

#582 [FIX] 13.0 mail_outbound_static
  mail_outbound_static/models/ir_mail_server.py
Labels: bot is merging ⏳

#583 [FIX] mail_drop_target: new attribute name
  mail_drop_target/models/mail_thread.py
Labels: bot is merging ⏳

#483 [11.0][FIX] mail_restrict_follower_selection: res_model not in context
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
Labels: approved, bot is merging ⏳, ready to merge

#584 [13.0][FIX] mail_tracking_mailgun: import mock the python3 way
  mail_tracking_mailgun/tests/test_mailgun.py
Labels: bot is merging ⏳

#579 [12.0][FIX] mass_mailing_partner: get contextual list when importing contacts
  mass_mailing_partner/models/mail_mass_mailing_contact.py
Labels: approved, bot is merging ⏳, needs review

#585 [12.0][FIX] mass_mailing_list_dynamic: Avoid error on shared contacts
  mass_mailing_list_dynamic/models/mail_mass_mailing_contact.py
  mass_mailing_list_dynamic/tests/test_dynamic_lists.py
Labels: approved, bot is merging ⏳, needs review
