Repository OCA/social, pull requests merged in 2021-05, with the labels that each got.

#707 [13.0][FWD] email_template_qweb: ease override of values, include defaults
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#645 [14.0][MIG] mail_outbound_static: Migration to 14.0
  mail_outbound_static/README.rst
  mail_outbound_static/__init__.py
  mail_outbound_static/__manifest__.py
  mail_outbound_static/i18n/mail_outbound_static.pot
  mail_outbound_static/models/__init__.py
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/readme/CONTRIBUTORS.rst
  mail_outbound_static/readme/DESCRIPTION.rst
  mail_outbound_static/readme/ROADMAP.rst
  mail_outbound_static/readme/USAGE.rst
  mail_outbound_static/static/description/icon.png
  mail_outbound_static/static/description/index.html
  mail_outbound_static/tests/__init__.py
  mail_outbound_static/tests/test.msg
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_outbound_static/views/ir_mail_server_view.xml
  setup/mail_outbound_static/odoo/addons/mail_outbound_static
  setup/mail_outbound_static/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#716 [FIX] mass_mailing_partner: Use correct button class
  mass_mailing_partner/views/res_partner_view.xml
Labels: bot is merging ⏳

#710 [14.0] mail_send_copy: description wording
  mail_send_copy/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳, ready to merge

#487 [11.0][ADD] mail_private
  mail_private/README.rst
  mail_private/__init__.py
  mail_private/__manifest__.py
  mail_private/models/__init__.py
  mail_private/models/ir_attachment.py
  mail_private/models/ir_model.py
  mail_private/models/mail_channel.py
  mail_private/models/mail_message.py
  mail_private/models/mail_security_group.py
  mail_private/models/mail_thread.py
  mail_private/models/res_partner.py
  mail_private/models/res_users.py
  mail_private/readme/CONFIGURE.rst
  mail_private/readme/CONTRIBUTORS.rst
  mail_private/readme/DESCRIPTION.rst
  mail_private/readme/USAGE.rst
  mail_private/security/ir.model.access.csv
  mail_private/security/security.xml
  mail_private/static/description/icon.png
  mail_private/static/description/index.html
  mail_private/static/src/js/composer.js
  mail_private/static/src/js/message.js
  mail_private/static/src/less/message.less
  mail_private/static/src/xml/composer.xml
  mail_private/static/src/xml/thread.xml
  mail_private/tests/__init__.py
  mail_private/tests/test_mail_private.py
  mail_private/views/assets.xml
  mail_private/views/ir_model.xml
  mail_private/views/mail_message.xml
  mail_private/views/mail_security_group.xml
  mail_private/wizards/__init__.py
  mail_private/wizards/mail_compose_message.py
  mail_private/wizards/mail_compose_message.xml
Labels: approved, bot is merging ⏳, ready to merge

#717 [FIX] mail_debrand: avoid KeyError: 'body_html' on plain text emails
  mail_debrand/models/mail_render_mixinANDmail_mail.py
  mail_debrand/tests/test_mail_debrand.py
Labels: approved, bot is merging ⏳

#681 [MIG] mail_layout_preview: Migration to 14.0
  mail_layout_preview/README.rst
  mail_layout_preview/__init__.py
  mail_layout_preview/__manifest__.py
  mail_layout_preview/controllers/__init__.py
  mail_layout_preview/controllers/layout_preview.py
  mail_layout_preview/i18n/mail_layout_preview.pot
  mail_layout_preview/readme/CONTRIBUTORS.rst
  mail_layout_preview/readme/CREDITS.rst
  mail_layout_preview/readme/DESCRIPTION.rst
  mail_layout_preview/readme/USAGE.rst
  mail_layout_preview/static/description/icon.png
  mail_layout_preview/static/description/index.html
  mail_layout_preview/templates/email_preview.xml
  mail_layout_preview/tests/__init__.py
  mail_layout_preview/tests/test_layout_preview.py
  mail_layout_preview/wizard/__init__.py
  mail_layout_preview/wizard/email_template_preview.py
  mail_layout_preview/wizard/email_template_preview.xml
  setup/mail_layout_preview/odoo/addons/mail_layout_preview
  setup/mail_layout_preview/setup.py
Labels: approved, bot is merging ⏳, ready to merge
