Repository OCA/social, pull requests merged in 2021-01, with the labels that each got.

#479 [13.0][MIG] mail_activity_partner
  mail_activity_partner/README.rst
  mail_activity_partner/__init__.py
  mail_activity_partner/__manifest__.py
  mail_activity_partner/i18n/mail_activity_partner.pot
  mail_activity_partner/models/__init__.py
  mail_activity_partner/models/mail_activity.py
  mail_activity_partner/readme/CONTRIBUTORS.rst
  mail_activity_partner/readme/DESCRIPTION.rst
  mail_activity_partner/readme/USAGE.rst
  mail_activity_partner/static/description/icon.png
  mail_activity_partner/static/description/index.html
  mail_activity_partner/tests/__init__.py
  mail_activity_partner/tests/test_mail_activity_partner.py
  mail_activity_partner/views/mail_activity_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#462 [ADD][12.0] module mail_send_bcc to receive all mail sent by Odoo in bcc
  .travis.yml
  mail_send_copy/README.rst
  mail_send_copy/__init__.py
  mail_send_copy/__manifest__.py
  mail_send_copy/i18n/fr.po
  mail_send_copy/models/__init__.py
  mail_send_copy/models/ir_mail_server.py
  mail_send_copy/readme/CONTRIBUTORS.rst
  mail_send_copy/readme/DESCRIPTION.rst
  mail_send_copy/readme/ROADMAP.rst
  mail_send_copy/static/description/icon.png
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳, needs review

#654 14.0 mig mail send copy
  mail_send_copy/README.rst
  mail_send_copy/__init__.py
  mail_send_copy/__manifest__.py
  mail_send_copy/i18n/fr.po
  mail_send_copy/i18n/mail_send_copy.pot
  mail_send_copy/models/__init__.py
  mail_send_copy/models/ir_mail_server.py
  mail_send_copy/readme/CONTRIBUTORS.rst
  mail_send_copy/readme/DESCRIPTION.rst
  mail_send_copy/readme/ROADMAP.rst
  mail_send_copy/static/description/icon.png
  mail_send_copy/static/description/index.html
  setup/mail_send_copy/odoo/addons/mail_send_copy
  setup/mail_send_copy/setup.py
Labels: approved, bot is merging ⏳

#650 [ADD] mail_notification_custom_subject: Apply a custom subject to mail notifications
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es_ES.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.rst
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
  mail_notification_custom_subject/readme/DESCRIPTION.rst
  mail_notification_custom_subject/readme/USAGE.rst
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#610 [12.0][FWD] email_template_qweb: ease override of values, include defaults
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, needs review, ready to merge

#659 [13.0] [FIX] mail_tracking
  mail_tracking/models/mail_resend_message.py
Labels: approved, bot is merging ⏳
