Repository OCA/social, pull requests merged in 2021-09, with the labels that each got.

#762 [13.0] [FWD] [ADD] mail_autosubscribe: New Module
  .travis.yml
  mail_autosubscribe/README.rst
  mail_autosubscribe/__init__.py
  mail_autosubscribe/__manifest__.py
  mail_autosubscribe/i18n/mail_autosubscribe.pot
  mail_autosubscribe/models/__init__.py
  mail_autosubscribe/models/mail_autosubscribe.py
  mail_autosubscribe/models/mail_template.py
  mail_autosubscribe/models/mail_thread.py
  mail_autosubscribe/models/models.py
  mail_autosubscribe/models/res_partner.py
  mail_autosubscribe/readme/CONFIGURE.rst
  mail_autosubscribe/readme/CONTRIBUTORS.rst
  mail_autosubscribe/readme/DESCRIPTION.rst
  mail_autosubscribe/readme/ROADMAP.rst
  mail_autosubscribe/security/ir.model.access.csv
  mail_autosubscribe/static/description/icon.png
  mail_autosubscribe/static/description/index.html
  mail_autosubscribe/tests/__init__.py
  mail_autosubscribe/tests/models/__init__.py
  mail_autosubscribe/tests/models/fake_order.py
  mail_autosubscribe/tests/test_mail_autosubscribe.py
  mail_autosubscribe/views/mail_autosubscribe.xml
  mail_autosubscribe/views/mail_template.xml
  mail_autosubscribe/views/res_partner.xml
  setup/mail_autosubscribe/odoo/addons/mail_autosubscribe
  setup/mail_autosubscribe/setup.py
Labels: approved, bot is merging ⏳

#721 [14.0] [NEW] mail_allow_portal_internal_note: allow internal note to portal user.
  mail_allow_portal_internal_note/README.rst
  mail_allow_portal_internal_note/__init__.py
  mail_allow_portal_internal_note/__manifest__.py
  mail_allow_portal_internal_note/controllers/__init__.py
  mail_allow_portal_internal_note/controllers/mail.py
  mail_allow_portal_internal_note/models/__init__.py
  mail_allow_portal_internal_note/models/res_users.py
  mail_allow_portal_internal_note/readme/CONFIGURE.rst
  mail_allow_portal_internal_note/readme/CONTRIBUTORS.rst
  mail_allow_portal_internal_note/readme/DESCRIPTION.rst
  mail_allow_portal_internal_note/views/res_users.xml
  setup/mail_allow_portal_internal_note/odoo/addons/mail_allow_portal_internal_note
  setup/mail_allow_portal_internal_note/setup.py
Labels: approved, bot is merging ⏳

#769 [14.0][FIX] mail_restrict_send_button (Issue #768)
  mail_restrict_send_button/static/src/js/chatter.js
Labels: approved, bot is merging ⏳

#770 [14.0][IMP] mail_debrand: Keep message body intact while removing branding
  mail_debrand/README.rst
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_mail.py
  mail_debrand/models/mail_render_mixin.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/static/description/index.html
  mail_debrand/tests/test_mail_debrand.py
Labels: approved

#772 [14.0][ADD] mass_mailing_subscription_date
  mass_mailing_subscription_date/__init__.py
  mass_mailing_subscription_date/__manifest__.py
  mass_mailing_subscription_date/hooks.py
  mass_mailing_subscription_date/models/__init__.py
  mass_mailing_subscription_date/models/mailing_contact_subscription.py
  mass_mailing_subscription_date/readme/CONTRIBUTORS.rst
  mass_mailing_subscription_date/readme/DESCRIPTION.rst
  mass_mailing_subscription_date/tests/__init__.py
  mass_mailing_subscription_date/tests/test_subscription_date.py
  mass_mailing_subscription_date/views/mailing_contact_subscription.xml
  setup/mass_mailing_subscription_date/odoo/addons/mass_mailing_subscription_date
  setup/mass_mailing_subscription_date/setup.py
Labels: approved, bot is merging ⏳

#777 [FIX] mass_mailing_partner: wrong company implementation
  mass_mailing_partner/models/mail_mass_mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_list.py
  mass_mailing_partner/tests/test_partner_mail_list_wizard.py
Labels: approved, bot is merging ⏳

#778 [13.0][FIX] mass_mailing_partner: wrong company implementation
  mass_mailing_partner/models/mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_list.py
  mass_mailing_partner/tests/test_partner_mail_list_wizard.py
Labels: approved, bot is merging ⏳

#780 [14.0][FIX] mass_mailing_partner: wrong company implementation
  mass_mailing_partner/models/mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_contact.py
  mass_mailing_partner/tests/test_mail_mass_mailing_list.py
  mass_mailing_partner/tests/test_partner_mail_list_wizard.py
Labels: approved, bot is merging ⏳

#767 [14.0][ADD] mass_mailing_contact_partner
  mass_mailing_contact_partner/__init__.py
  mass_mailing_contact_partner/__manifest__.py
  mass_mailing_contact_partner/models/__init__.py
  mass_mailing_contact_partner/models/mailing_contact.py
  mass_mailing_contact_partner/models/res_partner.py
  mass_mailing_contact_partner/readme/CONTRIBUTORS.rst
  mass_mailing_contact_partner/readme/DESCRIPTION.rst
  mass_mailing_contact_partner/tests/__init__.py
  mass_mailing_contact_partner/tests/test_mass_mailing_contact_partner.py
  mass_mailing_contact_partner/views/mailing_contact.xml
  setup/mass_mailing_contact_partner/odoo/addons/mass_mailing_contact_partner
  setup/mass_mailing_contact_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#771 [12.0][IMP]mail_activity_board: Add action buttons in kanban view
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, ready to merge, bot is merging ⏳
