Repository OCA/social, pull requests merged in 2021-07, with the labels that each got.

#711 [12.0] mail_show_follower
  mail_show_follower/__init__.py
  mail_show_follower/__manifest__.py
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/models/res_users.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/readme/DESCRIPTION.rst
  mail_show_follower/readme/USAGE.rst
  mail_show_follower/views/res_config_settings.xml
  mail_show_follower/views/res_users.xml
  setup/mail_show_follower/odoo/addons/mail_show_follower
  setup/mail_show_follower/setup.py
Labels: approved, bot is merging ⏳, needs review

#741 [FIX] mail_tracking: reduce spammy score
  mail_tracking/models/ir_mail_server.py
Labels: approved, bot is merging ⏳, bug

#744 [13.0][FIX] mail_preview_base: Add fieldModelName to FieldPreviewViewer according to 14.0
  mail_preview_base/static/src/js/preview.js
Labels: approved, bot is merging ⏳

#719 [14.0] [NEW] Added new module to restrict chatter buttons.
  mail_restrict_send_button/README.rst
  mail_restrict_send_button/__init__.py
  mail_restrict_send_button/__manifest__.py
  mail_restrict_send_button/models/__init__.py
  mail_restrict_send_button/models/mail_followers.py
  mail_restrict_send_button/readme/CONFIGURE.rst
  mail_restrict_send_button/readme/CONTRIBUTORS.rst
  mail_restrict_send_button/readme/DESCRIPTION.rst
  mail_restrict_send_button/security/res_groups.xml
  mail_restrict_send_button/static/src/js/chatter.js
  mail_restrict_send_button/static/src/xml/chatter.xml
  mail_restrict_send_button/views/assets.xml
  setup/mail_restrict_send_button/odoo/addons/mail_restrict_send_button
  setup/mail_restrict_send_button/setup.py
Labels: bot is merging ⏳

#746 [14.0][MIG] mail_attach_existing_attachment: Migration to 14.0
  mail_attach_existing_attachment/README.rst
  mail_attach_existing_attachment/__init__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_attach_existing_attachment/i18n/ca.po
  mail_attach_existing_attachment/i18n/de.po
  mail_attach_existing_attachment/i18n/es.po
  mail_attach_existing_attachment/i18n/es_CO.po
  mail_attach_existing_attachment/i18n/fr.po
  mail_attach_existing_attachment/i18n/he.po
  mail_attach_existing_attachment/i18n/hr.po
  mail_attach_existing_attachment/i18n/it.po
  mail_attach_existing_attachment/i18n/mail_attach_existing_attachment.pot
  mail_attach_existing_attachment/i18n/pt_BR.po
  mail_attach_existing_attachment/i18n/sl.po
  mail_attach_existing_attachment/i18n/zh_CN.po
  mail_attach_existing_attachment/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment/readme/DESCRIPTION.rst
  mail_attach_existing_attachment/readme/ROADMAP.rst
  mail_attach_existing_attachment/readme/USAGE.rst
  mail_attach_existing_attachment/static/description/attachment.png
  mail_attach_existing_attachment/static/description/ex_mail_compose_message.png
  mail_attach_existing_attachment/static/description/icon.png
  mail_attach_existing_attachment/static/description/index.html
  mail_attach_existing_attachment/tests/__init__.py
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment/wizard/__init__.py
  mail_attach_existing_attachment/wizard/mail_compose_message.py
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
  setup/mail_attach_existing_attachment/odoo/addons/mail_attach_existing_attachment
  setup/mail_attach_existing_attachment/setup.py
Labels: approved, bot is merging ⏳

#749 [14.0] mail_debrand: pass original args to super()
  mail_debrand/models/__init__.py
  mail_debrand/models/mail_mail.py
  mail_debrand/models/mail_render_mixin.py
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand_digest.py
Labels: approved, bot is merging ⏳, ready to merge

#748 [14.0] [MIG] mail_tracking_mass_mailing: MIgration to v14.0
  mail_tracking_mass_mailing/README.rst
  mail_tracking_mass_mailing/__init__.py
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/hooks.py
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/da.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/el_GR.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/es_CO.po
  mail_tracking_mass_mailing/i18n/eu.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/gl.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/hr_HR.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/i18n/nb_NO.po
  mail_tracking_mass_mailing/i18n/nl.po
  mail_tracking_mass_mailing/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/pl.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/pt_BR.po
  mail_tracking_mass_mailing/i18n/ro.po
  mail_tracking_mass_mailing/i18n/ru.po
  mail_tracking_mass_mailing/i18n/sl.po
  mail_tracking_mass_mailing/i18n/tr.po
  mail_tracking_mass_mailing/models/__init__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mail_tracking_email.py
  mail_tracking_mass_mailing/models/mail_tracking_event.py
  mail_tracking_mass_mailing/models/mailing_contact.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/readme/CONTRIBUTORS.rst
  mail_tracking_mass_mailing/readme/DESCRIPTION.rst
  mail_tracking_mass_mailing/readme/INSTALL.rst
  mail_tracking_mass_mailing/readme/USAGE.rst
  mail_tracking_mass_mailing/static/description/icon.png
  mail_tracking_mass_mailing/static/description/index.html
  mail_tracking_mass_mailing/tests/__init__.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mail_tracking_mass_mailing/views/mail_mass_mailing_view.xml
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mail_tracking_mass_mailing/views/mail_tracking_email_view.xml
  mail_tracking_mass_mailing/views/mailing_contact_view.xml
  setup/mail_tracking_mass_mailing/odoo/addons/mail_tracking_mass_mailing
  setup/mail_tracking_mass_mailing/setup.py
Labels: approved, bot is merging ⏳, ready to merge
