Repository OCA/social, pull requests merged in 2021-11, with the labels that each got.

#793 [14.0][MIG] mail_full_expand: Migration to 14.0
  mail_full_expand/README.rst
  mail_full_expand/__init__.py
  mail_full_expand/__manifest__.py
  mail_full_expand/i18n/ca.po
  mail_full_expand/i18n/de.po
  mail_full_expand/i18n/es.po
  mail_full_expand/i18n/es_CO.po
  mail_full_expand/i18n/fr.po
  mail_full_expand/i18n/hr.po
  mail_full_expand/i18n/it.po
  mail_full_expand/i18n/mail_full_expand.pot
  mail_full_expand/i18n/nb.po
  mail_full_expand/i18n/nl.po
  mail_full_expand/i18n/nl_NL.po
  mail_full_expand/i18n/pt.po
  mail_full_expand/i18n/pt_BR.po
  mail_full_expand/i18n/sl.po
  mail_full_expand/i18n/tr.po
  mail_full_expand/i18n/tr_TR.po
  mail_full_expand/readme/CONTRIBUTORS.rst
  mail_full_expand/readme/DESCRIPTION.rst
  mail_full_expand/readme/USAGE.rst
  mail_full_expand/static/description/icon.png
  mail_full_expand/static/description/index.html
  mail_full_expand/static/src/components/message/mail_full_expand.js
  mail_full_expand/static/src/components/message/mail_full_expand.scss
  mail_full_expand/static/src/components/message/mail_full_expand.xml
  mail_full_expand/views/assets.xml
  mail_full_expand/views/mail_full_expand.xml
  setup/mail_full_expand/odoo/addons/mail_full_expand
  setup/mail_full_expand/setup.py
Labels: approved, bot is merging ⏳

#797 [13.0][MIG] mail_attach_existing_attachment_account: Migration to 13.0
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment_account/README.rst
  mail_attach_existing_attachment_account/__init__.py
  mail_attach_existing_attachment_account/__manifest__.py
  mail_attach_existing_attachment_account/i18n/mail_attach_existing_attachment_account.pot
  mail_attach_existing_attachment_account/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment_account/readme/DESCRIPTION.rst
  mail_attach_existing_attachment_account/static/description/icon.png
  mail_attach_existing_attachment_account/static/description/index.html
  mail_attach_existing_attachment_account/tests/__init__.py
  mail_attach_existing_attachment_account/tests/test_mail_attach_existing_attachment_account.py
  mail_attach_existing_attachment_account/wizard/__init__.py
  mail_attach_existing_attachment_account/wizard/account_invoice_send.py
  mail_attach_existing_attachment_account/wizard/account_invoice_send_view.xml
  setup/mail_attach_existing_attachment_account/odoo/addons/mail_attach_existing_attachment_account
  setup/mail_attach_existing_attachment_account/setup.py
Labels: approved, bot is merging ⏳

#796 [14.0][MIG] mail_attach_existing_attachment_account: Migration to 14.0
  mail_attach_existing_attachment_account/README.rst
  mail_attach_existing_attachment_account/__init__.py
  mail_attach_existing_attachment_account/__manifest__.py
  mail_attach_existing_attachment_account/i18n/mail_attach_existing_attachment_account.pot
  mail_attach_existing_attachment_account/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment_account/readme/DESCRIPTION.rst
  mail_attach_existing_attachment_account/static/description/icon.png
  mail_attach_existing_attachment_account/static/description/index.html
  mail_attach_existing_attachment_account/tests/__init__.py
  mail_attach_existing_attachment_account/tests/test_mail_attach_existing_attachment_account.py
  mail_attach_existing_attachment_account/wizard/__init__.py
  mail_attach_existing_attachment_account/wizard/account_invoice_send.py
  mail_attach_existing_attachment_account/wizard/account_invoice_send_view.xml
  setup/mail_attach_existing_attachment_account/odoo/addons/mail_attach_existing_attachment_account
  setup/mail_attach_existing_attachment_account/setup.py
Labels: approved, bot is merging ⏳

#792 [PORT] porting js code to comply with OWL
  mail_tracking/__manifest__.py
  mail_tracking/models/mail_message.py
  mail_tracking/readme/CONTRIBUTORS.rst
  mail_tracking/static/src/js/chatter.js
  mail_tracking/static/src/js/discuss/discuss.js
  mail_tracking/static/src/js/failed_message/mail_failed_box.js
  mail_tracking/static/src/js/failed_message/thread.js
  mail_tracking/static/src/js/mail_tracking.js
  mail_tracking/static/src/js/message.js
  mail_tracking/static/src/js/models/thread.js
  mail_tracking/static/src/xml/failed_message/discuss.xml
  mail_tracking/static/src/xml/failed_message/thread.xml
  mail_tracking/static/src/xml/mail_tracking.xml
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/assets.xml
Labels: approved, bot is merging ⏳

#773 [14.0][MIG] mass_mailing_unique
  mass_mailing_unique/README.rst
  mass_mailing_unique/__init__.py
  mass_mailing_unique/__manifest__.py
  mass_mailing_unique/hooks.py
  mass_mailing_unique/i18n/ca.po
  mass_mailing_unique/i18n/de.po
  mass_mailing_unique/i18n/es.po
  mass_mailing_unique/i18n/fr.po
  mass_mailing_unique/i18n/hr.po
  mass_mailing_unique/i18n/it.po
  mass_mailing_unique/i18n/mass_mailing_unique.pot
  mass_mailing_unique/i18n/pt.po
  mass_mailing_unique/i18n/sl.po
  mass_mailing_unique/models/__init__.py
  mass_mailing_unique/models/mailing_contact.py
  mass_mailing_unique/models/mailing_list.py
  mass_mailing_unique/readme/CONTRIBUTORS.rst
  mass_mailing_unique/readme/DESCRIPTION.rst
  mass_mailing_unique/readme/INSTALL.rst
  mass_mailing_unique/static/description/icon.png
  mass_mailing_unique/static/description/index.html
  mass_mailing_unique/tests/__init__.py
  mass_mailing_unique/tests/test_mass_mailing_unique.py
  setup/mass_mailing_unique/odoo/addons/mass_mailing_unique
  setup/mass_mailing_unique/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#794 [11.0][IMP] mail_activity_team: better error message
  mail_activity_team/models/mail_activity.py
Labels: approved, ready to merge

#765 [14.0][ADD] mass_mailing_subscription_email
  mass_mailing_subscription_email/__init__.py
  mass_mailing_subscription_email/__manifest__.py
  mass_mailing_subscription_email/data/mail_template.xml
  mass_mailing_subscription_email/hooks.py
  mass_mailing_subscription_email/models/__init__.py
  mass_mailing_subscription_email/models/mailing_contact_subscription.py
  mass_mailing_subscription_email/models/mailing_list.py
  mass_mailing_subscription_email/readme/CONFIGURE.rst
  mass_mailing_subscription_email/readme/CONTRIBUTORS.rst
  mass_mailing_subscription_email/readme/DESCRIPTION.rst
  mass_mailing_subscription_email/tests/__init__.py
  mass_mailing_subscription_email/tests/test_subscription_email.py
  mass_mailing_subscription_email/views/mailing_list.xml
  setup/mass_mailing_subscription_email/odoo/addons/mass_mailing_subscription_email
  setup/mass_mailing_subscription_email/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#799 [MIG][13.0] mail activity creator
  mail_activity_creator/README.rst
  mail_activity_creator/__init__.py
  mail_activity_creator/__manifest__.py
  mail_activity_creator/i18n/mail_activity_creator.pot
  mail_activity_creator/models/__init__.py
  mail_activity_creator/models/mail_activity.py
  mail_activity_creator/readme/CONTRIBUTORS.rst
  mail_activity_creator/readme/DESCRIPTION.rst
  mail_activity_creator/static/description/icon.png
  mail_activity_creator/static/description/index.html
  mail_activity_creator/static/src/xml/activity.xml
  mail_activity_creator/tests/__init__.py
  mail_activity_creator/tests/test_creator.py
  mail_activity_creator/views/mail_activity_views.xml
  setup/mail_activity_creator/odoo/addons/mail_activity_creator
  setup/mail_activity_creator/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#804 [IMP] mail_tracking{,_mailgun}: process sent events and fix wrong failure event mappings... and refactor
  mail_tracking/controllers/main.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/mail_tracking_event.py
  mail_tracking_mailgun/README.rst
  mail_tracking_mailgun/__init__.py
  mail_tracking_mailgun/__manifest__.py
  mail_tracking_mailgun/controllers/__init__.py
  mail_tracking_mailgun/controllers/main.py
  mail_tracking_mailgun/migrations/13.0.2.0.0/post-migration.py
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/models/mail_tracking_event.py
  mail_tracking_mailgun/models/res_partner.py
  mail_tracking_mailgun/readme/CONFIGURE.rst
  mail_tracking_mailgun/readme/CONTRIBUTORS.rst
  mail_tracking_mailgun/readme/INSTALL.rst
  mail_tracking_mailgun/readme/ROADMAP.rst
  mail_tracking_mailgun/static/description/index.html
  mail_tracking_mailgun/tests/test_mailgun.py
  mail_tracking_mailgun/wizards/__init__.py
  mail_tracking_mailgun/wizards/res_config_settings.py
  mail_tracking_mailgun/wizards/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#795 [14.0][MIG] mail_activity_partner
  mail_activity_partner/README.rst
  mail_activity_partner/__init__.py
  mail_activity_partner/__manifest__.py
  mail_activity_partner/i18n/mail_activity_partner.pot
  mail_activity_partner/models/__init__.py
  mail_activity_partner/models/mail_activity.py
  mail_activity_partner/readme/CONTRIBUTORS.rst
  mail_activity_partner/readme/DESCRIPTION.rst
  mail_activity_partner/readme/USAGE.rst
  mail_activity_partner/static/description/icon.png
  mail_activity_partner/static/description/index.html
  mail_activity_partner/tests/__init__.py
  mail_activity_partner/tests/test_mail_activity_partner.py
  mail_activity_partner/views/mail_activity_views.xml
  setup/mail_activity_partner/odoo/addons/mail_activity_partner
  setup/mail_activity_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#802 [MIG][15.0]mail_activity_board
  mail_activity_board/README.rst
  mail_activity_board/__init__.py
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/es.po
  mail_activity_board/i18n/fr_BE.po
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/__init__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/models/mail_activity_mixin.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/readme/DESCRIPTION.rst
  mail_activity_board/readme/USAGE.rst
  mail_activity_board/static/description/icon.png
  mail_activity_board/static/description/index.html
  mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.esm.js
  mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.xml
  mail_activity_board/tests/__init__.py
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
  setup/mail_activity_board/odoo/addons/mail_activity_board
  setup/mail_activity_board/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#808 [MIG][14.0] mail activity creator
  mail_activity_creator/README.rst
  mail_activity_creator/__init__.py
  mail_activity_creator/__manifest__.py
  mail_activity_creator/i18n/mail_activity_creator.pot
  mail_activity_creator/models/__init__.py
  mail_activity_creator/models/mail_activity.py
  mail_activity_creator/readme/CONTRIBUTORS.rst
  mail_activity_creator/readme/DESCRIPTION.rst
  mail_activity_creator/static/description/icon.png
  mail_activity_creator/static/description/index.html
  mail_activity_creator/static/src/xml/activity.xml
  mail_activity_creator/tests/__init__.py
  mail_activity_creator/tests/test_creator.py
  mail_activity_creator/views/mail_activity_views.xml
  setup/mail_activity_creator/odoo/addons/mail_activity_creator
  setup/mail_activity_creator/setup.py
Labels: approved, bot is merging ⏳
