Repository OCA/social, pull requests merged in 2021-03, with the labels that each got.

#683 [13.0][FIX] mail_tracking: Store cc
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳, ready to merge

#676 [13.0][FIX] mail_optional_follower_notification: change reference mode
  mail_optional_follower_notification/wizard/mail_compose_message_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#689 [12.0][FIX] mass_mailing_list_dynamic: Prevent ValidationError when merge contacts
  mass_mailing_list_dynamic/models/mail_mass_mailing_contact.py
  mass_mailing_list_dynamic/readme/CONTRIBUTORS.rst
  mass_mailing_list_dynamic/tests/test_dynamic_lists.py
  mass_mailing_list_dynamic/wizards/__init__.py
  mass_mailing_list_dynamic/wizards/partner_merge.py
Labels: approved, bot is merging ⏳

#690 [13.0][FIX] mass_mailing_list_dynamic: Prevent ValidationError when merge contacts
  mass_mailing_list_dynamic/readme/CONTRIBUTORS.rst
  mass_mailing_list_dynamic/tests/test_dynamic_lists.py
  mass_mailing_list_dynamic/wizards/__init__.py
  mass_mailing_list_dynamic/wizards/partner_merge.py
Labels: bot is merging ⏳

#693 [IMP] mass_mailing_custom_unsubscribe: chatter permissions
  mass_mailing_custom_unsubscribe/models/mail_unsubscription.py
Labels: approved, bot is merging ⏳

#671 [13.0] [MIG] mail_notification_custom_subject: Migration to v13.0
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es_ES.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.rst
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
  mail_notification_custom_subject/readme/DESCRIPTION.rst
  mail_notification_custom_subject/readme/USAGE.rst
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/icon.png
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
  setup/mail_notification_custom_subject/odoo/addons/mail_notification_custom_subject
  setup/mail_notification_custom_subject/setup.py
Labels: bot is merging ⏳

#692 [14.0][MIG] mail_preview_base: Migration to 14.0
  mail_preview_base/README.rst
  mail_preview_base/__init__.py
  mail_preview_base/__manifest__.py
  mail_preview_base/i18n/mail_preview_base.pot
  mail_preview_base/readme/CONTRIBUTORS.rst
  mail_preview_base/readme/DESCRIPTION.rst
  mail_preview_base/readme/USAGE.rst
  mail_preview_base/static/description/icon.png
  mail_preview_base/static/description/index.html
  mail_preview_base/static/src/js/preview.js
  mail_preview_base/static/src/scss/preview.scss
  mail_preview_base/static/src/xml/preview.xml
  mail_preview_base/template/assets.xml
  mail_preview_base/views/ir_attachment_view.xml
  setup/mail_preview_base/odoo/addons/mail_preview_base
  setup/mail_preview_base/setup.py
Labels: approved, bot is merging ⏳, ready to merge
