Repository OCA/social, pull requests merged in 2021-02, with the labels that each got.

#665 [13.0][IMP] mail_tracking: Discuss failed messages: Button and domain
  mail_tracking/demo/demo.xml
  mail_tracking/models/mail_message.py
  mail_tracking/static/src/js/failed_message/discuss.js
  mail_tracking/static/src/xml/failed_message/discuss.xml
  mail_tracking/tests/test_mail_tracking.py
Labels: bot is merging ⏳

#666 [12.0][FIX] mail_tracking: Resend action
  mail_tracking/models/mail_resend_message.py
Labels: bot is merging ⏳

#619 _check_email_list_ids -> raise more informative error message
  mass_mailing_unique/models/mail_mass_mailing_contact.py
Labels: approved, bot is merging ⏳

#667 [12.0][FIX] mass_mailing_partner: Mailing contact multi wite
  mass_mailing_partner/models/mail_mass_mailing_contact.py
  mass_mailing_partner/tests/test_res_partner.py
Labels: approved, bot is merging ⏳

#668 [13.0][IMP] mass_mailing_partner: Add test related to write with multi-partner
  mass_mailing_partner/tests/test_res_partner.py
Labels: bot is merging ⏳

#655 [MIG] mail_debrand
  mail_debrand/README.rst
  mail_debrand/__init__.py
  mail_debrand/__manifest__.py
  mail_debrand/i18n/fr.po
  mail_debrand/i18n/mail_debrand.pot
  mail_debrand/i18n/nl.po
  mail_debrand/i18n/pt.po
  mail_debrand/i18n/sl.po
  mail_debrand/i18n/sr_Latn.po
  mail_debrand/models/__init__.py
  mail_debrand/models/mail_render_mixinANDmail_mail.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/readme/DESCRIPTION.rst
  mail_debrand/readme/HISTORY.rst
  mail_debrand/readme/USAGE.rst
  mail_debrand/static/description/icon.png
  mail_debrand/static/description/icon.svg
  mail_debrand/static/description/index.html
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand.py
  setup/mail_debrand/odoo/addons/mail_debrand
  setup/mail_debrand/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#617 [13.0][UPD] Eficent -> ForgeFlow
  base_search_mail_content/__init__.py
  base_search_mail_content/__manifest__.py
  base_search_mail_content/models/__init__.py
  base_search_mail_content/models/mail_thread.py
  base_search_mail_content/models/trgm_index.py
  base_search_mail_content/readme/CONTRIBUTORS.rst
  base_search_mail_content/tests/test_base_search_mail_content.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/tests/test_mail_activity_team.py
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_thread.py
  mail_debrand/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#679 [MIG] email_template_qweb: Migration to 14.0
  email_template_qweb/README.rst
  email_template_qweb/__init__.py
  email_template_qweb/__manifest__.py
  email_template_qweb/demo/ir_ui_view.xml
  email_template_qweb/demo/mail_template.xml
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/email_template_qweb.pot
  email_template_qweb/i18n/en.po
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/nl_NL.po
  email_template_qweb/i18n/pt_BR.po
  email_template_qweb/i18n/zh_CN.po
  email_template_qweb/models/__init__.py
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
  email_template_qweb/readme/CREDITS.rst
  email_template_qweb/readme/DESCRIPTION.rst
  email_template_qweb/readme/USAGE.rst
  email_template_qweb/static/description/icon.png
  email_template_qweb/static/description/index.html
  email_template_qweb/tests/__init__.py
  email_template_qweb/tests/test_mail_template_qweb.py
  email_template_qweb/views/mail_template.xml
  setup/email_template_qweb/odoo/addons/email_template_qweb
  setup/email_template_qweb/setup.py
Labels: approved, bot is merging ⏳, ready to merge
