Repository OCA/social, pull requests merged in 2021-08, with the labels that each got.

#680 [MIG] mail_inline_css: Migration to 14.0
  mail_inline_css/README.rst
  mail_inline_css/__init__.py
  mail_inline_css/__manifest__.py
  mail_inline_css/demo/demo_mail_template.xml
  mail_inline_css/demo/demo_template.xml
  mail_inline_css/i18n/de.po
  mail_inline_css/i18n/es.po
  mail_inline_css/i18n/es_MX.po
  mail_inline_css/i18n/fr.po
  mail_inline_css/i18n/hr.po
  mail_inline_css/i18n/it.po
  mail_inline_css/i18n/mail_inline_css.pot
  mail_inline_css/i18n/nl_NL.po
  mail_inline_css/i18n/zh_CN.po
  mail_inline_css/models/__init__.py
  mail_inline_css/models/mail_template.py
  mail_inline_css/readme/CONTRIBUTORS.rst
  mail_inline_css/readme/CREDITS.rst
  mail_inline_css/readme/DESCRIPTION.rst
  mail_inline_css/static/description/icon.png
  mail_inline_css/static/description/index.html
  mail_inline_css/tests/__init__.py
  mail_inline_css/tests/test_mail_inline_styles.py
  requirements.txt
  setup/mail_inline_css/odoo/addons/mail_inline_css
  setup/mail_inline_css/setup.py
Labels: bot is merging ⏳

#754 [14.0][ADD] mail_autosubscribe
  mail_autosubscribe/__init__.py
  mail_autosubscribe/__manifest__.py
  mail_autosubscribe/models/__init__.py
  mail_autosubscribe/models/mail_autosubscribe.py
  mail_autosubscribe/models/mail_template.py
  mail_autosubscribe/models/mail_thread.py
  mail_autosubscribe/models/models.py
  mail_autosubscribe/models/res_partner.py
  mail_autosubscribe/readme/CONFIGURE.rst
  mail_autosubscribe/readme/CONTRIBUTORS.rst
  mail_autosubscribe/readme/DESCRIPTION.rst
  mail_autosubscribe/readme/ROADMAP.rst
  mail_autosubscribe/security/ir.model.access.csv
  mail_autosubscribe/tests/__init__.py
  mail_autosubscribe/tests/models/__init__.py
  mail_autosubscribe/tests/models/fake_order.py
  mail_autosubscribe/tests/test_mail_autosubscribe.py
  mail_autosubscribe/views/mail_autosubscribe.xml
  mail_autosubscribe/views/mail_template.xml
  mail_autosubscribe/views/res_partner.xml
  setup/mail_autosubscribe/odoo/addons/mail_autosubscribe
  setup/mail_autosubscribe/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#760 [FIX] mail_tracking: Added restriction on email search.
  mail_tracking/views/mail_tracking_email_view.xml
Labels: approved, bot is merging ⏳

#764 [REF] mail_debrand: Fix FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  mail_debrand/models/mail_render_mixin.py
Labels: approved, bot is merging ⏳

#757 [MIG] mail_notification_custom_subject: Migration to 14.0
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es_ES.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.rst
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
  mail_notification_custom_subject/readme/DESCRIPTION.rst
  mail_notification_custom_subject/readme/USAGE.rst
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/icon.png
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
  setup/mail_notification_custom_subject/odoo/addons/mail_notification_custom_subject
  setup/mail_notification_custom_subject/setup.py
Labels: approved, ready to merge, bot is merging ⏳
