Repository OCA/social, pull requests merged in 2021-04, with the labels that each got.

#696 [FIX] mail_activity_team: scheduled activity
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/tests/test_mail_activity_team.py
Labels: approved, bot is merging ⏳

#698 [13.0][FIX] mass_mailing_partner: Add sudo() to prevent user without mailing access try to merge contacts
  mass_mailing_partner/wizard/partner_merge.py
Labels: approved, bot is merging ⏳

#687 [14.0][FIX] mail_debrand: tolerate binary inputs, solve etree FutureWarning
  mail_debrand/models/mail_render_mixinANDmail_mail.py
  mail_debrand/tests/test_mail_debrand.py
Labels: bot is merging ⏳

#458 WIP [ADD] mail_embed_image module
  mail_embed_image/README.rst
  mail_embed_image/__init__.py
  mail_embed_image/__manifest__.py
  mail_embed_image/models/__init__.py
  mail_embed_image/models/ir_mail_server.py
  mail_embed_image/readme/CONTRIBUTORS.rst
  mail_embed_image/readme/DESCRIPTION.rst
  mail_embed_image/static/description/icon.png
  mail_embed_image/static/description/index.html
  mail_embed_image/tests/__init__.py
  mail_embed_image/tests/test_mail_embed_image.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#677 [12.0][MIG] Module mail_improved_tracking_value
  mail_improved_tracking_value/README.rst
  mail_improved_tracking_value/__init__.py
  mail_improved_tracking_value/__manifest__.py
  mail_improved_tracking_value/i18n/mail_improved_tracking_value.pot
  mail_improved_tracking_value/models/__init__.py
  mail_improved_tracking_value/models/mail_tracking_value.py
  mail_improved_tracking_value/static/description/icon.png
  mail_improved_tracking_value/tests/__init__.py
  mail_improved_tracking_value/tests/test_improved_tracking_value.py
  mail_improved_tracking_value/views/mail_tracking_value.xml
Labels: approved, bot is merging ⏳

#703 [13.0][add][mail_partner_opt_out]
  mail_partner_opt_out/__init__.py
  mail_partner_opt_out/__manifest__.py
  mail_partner_opt_out/models/__init__.py
  mail_partner_opt_out/models/res_partner.py
  mail_partner_opt_out/readme/CONTRIBUTORS.rst
  mail_partner_opt_out/readme/DESCRIPTION.rst
  mail_partner_opt_out/readme/USAGE.rst
  mail_partner_opt_out/views/res_partner_views.xml
  setup/mail_partner_opt_out/odoo/addons/mail_partner_opt_out
  setup/mail_partner_opt_out/setup.py
Labels: approved, bot is merging ⏳, ready to merge
