Repository OCA/social, pull requests merged in 2022-01, with the labels that each got.

#662 [MIG] mail_activity_team: Migration to 14.0
  mail_activity_team/README.rst
  mail_activity_team/__init__.py
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/it.po
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/readme/DESCRIPTION.rst
  mail_activity_team/readme/USAGE.rst
  mail_activity_team/security/ir.model.access.csv
  mail_activity_team/security/mail_activity_team_security.xml
  mail_activity_team/static/description/icon.png
  mail_activity_team/static/description/index.html
  mail_activity_team/static/src/js/systray.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/__init__.py
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/assets_backend.xml
  mail_activity_team/views/mail_activity_team_views.xml
  mail_activity_team/views/mail_activity_views.xml
  mail_activity_team/views/res_users_views.xml
Labels: bot is merging ⏳

#807 [FIX] mail_tracking: use recipient_address to search emails
  mail_tracking/views/mail_tracking_email_view.xml
  mail_tracking/views/res_partner_view.xml
Labels: bot is merging ⏳

#758 [14.0][MIG]mail_activity_done
  mail_activity_done/LICENSE
  mail_activity_done/README.rst
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/i18n/hu.po
  mail_activity_done/i18n/mail_activity_done.pot
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/DESCRIPTION.rst
  mail_activity_done/readme/USAGE.rst
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/description/index.html
  mail_activity_done/static/src/js/mail_activity.js
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
  mail_activity_done/views/templates.xml
  setup/mail_activity_done/odoo/addons/mail_activity_done
  setup/mail_activity_done/setup.py
Labels: approved, bot is merging ⏳

#829 [FIX] mail_tracking: change order of inheritance and use return
  mail_tracking/static/src/js/discuss/discuss.js
Labels: bot is merging ⏳

#815 [14.0][MIG]mail_partner_opt_out: Migration to 14.0
  mail_partner_opt_out/README.rst
  mail_partner_opt_out/__init__.py
  mail_partner_opt_out/__manifest__.py
  mail_partner_opt_out/i18n/mail_partner_opt_out.pot
  mail_partner_opt_out/models/__init__.py
  mail_partner_opt_out/models/mail_thread_blacklist.py
  mail_partner_opt_out/readme/CONTRIBUTORS.rst
  mail_partner_opt_out/readme/DESCRIPTION.rst
  mail_partner_opt_out/readme/USAGE.rst
  mail_partner_opt_out/static/description/icon.png
  mail_partner_opt_out/static/description/index.html
  mail_partner_opt_out/views/res_partner_views.xml
  setup/mail_partner_opt_out/odoo/addons/mail_partner_opt_out
  setup/mail_partner_opt_out/setup.py
Labels: approved, bot is merging ⏳

#816 [15.0][MIG]mail_attach_existing_attachment
  mail_attach_existing_attachment/README.rst
  mail_attach_existing_attachment/__init__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_attach_existing_attachment/i18n/ca.po
  mail_attach_existing_attachment/i18n/de.po
  mail_attach_existing_attachment/i18n/es.po
  mail_attach_existing_attachment/i18n/es_CO.po
  mail_attach_existing_attachment/i18n/fr.po
  mail_attach_existing_attachment/i18n/he.po
  mail_attach_existing_attachment/i18n/hr.po
  mail_attach_existing_attachment/i18n/it.po
  mail_attach_existing_attachment/i18n/mail_attach_existing_attachment.pot
  mail_attach_existing_attachment/i18n/pt_BR.po
  mail_attach_existing_attachment/i18n/sl.po
  mail_attach_existing_attachment/i18n/zh_CN.po
  mail_attach_existing_attachment/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment/readme/DESCRIPTION.rst
  mail_attach_existing_attachment/readme/ROADMAP.rst
  mail_attach_existing_attachment/readme/USAGE.rst
  mail_attach_existing_attachment/static/description/attachment.png
  mail_attach_existing_attachment/static/description/ex_mail_compose_message.png
  mail_attach_existing_attachment/static/description/icon.png
  mail_attach_existing_attachment/static/description/index.html
  mail_attach_existing_attachment/tests/__init__.py
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment/wizard/__init__.py
  mail_attach_existing_attachment/wizard/mail_compose_message.py
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
  setup/mail_attach_existing_attachment/odoo/addons/mail_attach_existing_attachment
  setup/mail_attach_existing_attachment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#835 [15.0][MIG] mail_activity_done
  mail_activity_done/README.rst
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/i18n/hu.po
  mail_activity_done/i18n/mail_activity_done.pot
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/DESCRIPTION.rst
  mail_activity_done/readme/USAGE.rst
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/description/index.html
  mail_activity_done/static/src/js/mail_activity.esm.js
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
  setup/mail_activity_done/odoo/addons/mail_activity_done
  setup/mail_activity_done/setup.py
Labels: approved, bot is merging ⏳
