Repository OCA/social, pull requests merged in 2022-08, with the labels that each got.

#953 [15.0] mail_tracking: Fixed Deprecated Warning
  mail_tracking/models/ir_mail_server.py
Labels: bot is merging ⏳

#946 [15.0][FIX] mail_activity_board: read access to ir.model for non admin
  mail_activity_board/models/mail_activity.py
Labels: approved, ready to merge, bot is merging ⏳

#943 [ADD] mail_chatter_thread_colour
  mail_chatter_thread_colour/README.rst
  mail_chatter_thread_colour/__init__.py
  mail_chatter_thread_colour/__manifest__.py
  mail_chatter_thread_colour/data/ir_config_parameter_data.xml
  mail_chatter_thread_colour/demo/ir_model.xml
  mail_chatter_thread_colour/models/__init__.py
  mail_chatter_thread_colour/models/assetsbundle.py
  mail_chatter_thread_colour/models/ir_model.py
  mail_chatter_thread_colour/models/ir_qweb.py
  mail_chatter_thread_colour/models/res_config_settings.py
  mail_chatter_thread_colour/readme/CONFIGURE.rst
  mail_chatter_thread_colour/readme/CONTRIBUTORS.rst
  mail_chatter_thread_colour/readme/DESCRIPTION.rst
  mail_chatter_thread_colour/static/description/icon.png
  mail_chatter_thread_colour/static/src/xml/thread.xml
  mail_chatter_thread_colour/templates/assets.xml
  mail_chatter_thread_colour/views/ir_model.xml
  mail_chatter_thread_colour/views/res_config_settings.xml
  setup/mail_chatter_thread_colour/odoo/addons/mail_chatter_thread_colour
  setup/mail_chatter_thread_colour/setup.py
Labels: approved, bot is merging ⏳

#955 Updated from template: Change Travis for GH Actions
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳
