Repository OCA/social, pull requests merged in 2022-02, with the labels that each got.

#830 [14.0][MIG] website_mass_mailing_name: Migration to 14.0
  setup/website_mass_mailing_name/odoo/addons/website_mass_mailing_name
  setup/website_mass_mailing_name/setup.py
  website_mass_mailing_name/README.rst
  website_mass_mailing_name/__init__.py
  website_mass_mailing_name/__manifest__.py
  website_mass_mailing_name/controllers/__init__.py
  website_mass_mailing_name/controllers/main.py
  website_mass_mailing_name/i18n/de.po
  website_mass_mailing_name/i18n/es.po
  website_mass_mailing_name/i18n/fr.po
  website_mass_mailing_name/i18n/hr.po
  website_mass_mailing_name/i18n/pt.po
  website_mass_mailing_name/i18n/sl.po
  website_mass_mailing_name/i18n/website_mass_mailing_name.pot
  website_mass_mailing_name/readme/CONTRIBUTORS.rst
  website_mass_mailing_name/readme/DESCRIPTION.rst
  website_mass_mailing_name/readme/USAGE.rst
  website_mass_mailing_name/static/description/icon.png
  website_mass_mailing_name/static/description/index.html
  website_mass_mailing_name/static/src/css/website_mass_mailing_name.scss
  website_mass_mailing_name/static/src/js/admin_and_public_tour.js
  website_mass_mailing_name/static/src/js/website_mass_mailing_name.js
  website_mass_mailing_name/templates/assets.xml
  website_mass_mailing_name/templates/snippets.xml
  website_mass_mailing_name/tests/__init__.py
  website_mass_mailing_name/tests/snippet_test_page.xml
  website_mass_mailing_name/tests/test_ui.py
Labels: approved, ready to merge, bot is merging ⏳

#844 [14.0][FIX] mass_mailing_subscription_email: /unsubscribe_from_list link
  mass_mailing_subscription_email/__init__.py
  mass_mailing_subscription_email/__manifest__.py
  mass_mailing_subscription_email/controllers/__init__.py
  mass_mailing_subscription_email/controllers/main.py
  mass_mailing_subscription_email/models/__init__.py
  mass_mailing_subscription_email/models/mail_mail.py
  mass_mailing_subscription_email/models/mailing_contact_subscription.py
  mass_mailing_subscription_email/tests/__init__.py
  mass_mailing_subscription_email/tests/test_subscription_email.py
  mass_mailing_subscription_email/tests/test_unsubscribe_from_list.py
Labels: bot is merging ⏳

#846 [14.0][FIX] mass_mailing_company_newsletter: missing permissions
  mass_mailing_company_newsletter/models/res_partner.py
Labels: bot is merging ⏳

#728 [13.0][ADD] mail_template_multi_attachment
  mail_template_multi_attachment/README.rst
  mail_template_multi_attachment/__init__.py
  mail_template_multi_attachment/__manifest__.py
  mail_template_multi_attachment/models/__init__.py
  mail_template_multi_attachment/models/mail_template.py
  mail_template_multi_attachment/models/mail_template_report.py
  mail_template_multi_attachment/readme/CONFIGURE.rst
  mail_template_multi_attachment/readme/CONTRIBUTORS.rst
  mail_template_multi_attachment/readme/DESCRIPTION.rst
  mail_template_multi_attachment/readme/USAGE.rst
  mail_template_multi_attachment/security/mail_template_report.xml
  mail_template_multi_attachment/static/description/index.html
  mail_template_multi_attachment/tests/__init__.py
  mail_template_multi_attachment/tests/test_mail_template.py
  mail_template_multi_attachment/views/mail_template.xml
  mail_template_multi_attachment/views/mail_template_report.xml
  setup/mail_template_multi_attachment/odoo/addons/mail_template_multi_attachment
  setup/mail_template_multi_attachment/setup.py
Labels: approved, bot is merging ⏳, stale

#849 [14.0][FIX] mass_mailing_subscription_email: fix unsubscribe
  mass_mailing_subscription_email/controllers/main.py
Labels: approved, bot is merging ⏳

#850 [14.0][IMP] mail_tracking_mailgun: refactor to support modern webhooks (forward port)
  mail_tracking_mailgun/README.rst
  mail_tracking_mailgun/__init__.py
  mail_tracking_mailgun/__manifest__.py
  mail_tracking_mailgun/controllers/__init__.py
  mail_tracking_mailgun/controllers/main.py
  mail_tracking_mailgun/migrations/14.0.2.0.0/post-migration.py
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/models/mail_tracking_event.py
  mail_tracking_mailgun/models/res_partner.py
  mail_tracking_mailgun/readme/CONFIGURE.rst
  mail_tracking_mailgun/readme/CONTRIBUTORS.rst
  mail_tracking_mailgun/readme/INSTALL.rst
  mail_tracking_mailgun/readme/ROADMAP.rst
  mail_tracking_mailgun/static/description/index.html
  mail_tracking_mailgun/tests/test_mailgun.py
  mail_tracking_mailgun/wizards/__init__.py
  mail_tracking_mailgun/wizards/res_config_settings.py
  mail_tracking_mailgun/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#788 [12.0] FIX mail_show_follower: ValueError: Expected singleton: res.users
  mail_show_follower/models/mail_mail.py
Labels: needs review, approved, ready to merge
