Repository OCA/social, pull requests merged in 2022-07, with the labels that each got.

#887 [15.0][IMP] mail_activity_board: Direct access to related model instance (forward port)
  mail_activity_board/__manifest__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#934 15.0 mail autosubscrite dependencies
  mail_autosubscribe/__manifest__.py
  mail_autosubscribe/readme/CONTRIBUTORS.rst
  mail_autosubscribe/tests/test_mail_autosubscribe.py
  requirements.txt
Labels: bot is merging ⏳

#916 [14.0] [ADD] mail_layout_force
  mail_layout_force/__init__.py
  mail_layout_force/__manifest__.py
  mail_layout_force/data/mail_layout.xml
  mail_layout_force/demo/mail_layout.xml
  mail_layout_force/models/__init__.py
  mail_layout_force/models/mail_template.py
  mail_layout_force/models/mail_thread.py
  mail_layout_force/readme/CONFIGURE.rst
  mail_layout_force/readme/CONTRIBUTORS.rst
  mail_layout_force/readme/DESCRIPTION.rst
  mail_layout_force/tests/__init__.py
  mail_layout_force/tests/test_mail_layout_force.py
  mail_layout_force/views/mail_template.xml
  mail_layout_force/wizards/__init__.py
  mail_layout_force/wizards/mail_compose_message.py
  setup/mail_layout_force/odoo/addons/mail_layout_force
  setup/mail_layout_force/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#918 [FIX][15.0] mail_debrand: test_mail_digest update for 15.0
  mail_debrand/tests/test_mail_debrand_digest.py
Labels: approved, ready to merge, bot is merging ⏳

#931 [FIX] mail_autosubscribe: check partners type
  mail_autosubscribe/models/mail_thread.py
Labels: approved, bot is merging ⏳

#926 [12.0] [FIX] mail_tracking: reduce spammy score
  mail_tracking/models/ir_mail_server.py
Labels: approved, bot is merging ⏳

#900 [13.0][FIX] mail_activity_team. Smart button archive
  mail_activity_team/views/mail_activity_team_views.xml
Labels: approved, bot is merging ⏳

#942 [14.0][IMP] mail_tracking: remove legacy hooks
  mail_tracking/__init__.py
  mail_tracking/__manifest__.py
  mail_tracking/hooks.py
Labels: approved, bot is merging ⏳
