Repository OCA/social, pull requests merged in 2022-12, with the labels that each got.

#1010 [14.0][IMP] mail_activity_done: Change assertEquals to assertEqual
  mail_activity_done/tests/test_mail_activity_done.py
Labels: bot is merging ⏳

#1016 [FIX] mail_notification_custom_subject: do not require being admin to send messages
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
Labels: bug, approved, bot is merging ⏳

#1018 [FIX] mail_show_follower: failure when partner has more than 1 user
  mail_show_follower/__manifest__.py
  mail_show_follower/models/mail_mail.py
Labels: bug, bot is merging ⏳

#1027 [15.0] [FIX] mail_notification_custom_subject: Use same approach as Odoo when selecting subtype_id
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
Labels: bug, bot is merging ⏳

#980 [15.0][MIG] mail_quoted_reply
  mail_quoted_reply/README.rst
  mail_quoted_reply/__init__.py
  mail_quoted_reply/__manifest__.py
  mail_quoted_reply/i18n/ca.po
  mail_quoted_reply/i18n/es.po
  mail_quoted_reply/i18n/mail_quoted_reply.pot
  mail_quoted_reply/models/__init__.py
  mail_quoted_reply/models/mail_compose_message.py
  mail_quoted_reply/models/mail_message.py
  mail_quoted_reply/readme/CONTRIBUTORS.rst
  mail_quoted_reply/readme/DESCRIPTION.rst
  mail_quoted_reply/readme/USAGE.rst
  mail_quoted_reply/static/description/icon.png
  mail_quoted_reply/static/description/index.html
  mail_quoted_reply/static/src/components/mail_message_reply.esm.js
  mail_quoted_reply/static/src/models/mail_message_reply.esm.js
  mail_quoted_reply/static/src/xml/mail_message_reply.xml
  mail_quoted_reply/tests/__init__.py
  mail_quoted_reply/tests/test_reply.py
  setup/mail_quoted_reply/odoo/addons/mail_quoted_reply
  setup/mail_quoted_reply/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1028 [13.0][FIX] mail_tracking_mailgun: controller env company
  mail_tracking_mailgun/controllers/main.py
Labels: approved, bot is merging ⏳

#920 [14.0][IMP] mail_activity_team: Forwarding commits from 13.0 to 14.0
  mail_activity_team/__manifest__.py
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_activity_type.py
  mail_activity_team/models/res_users.py
  mail_activity_team/static/src/js/systray.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/mail_activity_type.xml
  mail_activity_team/views/mail_activity_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#922 [IMP] mail_activity_team: Forwarding commits from 13.0 to 15.0
  mail_activity_team/__manifest__.py
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_activity_type.py
  mail_activity_team/models/res_users.py
  mail_activity_team/static/src/js/systray.esm.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/mail_activity_type.xml
  mail_activity_team/views/mail_activity_views.xml
Labels: approved, bot is merging ⏳

#871 [13.0] add mass_mailing_contact_active and mass_mailing_partner_contact_active
  .github/workflows/test.yml
  mass_mailing_contact_active/__init__.py
  mass_mailing_contact_active/__manifest__.py
  mass_mailing_contact_active/models/__init__.py
  mass_mailing_contact_active/models/mailing_contact.py
  mass_mailing_contact_active/models/mailing_contact_subscription.py
  mass_mailing_contact_active/readme/CONTRIBUTORS.rst
  mass_mailing_contact_active/readme/DESCRIPTION.rst
  mass_mailing_contact_active/tests/__init__.py
  mass_mailing_contact_active/tests/test_mailing_contact_active.py
  mass_mailing_partner_contact_active/__init__.py
  mass_mailing_partner_contact_active/__manifest__.py
  mass_mailing_partner_contact_active/models/__init__.py
  mass_mailing_partner_contact_active/models/res_partner.py
  mass_mailing_partner_contact_active/readme/CONTRIBUTORS.rst
  mass_mailing_partner_contact_active/readme/DESCRIPTION.rst
  mass_mailing_partner_contact_active/readme/ROADMAP.rst
  mass_mailing_partner_contact_active/tests/__init__.py
  mass_mailing_partner_contact_active/tests/test_mailing_partner_contact_active.py
  setup/mass_mailing_contact_active/odoo/addons/mass_mailing_contact_active
  setup/mass_mailing_contact_active/setup.py
  setup/mass_mailing_partner_contact_active/odoo/addons/mass_mailing_partner_contact_active
  setup/mass_mailing_partner_contact_active/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#828 [14.0][ADD] mail_server_by_user
  mail_server_by_user/README.rst
  mail_server_by_user/__init__.py
  mail_server_by_user/__manifest__.py
  mail_server_by_user/models/__init__.py
  mail_server_by_user/models/ir_mail_server.py
  mail_server_by_user/models/mail_mail.py
  mail_server_by_user/models/mail_thread.py
  mail_server_by_user/readme/CONTRIBUTORS.rst
  mail_server_by_user/readme/DESCRIPTION.rst
  mail_server_by_user/static/description/index.html
  mail_server_by_user/tests/__init__.py
  mail_server_by_user/tests/test.msg
  mail_server_by_user/tests/test_mail_server_by_user.py
  setup/mail_server_by_user/odoo/addons/mail_server_by_user
  setup/mail_server_by_user/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#975 [16.0] [MIG] mail_optional_autofollow
  mail_optional_autofollow/README.rst
  mail_optional_autofollow/__init__.py
  mail_optional_autofollow/__manifest__.py
  mail_optional_autofollow/i18n/ca.po
  mail_optional_autofollow/i18n/de.po
  mail_optional_autofollow/i18n/es.po
  mail_optional_autofollow/i18n/es_CO.po
  mail_optional_autofollow/i18n/fr.po
  mail_optional_autofollow/i18n/hr.po
  mail_optional_autofollow/i18n/it.po
  mail_optional_autofollow/i18n/mail_optional_autofollow.pot
  mail_optional_autofollow/i18n/pt_BR.po
  mail_optional_autofollow/i18n/sl.po
  mail_optional_autofollow/static/description/autofollow.png
  mail_optional_autofollow/static/description/icon.png
  mail_optional_autofollow/tests/__init__.py
  mail_optional_autofollow/tests/test_mail_optional_autofollow.py
  mail_optional_autofollow/wizard/__init__.py
  mail_optional_autofollow/wizard/mail_compose_message.py
  mail_optional_autofollow/wizard/mail_compose_message_view.xml
  setup/mail_optional_autofollow/odoo/addons/mail_optional_autofollow
  setup/mail_optional_autofollow/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#859 [ADD] mail_partner_forwarding: new module
  mail_partner_forwarding/README.rst
  mail_partner_forwarding/__init__.py
  mail_partner_forwarding/__manifest__.py
  mail_partner_forwarding/models/__init__.py
  mail_partner_forwarding/models/mail_thread.py
  mail_partner_forwarding/models/res_partner.py
  mail_partner_forwarding/models/res_user.py
  mail_partner_forwarding/readme/CONTRIBUTORS.rst
  mail_partner_forwarding/readme/DESCRIPTION.rst
  mail_partner_forwarding/readme/HISTORY.rst
  mail_partner_forwarding/readme/USAGE.rst
  mail_partner_forwarding/tests/__init__.py
  mail_partner_forwarding/tests/models/__init__.py
  mail_partner_forwarding/tests/models/fake_order.py
  mail_partner_forwarding/tests/test_mail_forwarding.py
  mail_partner_forwarding/views/res_partner_views.xml
  mail_partner_forwarding/views/res_user_views.xml
  setup/mail_partner_forwarding/odoo/addons/mail_partner_forwarding
  setup/mail_partner_forwarding/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1032 [16.0][MIG] mail_partner_opt_out: Migration to 16.0
  mail_partner_opt_out/README.rst
  mail_partner_opt_out/__init__.py
  mail_partner_opt_out/__manifest__.py
  mail_partner_opt_out/i18n/mail_partner_opt_out.pot
  mail_partner_opt_out/models/__init__.py
  mail_partner_opt_out/models/mail_thread_blacklist.py
  mail_partner_opt_out/readme/CONTRIBUTORS.rst
  mail_partner_opt_out/readme/DESCRIPTION.rst
  mail_partner_opt_out/readme/USAGE.rst
  mail_partner_opt_out/static/description/icon.png
  mail_partner_opt_out/static/description/index.html
  mail_partner_opt_out/views/res_partner_views.xml
  setup/mail_partner_opt_out/odoo/addons/mail_partner_opt_out
  setup/mail_partner_opt_out/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#924 [14.0] Add module mail_notification_with_history
  mail_notification_with_history/__init__.py
  mail_notification_with_history/__manifest__.py
  mail_notification_with_history/data/mail_data.xml
  mail_notification_with_history/models/__init__.py
  mail_notification_with_history/models/mail_message.py
  mail_notification_with_history/models/mail_thread.py
  mail_notification_with_history/readme/CONTRIBUTORS.rst
  mail_notification_with_history/readme/DESCRIPTION.rst
  mail_notification_with_history/readme/INSTALL.rst
  mail_notification_with_history/tests/__init__.py
  mail_notification_with_history/tests/test_mail_notification_with_history.py
  setup/mail_notification_with_history/odoo/addons/mail_notification_with_history
  setup/mail_notification_with_history/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale
