Repository OCA/social, pull requests merged in 2022-11, with the labels that each got.

#987 [15.0] [IMP] mail_activity_team: settings menu position
  mail_activity_team/views/mail_activity_team_views.xml
Labels: approved, bot is merging ⏳

#954 [MIG] mail_chatter_thread_colour: Migration to 14.0
  mail_chatter_thread_colour/README.rst
  mail_chatter_thread_colour/__init__.py
  mail_chatter_thread_colour/__manifest__.py
  mail_chatter_thread_colour/data/ir_config_parameter_data.xml
  mail_chatter_thread_colour/demo/ir_model.xml
  mail_chatter_thread_colour/models/__init__.py
  mail_chatter_thread_colour/models/assetsbundle.py
  mail_chatter_thread_colour/models/ir_model.py
  mail_chatter_thread_colour/models/ir_qweb.py
  mail_chatter_thread_colour/models/res_config_settings.py
  mail_chatter_thread_colour/readme/CONFIGURE.rst
  mail_chatter_thread_colour/readme/CONTRIBUTORS.rst
  mail_chatter_thread_colour/readme/DESCRIPTION.rst
  mail_chatter_thread_colour/static/description/icon.png
  mail_chatter_thread_colour/static/src/xml/thread.xml
  mail_chatter_thread_colour/templates/assets.xml
  mail_chatter_thread_colour/views/ir_model.xml
  mail_chatter_thread_colour/views/res_config_settings.xml
  setup/mail_chatter_thread_colour/odoo/addons/mail_chatter_thread_colour
  setup/mail_chatter_thread_colour/setup.py
Labels: approved, bot is merging ⏳

#996 [12.0][UPD] switch to github actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  fetchmail_thread_default/__manifest__.py
  mail_activity_done/__manifest__.py
  mail_autogenerated_header/__manifest__.py
  mail_debrand/__manifest__.py
  mail_drop_target/__manifest__.py
  mail_footer_notified_partner/__manifest__.py
  mail_history/__manifest__.py
  mail_notification_custom_subject/__manifest__.py
  mail_optional_autofollow/__manifest__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_send_copy/__manifest__.py
  mail_track_diff_only/__manifest__.py
  mail_tracking/__manifest__.py
  requirements.txt
  setup/mail_drop_target/setup.py
Labels: bot is merging ⏳

#997 [15.0][ADD] email_parent_recipient
  mail_parent_recipient/README.rst
  mail_parent_recipient/__init__.py
  mail_parent_recipient/__manifest__.py
  mail_parent_recipient/models/__init__.py
  mail_parent_recipient/models/mail_template.py
  mail_parent_recipient/models/res_config.py
  mail_parent_recipient/readme/CONTRIBUTORS.rst
  mail_parent_recipient/readme/CREDITS.rst
  mail_parent_recipient/readme/DESCRIPTION.rst
  mail_parent_recipient/tests/__init__.py
  mail_parent_recipient/tests/test_mail_parent_recipient.py
  mail_parent_recipient/views/res_config_views.xml
  setup/mail_parent_recipient/odoo/addons/mail_parent_recipient
  setup/mail_parent_recipient/setup.py
Labels: approved, bot is merging ⏳

#998 [14.0][Add] microsoft outlook single-tenant support
  microsoft_outlook_single_tenant/README.rst
  microsoft_outlook_single_tenant/__init__.py
  microsoft_outlook_single_tenant/__manifest__.py
  microsoft_outlook_single_tenant/models/__init__.py
  microsoft_outlook_single_tenant/models/microsoft_outlook_mixin.py
  microsoft_outlook_single_tenant/models/res_config_settings.py
  microsoft_outlook_single_tenant/readme/CONFIGURE.rst
  microsoft_outlook_single_tenant/readme/CONTRIBUTORS.rst
  microsoft_outlook_single_tenant/readme/DESCRIPTION.rst
  microsoft_outlook_single_tenant/static/description/index.html
  microsoft_outlook_single_tenant/tests/__init__.py
  microsoft_outlook_single_tenant/tests/test_fetchmail_outlook.py
  microsoft_outlook_single_tenant/views/res_config_settings_views.xml
  setup/microsoft_outlook_single_tenant/odoo/addons/microsoft_outlook_single_tenant
  setup/microsoft_outlook_single_tenant/setup.py
Labels: approved, bot is merging ⏳

#989 [15.0][MIG] mass_mailing_resend: Migration to 15.0
  mass_mailing_resend/README.rst
  mass_mailing_resend/__init__.py
  mass_mailing_resend/__manifest__.py
  mass_mailing_resend/i18n/ca.po
  mass_mailing_resend/i18n/de.po
  mass_mailing_resend/i18n/es.po
  mass_mailing_resend/i18n/fr.po
  mass_mailing_resend/i18n/mass_mailing_resend.pot
  mass_mailing_resend/i18n/sl.po
  mass_mailing_resend/models/__init__.py
  mass_mailing_resend/models/mailing_mailing.py
  mass_mailing_resend/readme/CONTRIBUTORS.rst
  mass_mailing_resend/readme/DESCRIPTION.rst
  mass_mailing_resend/readme/ROADMAP.rst
  mass_mailing_resend/readme/USAGE.rst
  mass_mailing_resend/static/description/icon.png
  mass_mailing_resend/static/description/icon.svg
  mass_mailing_resend/static/description/index.html
  mass_mailing_resend/tests/__init__.py
  mass_mailing_resend/tests/test_mass_mailing_resend.py
  mass_mailing_resend/views/mailing_mailing_views.xml
  setup/mass_mailing_resend/odoo/addons/mass_mailing_resend
  setup/mass_mailing_resend/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#896 [13.0][FIX] mail_activity_team: activity count
  mail_activity_team/models/res_users.py
  mail_activity_team/static/src/js/systray.js
Labels: approved, ready to merge, bot is merging ⏳
