Repository OCA/social, pull requests merged in 2022-03, with the labels that each got.

#854 [12.0][mail_show_follower] Update version
  mail_show_follower/__manifest__.py
Labels: needs review, approved

#833 [15.0][MIG] mail_activity_team
  mail_activity_team/README.rst
  mail_activity_team/__init__.py
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/it.po
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/readme/DESCRIPTION.rst
  mail_activity_team/readme/ROADMAP.rst
  mail_activity_team/readme/USAGE.rst
  mail_activity_team/security/ir.model.access.csv
  mail_activity_team/security/mail_activity_team_security.xml
  mail_activity_team/static/description/icon.png
  mail_activity_team/static/description/index.html
  mail_activity_team/static/src/js/systray.esm.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/__init__.py
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/mail_activity_team_views.xml
  mail_activity_team/views/mail_activity_views.xml
  mail_activity_team/views/res_users_views.xml
  setup/mail_activity_team/odoo/addons/mail_activity_team
  setup/mail_activity_team/setup.py
Labels: approved, bot is merging ⏳

#847 [FIX] mail_tracking: error when filtering by "Sent"
  mail_tracking/views/mail_tracking_email_view.xml
Labels: bot is merging ⏳

#784 [ADD] mail_activity_form
  mail_activity_form/README.rst
  mail_activity_form/__init__.py
  mail_activity_form/__manifest__.py
  mail_activity_form/demo/mail_activity_type.xml
  mail_activity_form/models/__init__.py
  mail_activity_form/models/mail_activity.py
  mail_activity_form/models/mail_activity_type.py
  mail_activity_form/readme/CONTRIBUTORS.rst
  mail_activity_form/readme/DESCRIPTION.rst
  mail_activity_form/readme/ROADMAP.rst
  mail_activity_form/readme/USAGE.rst
  mail_activity_form/static/description/icon.png
  mail_activity_form/static/description/index.html
  mail_activity_form/tests/__init__.py
  mail_activity_form/tests/test_mail_activity_form.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#826 [MIG] mail_drop_target: Migration to 14.0
  mail_drop_target/README.rst
  mail_drop_target/__init__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/i18n/mail_drop_target.pot
  mail_drop_target/models/__init__.py
  mail_drop_target/models/mail_thread.py
  mail_drop_target/models/res_config_settings.py
  mail_drop_target/readme/CONFIGURATION.rst
  mail_drop_target/readme/CONTRIBUTORS.rst
  mail_drop_target/readme/DESCRIPTION.rst
  mail_drop_target/readme/ROADMAP.rst
  mail_drop_target/readme/USAGE.rst
  mail_drop_target/static/description/icon.png
  mail_drop_target/static/description/index.html
  mail_drop_target/static/src/css/mail_drop_target.css
  mail_drop_target/static/src/js/mail_drop_target.js
  mail_drop_target/tests/__init__.py
  mail_drop_target/tests/sample.eml
  mail_drop_target/tests/sample.msg
  mail_drop_target/tests/test_mail_drop_target.py
  mail_drop_target/views/res_config_settings_views.xml
  mail_drop_target/views/templates.xml
  requirements.txt
  setup/mail_drop_target/odoo/addons/mail_drop_target
  setup/mail_drop_target/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#822 [14.0][ADD] mail_filter_adressee_by_contact
  mail_filter_adressee_by_contact/__init__.py
  mail_filter_adressee_by_contact/__manifest__.py
  mail_filter_adressee_by_contact/models/__init__.py
  mail_filter_adressee_by_contact/models/mail_compose_message.py
  mail_filter_adressee_by_contact/readme/CONTRIBUTORS.rst
  mail_filter_adressee_by_contact/readme/DESCRIPTION.rst
  mail_filter_adressee_by_contact/views/mail_compose_message_view.xml
  mail_filter_adressee_by_contact/views/mail_invoice_send_view.xml
  setup/mail_filter_adressee_by_contact/odoo/addons/mail_filter_adressee_by_contact
  setup/mail_filter_adressee_by_contact/setup.py
Labels: needs review, approved, bot is merging ⏳

#862 [15.0][MIG] mig mail_show_follower
  mail_show_follower/README.rst
  mail_show_follower/__init__.py
  mail_show_follower/__manifest__.py
  mail_show_follower/i18n/fr.po
  mail_show_follower/i18n/mail_show_follower.pot
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/models/res_users.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/readme/DESCRIPTION.rst
  mail_show_follower/readme/USAGE.rst
  mail_show_follower/static/description/icon.png
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
  mail_show_follower/views/res_users.xml
  setup/mail_show_follower/odoo/addons/mail_show_follower
  setup/mail_show_follower/setup.py
Labels: needs review, approved, bot is merging ⏳

#837 [12.0][FIX] mail_activity_board: wrong typo for view extend
  mail_activity_board/__manifest__.py
  mail_activity_board/static/src/xml/inherit_chatter.xml
Labels: needs review, approved

#867 [14.0] [BKP] mail_show_follower: Backporting from 15.0
  mail_show_follower/README.rst
  mail_show_follower/__init__.py
  mail_show_follower/__manifest__.py
  mail_show_follower/i18n/fr.po
  mail_show_follower/i18n/mail_show_follower.pot
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/models/res_users.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/readme/DESCRIPTION.rst
  mail_show_follower/readme/USAGE.rst
  mail_show_follower/static/description/icon.png
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
  mail_show_follower/views/res_users.xml
  setup/mail_show_follower/odoo/addons/mail_show_follower
  setup/mail_show_follower/setup.py
Labels: needs review, approved, bot is merging ⏳

#866 [15.0][IMP][mail_show_follower] Customize notification appearance
  mail_show_follower/README.rst
  mail_show_follower/__manifest__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
Labels: needs review, approved, bot is merging ⏳

#869 [14.0][IMP][mail_filter_adressee_by_contact] differenciate users and partners in mail filter
  mail_filter_adressee_by_contact/__manifest__.py
  mail_filter_adressee_by_contact/models/__init__.py
  mail_filter_adressee_by_contact/models/account_invoice_send.py
  mail_filter_adressee_by_contact/models/mail_compose_message.py
  mail_filter_adressee_by_contact/views/mail_compose_message_view.xml
  mail_filter_adressee_by_contact/views/mail_invoice_send_view.xml
Labels: needs review, approved, bot is merging ⏳
