Repository OCA/social, pull requests merged in 2022-10, with the labels that each got.

#978 [14.0][FIX]Portal User Dont Have Access for Commercial Partner
  mail_allow_portal_internal_note/controllers/mail.py
Labels: approved, bot is merging ⏳

#735 [14.0][MIG] mail_optional_autofollow: Migration to 14.0
  mail_optional_autofollow/README.rst
  mail_optional_autofollow/__init__.py
  mail_optional_autofollow/__manifest__.py
  mail_optional_autofollow/i18n/ca.po
  mail_optional_autofollow/i18n/de.po
  mail_optional_autofollow/i18n/es.po
  mail_optional_autofollow/i18n/es_CO.po
  mail_optional_autofollow/i18n/fr.po
  mail_optional_autofollow/i18n/hr.po
  mail_optional_autofollow/i18n/it.po
  mail_optional_autofollow/i18n/mail_optional_autofollow.pot
  mail_optional_autofollow/i18n/pt_BR.po
  mail_optional_autofollow/i18n/sl.po
  mail_optional_autofollow/static/description/autofollow.png
  mail_optional_autofollow/static/description/icon.png
  mail_optional_autofollow/tests/__init__.py
  mail_optional_autofollow/tests/test_mail_optional_autofollow.py
  mail_optional_autofollow/wizard/__init__.py
  mail_optional_autofollow/wizard/mail_compose_message.py
  mail_optional_autofollow/wizard/mail_compose_message_view.xml
  setup/mail_optional_autofollow/odoo/addons/mail_optional_autofollow
  setup/mail_optional_autofollow/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#879 [15.0][MIG] mail_optional_autofollow: Migration to 15.0
  mail_optional_autofollow/README.rst
  mail_optional_autofollow/__init__.py
  mail_optional_autofollow/__manifest__.py
  mail_optional_autofollow/i18n/ca.po
  mail_optional_autofollow/i18n/de.po
  mail_optional_autofollow/i18n/es.po
  mail_optional_autofollow/i18n/es_CO.po
  mail_optional_autofollow/i18n/fr.po
  mail_optional_autofollow/i18n/hr.po
  mail_optional_autofollow/i18n/it.po
  mail_optional_autofollow/i18n/mail_optional_autofollow.pot
  mail_optional_autofollow/i18n/pt_BR.po
  mail_optional_autofollow/i18n/sl.po
  mail_optional_autofollow/static/description/autofollow.png
  mail_optional_autofollow/static/description/icon.png
  mail_optional_autofollow/tests/__init__.py
  mail_optional_autofollow/tests/test_mail_optional_autofollow.py
  mail_optional_autofollow/wizard/__init__.py
  mail_optional_autofollow/wizard/mail_compose_message.py
  mail_optional_autofollow/wizard/mail_compose_message_view.xml
  setup/mail_optional_autofollow/odoo/addons/mail_optional_autofollow
  setup/mail_optional_autofollow/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#972 [10.0] Use GitHub action
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  email_template_qweb/__manifest__.py
  mail_as_letter/__manifest__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_compose_select_lang/__manifest__.py
  mail_debrand/__openerp__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/tests/test_mail_drop_target.py
  mail_embed_image/__manifest__.py
  mail_follower_custom_notification/__manifest__.py
  mail_footer_notified_partner/__manifest__.py
  mail_full_expand/__manifest__.py
  mail_improved_tracking_value/__manifest__.py
  mail_optional_autofollow/__manifest__.py
  mail_optional_follower_notification/__manifest__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_sendgrid/tests/test_mail_sendgrid.py
  mail_sendgrid_mass_mailing/tests/test_mass_mailing.py
  mail_tracking/__manifest__.py
  mail_tracking_mailgun/__manifest__.py
  mass_mailing_custom_unsubscribe/__manifest__.py
  mass_mailing_partner/__manifest__.py
  mass_mailing_unique/__manifest__.py
  requirements.txt
  setup/mail_inline_css/setup.py
Labels: bot is merging ⏳

#891 [ADD][12.0] mail_autogenerated_header
  mail_autogenerated_header/README.rst
  mail_autogenerated_header/__init__.py
  mail_autogenerated_header/__manifest__.py
  mail_autogenerated_header/models/__init__.py
  mail_autogenerated_header/models/ir_mail_server.py
  mail_autogenerated_header/models/mail_thread.py
  mail_autogenerated_header/models/res_partner.py
  mail_autogenerated_header/readme/CONTRIBUTORS.rst
  mail_autogenerated_header/readme/DESCRIPTION.rst
  mail_autogenerated_header/readme/USAGE.rst
  mail_autogenerated_header/readme/newsfragments/.gitkeep
  mail_autogenerated_header/static/description/icon.png
  mail_autogenerated_header/static/description/index.html
  mail_autogenerated_header/tests/__init__.py
  mail_autogenerated_header/tests/test_mail_autogenerated_header.py
Labels: bot is merging ⏳

#983 [14.0] [FIX] `mass_mailing_subscription_email`: Avoid repetition emails if `opt_out` hasn't really changed
  mass_mailing_subscription_email/models/mailing_contact_subscription.py
  mass_mailing_subscription_email/tests/test_subscription_email.py
Labels: bot is merging ⏳

#899 [14.0][FIX] mail_activity_team. Smart button archive
  mail_activity_team/views/mail_activity_team_views.xml
Labels: approved, bot is merging ⏳, stale

#982 [15.0][MIG] mail_notification_custom_subject: Migration to 15.0
  mail_debrand/models/mail_render_mixin.py
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es_ES.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.rst
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
  mail_notification_custom_subject/readme/DESCRIPTION.rst
  mail_notification_custom_subject/readme/USAGE.rst
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/icon.png
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
  mail_outbound_static/tests/test_ir_mail_server.py
  setup/mail_notification_custom_subject/odoo/addons/mail_notification_custom_subject
  setup/mail_notification_custom_subject/setup.py
Labels: bot is merging ⏳

#937 [14.0][FIX] mail_debrand: fix #884
  mail_debrand/__manifest__.py
  mail_debrand/data/ir_config_parameter.xml
  mail_debrand/models/mail_render_mixin.py
Labels: approved, ready to merge, bot is merging ⏳
