Repository OCA/social, pull requests merged in 2022-04, with the labels that each got.

#870 [13.0] mass_mailing_partner: Fix assignation of company name
  mass_mailing_partner/models/res_partner.py
Labels: approved, bot is merging ⏳

#876 [14.0][FIX] mass_mailing_partner: Use width inheritance and prevents buttons from wrapping to fit the page
  mass_mailing_partner/views/res_partner_view.xml
Labels: bot is merging ⏳

#865 [15.0][IMP] mail_debrand: Remove Powered by Odoo
  mail_debrand/models/mail_render_mixin.py
Labels: needs review, approved, bot is merging ⏳

#883 [FIX] mail_restrict_follower_selection
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
Labels: bot is merging ⏳

#473 [13.0][IMP] mail_activity_board: Direct access to related model instance
  mail_activity_board/__manifest__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#877 [13.0][FIX] missing commits of mail_activity_team
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/res_users.py
  mail_activity_team/static/src/js/systray.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/assets_backend.xml
  mail_activity_team/views/mail_activity_views.xml
Labels: approved, bot is merging ⏳

#885 [14.0][IMP] mail_activity_board: Direct access to related model instance (forward port)
  mail_activity_board/__manifest__.py
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, bot is merging ⏳

#888 [15.0][UPD] Eficent -> ForgeFlow
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/tests/test_mail_activity_team.py
  mail_debrand/__manifest__.py
  mail_debrand/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#889 [FIX] mail_show_follower: Add recipients of the all related messages on the notification
  mail_show_follower/models/mail_mail.py
Labels: approved, bot is merging ⏳

#858 [14.0][IMP] mail_debrand: Remove Powered by Odoo
  mail_debrand/models/mail_render_mixin.py
Labels: needs review, approved, bot is merging ⏳

#886 [14.0][UPD] Eficent -> ForgeFlow
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/tests/test_mail_activity_team.py
  mail_debrand/__manifest__.py
  mail_debrand/readme/CONTRIBUTORS.rst
Labels: needs review, bot is merging ⏳

#874 14.0 mig mail_preview_audio
  mail_preview_audio/README.rst
  mail_preview_audio/__init__.py
  mail_preview_audio/__manifest__.py
  mail_preview_audio/i18n/mail_preview_audio.pot
  mail_preview_audio/readme/CONTRIBUTORS.rst
  mail_preview_audio/readme/DESCRIPTION.rst
  mail_preview_audio/static/description/icon.png
  mail_preview_audio/static/description/index.html
  mail_preview_audio/static/src/js/preview.js
  mail_preview_audio/static/src/xml/preview.xml
  mail_preview_audio/template/assets.xml
  setup/mail_preview_audio/odoo/addons/mail_preview_audio
  setup/mail_preview_audio/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#872 [FIX] email_template_qweb: get translations working
  email_template_qweb/models/mail_template.py
Labels: approved, ready to merge, bot is merging ⏳

#898 [FIX][15.0] mail_activity_team. smart button archive
  mail_activity_team/views/mail_activity_team_views.xml
Labels: approved, bot is merging ⏳

#810 [14.0][FIX] mail_allow_portal_internal_note: fix filter for messages to display
  mail_allow_portal_internal_note/__manifest__.py
  mail_allow_portal_internal_note/controllers/mail.py
  mail_allow_portal_internal_note/models/res_users.py
  mail_allow_portal_internal_note/static/src/js/composer.js
  mail_allow_portal_internal_note/static/src/xml/mail_portal_template.xml
  mail_allow_portal_internal_note/views/assets.xml
Labels: needs review, bot is merging ⏳
