Repository OCA/social, pull requests merged in 2023-10, with the labels that each got.

#1163 [16.0][MIG] mail_improved_tracking_value: Migration to 16.0
  mail_improved_tracking_value/README.rst
  mail_improved_tracking_value/__init__.py
  mail_improved_tracking_value/__manifest__.py
  mail_improved_tracking_value/i18n/mail_improved_tracking_value.pot
  mail_improved_tracking_value/models/__init__.py
  mail_improved_tracking_value/models/mail_message.py
  mail_improved_tracking_value/models/mail_tracking_value.py
  mail_improved_tracking_value/static/description/icon.png
  mail_improved_tracking_value/tests/__init__.py
  mail_improved_tracking_value/tests/test_improved_tracking_value.py
  mail_improved_tracking_value/views/mail_tracking_value.xml
  setup/mail_improved_tracking_value/odoo/addons/mail_improved_tracking_value
  setup/mail_improved_tracking_value/setup.py
Labels: approved, bot is merging ⏳

#1223 [15.0][FIX] mail_composer_cc_bcc: changes upstream
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, bot is merging ⏳

#1222 [15.0][FIX] mail_activity_team: Fix tests
  mail_activity_done/models/res_users.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_team/tests/test_mail_activity_team.py
Labels: approved, bot is merging ⏳

#1230 [15.0][FIX] *: `image_128` -> `avatar_128`
  mail_activity_board/views/mail_activity_view.xml
  mail_activity_creator/static/src/xml/activity.xml
Labels: bot is merging ⏳

#1229 [14.0][FIX] mail_activity_creator: `image_small` -> `image_128`
  mail_activity_creator/static/src/xml/activity.xml
Labels: bot is merging ⏳

#1231 [16.0][FIX] mail_activity_board: Use valid field for user avatar (forward port)
  mail_activity_board/views/mail_activity_view.xml
Labels: bot is merging ⏳

#1134 [MIG][13.0] mail_activity_reminder
  mail_activity_reminder/README.rst
  mail_activity_reminder/__init__.py
  mail_activity_reminder/__manifest__.py
  mail_activity_reminder/data/mail_activity_reminder_cron.xml
  mail_activity_reminder/data/mail_activity_template.xml
  mail_activity_reminder/i18n/fr.po
  mail_activity_reminder/i18n/mail_activity_reminder.pot
  mail_activity_reminder/i18n/pt.po
  mail_activity_reminder/models/__init__.py
  mail_activity_reminder/models/mail_activity.py
  mail_activity_reminder/models/mail_activity_type.py
  mail_activity_reminder/readme/CONFIGURE.rst
  mail_activity_reminder/readme/CONTRIBUTORS.rst
  mail_activity_reminder/readme/DESCRIPTION.rst
  mail_activity_reminder/static/description/icon.png
  mail_activity_reminder/static/description/index.html
  mail_activity_reminder/tests/__init__.py
  mail_activity_reminder/tests/test_mail_activity_reminder.py
  mail_activity_reminder/views/mail_activity_type.xml
  setup/mail_activity_reminder/odoo/addons/mail_activity_reminder
  setup/mail_activity_reminder/setup.py
Labels: approved, bot is merging ⏳

#1137 [14.0][ADD] mail_thread_create_nolog: display create msg on the fly
  mail_thread_create_nolog/README.rst
  mail_thread_create_nolog/__init__.py
  mail_thread_create_nolog/__manifest__.py
  mail_thread_create_nolog/models/__init__.py
  mail_thread_create_nolog/models/mail_message.py
  mail_thread_create_nolog/models/mail_thread.py
  mail_thread_create_nolog/readme/CONTRIBUTORS.rst
  mail_thread_create_nolog/readme/DESCRIPTION.rst
  mail_thread_create_nolog/readme/ROADMAP.rst
  mail_thread_create_nolog/static/description/icon.png
  mail_thread_create_nolog/static/description/index.html
  mail_thread_create_nolog/tests/__init__.py
  mail_thread_create_nolog/tests/test_create_nolog.py
  setup/mail_thread_create_nolog/odoo/addons/mail_thread_create_nolog
  setup/mail_thread_create_nolog/setup.py
Labels: bot is merging ⏳

#1228 [16.0][MIG] mail_activity_reminder
  mail_activity_reminder/README.rst
  mail_activity_reminder/__init__.py
  mail_activity_reminder/__manifest__.py
  mail_activity_reminder/data/mail_activity_reminder_cron.xml
  mail_activity_reminder/data/mail_activity_template.xml
  mail_activity_reminder/i18n/fr.po
  mail_activity_reminder/i18n/mail_activity_reminder.pot
  mail_activity_reminder/i18n/pt.po
  mail_activity_reminder/models/__init__.py
  mail_activity_reminder/models/mail_activity.py
  mail_activity_reminder/models/mail_activity_type.py
  mail_activity_reminder/readme/CONFIGURE.rst
  mail_activity_reminder/readme/CONTRIBUTORS.rst
  mail_activity_reminder/readme/DESCRIPTION.rst
  mail_activity_reminder/static/description/icon.png
  mail_activity_reminder/static/description/index.html
  mail_activity_reminder/tests/__init__.py
  mail_activity_reminder/tests/test_mail_activity_reminder.py
  mail_activity_reminder/views/mail_activity_type.xml
  setup/mail_activity_reminder/odoo/addons/mail_activity_reminder
  setup/mail_activity_reminder/setup.py
Labels: approved, bot is merging ⏳

#1236 [16.0][FIX] mail_tracking: validated mailbox when computing isInFailedDiscuss
  mail_tracking/static/src/models/message_view.esm.js
Labels: approved, bot is merging ⏳

#1224 [16.0][MIG] mail_composer_cc_bcc: Migrate to version 16.0
  mail_composer_cc_bcc/README.rst
  mail_composer_cc_bcc/__init__.py
  mail_composer_cc_bcc/__manifest__.py
  mail_composer_cc_bcc/i18n/mail_composer_cc_bcc.pot
  mail_composer_cc_bcc/models/__init__.py
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/models/mail_message.py
  mail_composer_cc_bcc/models/mail_template.py
  mail_composer_cc_bcc/models/mail_thread.py
  mail_composer_cc_bcc/models/res_company.py
  mail_composer_cc_bcc/readme/CONFIGURE.rst
  mail_composer_cc_bcc/readme/CONTRIBUTORS.rst
  mail_composer_cc_bcc/readme/CREDITS.rst
  mail_composer_cc_bcc/readme/DESCRIPTION.rst
  mail_composer_cc_bcc/readme/ROADMAP.rst
  mail_composer_cc_bcc/readme/USAGE.rst
  mail_composer_cc_bcc/static/description/icon.png
  mail_composer_cc_bcc/static/description/index.html
  mail_composer_cc_bcc/static/img/email_template_form_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_default_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_template_cc_bcc.png
  mail_composer_cc_bcc/static/img/res_company_form_default_cc_bcc.png
  mail_composer_cc_bcc/tests/__init__.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mail_composer_cc_bcc/views/mail_mail_views.xml
  mail_composer_cc_bcc/views/mail_message_views.xml
  mail_composer_cc_bcc/views/mail_template_views.xml
  mail_composer_cc_bcc/views/res_company_views.xml
  mail_composer_cc_bcc/wizards/__init__.py
  mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
  mail_composer_cc_bcc/wizards/mail_compose_message.py
  mail_composer_cc_bcc/wizards/mail_compose_message_view.xml
  setup/mail_composer_cc_bcc/odoo/addons/mail_composer_cc_bcc
  setup/mail_composer_cc_bcc/setup.py
Labels: approved, bot is merging ⏳

#962 [FIX] mail_outbound_static unittest test_ir_mail_server.py
  mail_outbound_static/tests/test_ir_mail_server.py
Labels: bot is merging ⏳, no stale

#1244 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mail_chatter_thread_colour/data/ir_config_parameter_data.xml
  mail_debrand/data/ir_config_parameter.xml
  mail_drop_target/views/res_config_settings_views.xml
  mail_drop_target/views/templates.xml
  mail_improved_tracking_value/i18n/mail_improved_tracking_value.pot
  mail_improved_tracking_value/views/mail_tracking_value.xml
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
  mail_restrict_send_button/security/res_groups.xml
  mail_restrict_send_button/views/assets.xml
  mail_tracking/demo/demo.xml
  mail_tracking/i18n/mail_tracking.pot
  mail_tracking/views/mail_tracking_email_view.xml
  mail_tracking/views/mail_tracking_event_view.xml
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mass_mailing_custom_unsubscribe/i18n/mass_mailing_custom_unsubscribe.pot
  mass_mailing_custom_unsubscribe/views/assets.xml
  mass_mailing_subscription_email/data/mail_template.xml
Labels: help wanted, needs review, bot is merging ⏳

#1248 [16.0][MIG] mail_tracking_mass_mailing: Migration to 16.0
  mail_tracking_mass_mailing/README.rst
  mail_tracking_mass_mailing/__init__.py
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/hooks.py
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/da.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/el_GR.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/es_CO.po
  mail_tracking_mass_mailing/i18n/eu.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/gl.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/hr_HR.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/i18n/nb_NO.po
  mail_tracking_mass_mailing/i18n/nl.po
  mail_tracking_mass_mailing/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/pl.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/pt_BR.po
  mail_tracking_mass_mailing/i18n/ro.po
  mail_tracking_mass_mailing/i18n/ru.po
  mail_tracking_mass_mailing/i18n/sl.po
  mail_tracking_mass_mailing/i18n/tr.po
  mail_tracking_mass_mailing/models/__init__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mail_tracking_email.py
  mail_tracking_mass_mailing/models/mail_tracking_event.py
  mail_tracking_mass_mailing/models/mailing_contact.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/readme/CONTRIBUTORS.rst
  mail_tracking_mass_mailing/readme/CREDITS.rst
  mail_tracking_mass_mailing/readme/DESCRIPTION.rst
  mail_tracking_mass_mailing/readme/INSTALL.rst
  mail_tracking_mass_mailing/readme/USAGE.rst
  mail_tracking_mass_mailing/static/description/icon.png
  mail_tracking_mass_mailing/static/description/index.html
  mail_tracking_mass_mailing/tests/__init__.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mail_tracking_mass_mailing/views/mail_mass_mailing_view.xml
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mail_tracking_mass_mailing/views/mail_tracking_email_view.xml
  mail_tracking_mass_mailing/views/mailing_contact_view.xml
  setup/mail_tracking_mass_mailing/odoo/addons/mail_tracking_mass_mailing
  setup/mail_tracking_mass_mailing/setup.py
Labels: bot is merging ⏳
