Repository OCA/social, pull requests merged in 2023-03, with the labels that each got.

#1068 [15.0][FIX] mail_tracking: fix portal tests
  mail_tracking/models/ir_mail_server.py
Labels: bot is merging ⏳

#1076 [ADD] mail_activity_unlink_log
  mail_activity_unlink_log/README.rst
  mail_activity_unlink_log/__init__.py
  mail_activity_unlink_log/__manifest__.py
  mail_activity_unlink_log/data/unlink_message.xml
  mail_activity_unlink_log/models/__init__.py
  mail_activity_unlink_log/models/mail_activity.py
  mail_activity_unlink_log/readme/CONTRIBUTORS.rst
  mail_activity_unlink_log/readme/DESCRIPTION.rst
  mail_activity_unlink_log/static/description/icon.png
  mail_activity_unlink_log/tests/__init__.py
  mail_activity_unlink_log/tests/test_activity_unlink.py
  setup/mail_activity_unlink_log/odoo/addons/mail_activity_unlink_log
  setup/mail_activity_unlink_log/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1001 [ADD] mail_post_defer: deferred message posting with queue
  mail_post_defer/README.rst
  mail_post_defer/__init__.py
  mail_post_defer/__manifest__.py
  mail_post_defer/hooks.py
  mail_post_defer/models/__init__.py
  mail_post_defer/models/mail_message.py
  mail_post_defer/models/mail_thread.py
  mail_post_defer/readme/CONFIGURE.rst
  mail_post_defer/readme/CONTRIBUTORS.rst
  mail_post_defer/readme/DESCRIPTION.rst
  mail_post_defer/readme/ROADMAP.rst
  mail_post_defer/readme/USAGE.rst
  mail_post_defer/static/description/icon.png
  mail_post_defer/static/src/js/message.esm.js
  mail_post_defer/static/src/xml/message.xml
  mail_post_defer/tests/__init__.py
  mail_post_defer/tests/test_install.py
  mail_post_defer/tests/test_mail.py
  setup/mail_post_defer/odoo/addons/mail_post_defer
  setup/mail_post_defer/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1035 [16.0][MIG] mail_outbound_static: Migration to 16.0
  mail_outbound_static/README.rst
  mail_outbound_static/__init__.py
  mail_outbound_static/__manifest__.py
  mail_outbound_static/i18n/es.po
  mail_outbound_static/i18n/mail_outbound_static.pot
  mail_outbound_static/models/__init__.py
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/readme/CONTRIBUTORS.rst
  mail_outbound_static/readme/DESCRIPTION.rst
  mail_outbound_static/readme/ROADMAP.rst
  mail_outbound_static/readme/USAGE.rst
  mail_outbound_static/static/description/icon.png
  mail_outbound_static/static/description/index.html
  mail_outbound_static/tests/__init__.py
  mail_outbound_static/tests/test.msg
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_outbound_static/views/ir_mail_server_view.xml
  setup/mail_outbound_static/odoo/addons/mail_outbound_static
  setup/mail_outbound_static/setup.py
Labels: bot is merging ⏳

#1072 [MIG] email_template_qweb: Migration to 15.0
  email_template_qweb/README.rst
  email_template_qweb/__init__.py
  email_template_qweb/__manifest__.py
  email_template_qweb/demo/ir_ui_view.xml
  email_template_qweb/demo/mail_template.xml
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/email_template_qweb.pot
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/fr_FR.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/nl_NL.po
  email_template_qweb/i18n/pt_BR.po
  email_template_qweb/i18n/zh_CN.po
  email_template_qweb/migrations/15.0.1.0.0/pre-migration.py
  email_template_qweb/models/__init__.py
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
  email_template_qweb/readme/CREDITS.rst
  email_template_qweb/readme/DESCRIPTION.rst
  email_template_qweb/readme/USAGE.rst
  email_template_qweb/static/description/icon.png
  email_template_qweb/static/description/index.html
  email_template_qweb/tests/__init__.py
  email_template_qweb/tests/test_mail_template_qweb.py
  email_template_qweb/views/mail_template.xml
  setup/email_template_qweb/odoo/addons/email_template_qweb
  setup/email_template_qweb/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1051 [15.0][FIX] mail_outbound_static: Move smtp info update logic to _prepare_email_message()
  mail_outbound_static/README.rst
  mail_outbound_static/models/ir_mail_server.py
  mail_outbound_static/readme/CONTRIBUTORS.rst
  mail_outbound_static/static/description/index.html
Labels: approved, bot is merging ⏳

#1092 [15.0][MIG] mass_mailing_custom_unsubscribe_event: Migration to version 15.0
  mass_mailing_custom_unsubscribe_event/README.rst
  mass_mailing_custom_unsubscribe_event/__init__.py
  mass_mailing_custom_unsubscribe_event/__manifest__.py
  mass_mailing_custom_unsubscribe_event/i18n/mass_mailing_custom_unsubscribe_event.pot
  mass_mailing_custom_unsubscribe_event/models/__init__.py
  mass_mailing_custom_unsubscribe_event/models/event_registration.py
  mass_mailing_custom_unsubscribe_event/readme/CONTRIBUTORS.rst
  mass_mailing_custom_unsubscribe_event/readme/DESCRIPTION.rst
  mass_mailing_custom_unsubscribe_event/readme/USAGE.rst
  mass_mailing_custom_unsubscribe_event/static/description/icon.png
  mass_mailing_custom_unsubscribe_event/static/description/index.html
  mass_mailing_custom_unsubscribe_event/static/src/js/tour.esm.js
  mass_mailing_custom_unsubscribe_event/tests/__init__.py
  mass_mailing_custom_unsubscribe_event/tests/test_ui.py
  mass_mailing_custom_unsubscribe_event/views/event_registration_views.xml
  setup/mass_mailing_custom_unsubscribe_event/odoo/addons/mass_mailing_custom_unsubscribe_event
  setup/mass_mailing_custom_unsubscribe_event/setup.py
Labels: approved, bot is merging ⏳
