Repository OCA/social, pull requests merged in 2023-12, with the labels that each got.

#1265 [16.0][MIG] mass_mailing_unique: Migration to 16.0
  mass_mailing_unique/README.rst
  mass_mailing_unique/__init__.py
  mass_mailing_unique/__manifest__.py
  mass_mailing_unique/hooks.py
  mass_mailing_unique/i18n/ca.po
  mass_mailing_unique/i18n/de.po
  mass_mailing_unique/i18n/es.po
  mass_mailing_unique/i18n/fr.po
  mass_mailing_unique/i18n/hr.po
  mass_mailing_unique/i18n/it.po
  mass_mailing_unique/i18n/mass_mailing_unique.pot
  mass_mailing_unique/i18n/pt.po
  mass_mailing_unique/i18n/sl.po
  mass_mailing_unique/models/__init__.py
  mass_mailing_unique/models/mailing_contact.py
  mass_mailing_unique/models/mailing_list.py
  mass_mailing_unique/readme/CONTRIBUTORS.rst
  mass_mailing_unique/readme/DESCRIPTION.rst
  mass_mailing_unique/readme/INSTALL.rst
  mass_mailing_unique/static/description/icon.png
  mass_mailing_unique/static/description/index.html
  mass_mailing_unique/tests/__init__.py
  mass_mailing_unique/tests/test_mass_mailing_unique.py
  setup/mass_mailing_unique/odoo/addons/mass_mailing_unique
  setup/mass_mailing_unique/setup.py
Labels: approved, bot is merging ⏳

#1226 [FIX][14.0] mail_debrand tour info on signup email
  mail_debrand/models/mail_render_mixin.py
Labels: bot is merging ⏳

#1115 [MIG][16.0]mail_autosubscribe
  mail_autosubscribe/README.rst
  mail_autosubscribe/__init__.py
  mail_autosubscribe/__manifest__.py
  mail_autosubscribe/i18n/ca.po
  mail_autosubscribe/i18n/mail_autosubscribe.pot
  mail_autosubscribe/models/__init__.py
  mail_autosubscribe/models/mail_autosubscribe.py
  mail_autosubscribe/models/mail_template.py
  mail_autosubscribe/models/mail_thread.py
  mail_autosubscribe/models/models.py
  mail_autosubscribe/models/res_partner.py
  mail_autosubscribe/readme/CONFIGURE.rst
  mail_autosubscribe/readme/CONTRIBUTORS.rst
  mail_autosubscribe/readme/DESCRIPTION.rst
  mail_autosubscribe/readme/ROADMAP.rst
  mail_autosubscribe/security/ir.model.access.csv
  mail_autosubscribe/static/description/icon.png
  mail_autosubscribe/static/description/index.html
  mail_autosubscribe/tests/__init__.py
  mail_autosubscribe/tests/models/__init__.py
  mail_autosubscribe/tests/models/fake_order.py
  mail_autosubscribe/tests/test_mail_autosubscribe.py
  mail_autosubscribe/views/mail_autosubscribe.xml
  mail_autosubscribe/views/mail_template.xml
  mail_autosubscribe/views/res_partner.xml
  requirements.txt
  setup/mail_autosubscribe/odoo/addons/mail_autosubscribe
  setup/mail_autosubscribe/setup.py
Labels: bot is merging ⏳, no stale

#1116 [16.0][ADD] mail_send_confirmation
  mail_send_confirmation/README.rst
  mail_send_confirmation/__init__.py
  mail_send_confirmation/__manifest__.py
  mail_send_confirmation/readme/CONTRIBUTORS.rst
  mail_send_confirmation/readme/DESCRIPTION.rst
  mail_send_confirmation/static/description/icon.png
  mail_send_confirmation/static/description/index.html
  mail_send_confirmation/static/src/models/composer_view.esm.js
  setup/mail_send_confirmation/odoo/addons/mail_send_confirmation
  setup/mail_send_confirmation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1181 [16.0][FIX] mail_debrand: Avoid odoo.sh links removal (url like my-customer.odoo.com )
  mail_debrand/models/mail_render_mixin.py
Labels: approved, bot is merging ⏳
