Repository OCA/social, pull requests merged in 2023-01, with the labels that each got.

#1038 [13.0][IMP] mail_tracking_mailgun: mass mailing manual tracking
  mail_tracking/models/mail_tracking_email.py
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/views/mail_tracking_email.xml
  mail_tracking_mass_mailing/models/mail_tracking_email.py
Labels: bot is merging ⏳

#976 [16.0] [MIG] mail_attach_existing_attachment
  mail_attach_existing_attachment/README.rst
  mail_attach_existing_attachment/__init__.py
  mail_attach_existing_attachment/__manifest__.py
  mail_attach_existing_attachment/i18n/ca.po
  mail_attach_existing_attachment/i18n/de.po
  mail_attach_existing_attachment/i18n/es.po
  mail_attach_existing_attachment/i18n/es_CO.po
  mail_attach_existing_attachment/i18n/fr.po
  mail_attach_existing_attachment/i18n/he.po
  mail_attach_existing_attachment/i18n/hr.po
  mail_attach_existing_attachment/i18n/it.po
  mail_attach_existing_attachment/i18n/mail_attach_existing_attachment.pot
  mail_attach_existing_attachment/i18n/pt_BR.po
  mail_attach_existing_attachment/i18n/sl.po
  mail_attach_existing_attachment/i18n/zh_CN.po
  mail_attach_existing_attachment/readme/CONTRIBUTORS.rst
  mail_attach_existing_attachment/readme/DESCRIPTION.rst
  mail_attach_existing_attachment/readme/ROADMAP.rst
  mail_attach_existing_attachment/readme/USAGE.rst
  mail_attach_existing_attachment/static/description/attachment.png
  mail_attach_existing_attachment/static/description/ex_mail_compose_message.png
  mail_attach_existing_attachment/static/description/icon.png
  mail_attach_existing_attachment/static/description/index.html
  mail_attach_existing_attachment/tests/__init__.py
  mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
  mail_attach_existing_attachment/wizard/__init__.py
  mail_attach_existing_attachment/wizard/mail_compose_message.py
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
  setup/mail_attach_existing_attachment/odoo/addons/mail_attach_existing_attachment
  setup/mail_attach_existing_attachment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#966 [13.0][FIX] mail_tracking: permissions
  mail_tracking/controllers/main.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/res_partner.py
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/res_partner_view.xml
Labels: bot is merging ⏳, stale

#1039 [15.0][FIX] mail_quoted_reply: format of default m2m value in context (fixes tests)
  mail_quoted_reply/models/mail_message.py
  mail_quoted_reply/tests/test_reply.py
Labels: approved, bot is merging ⏳

#1030 [MIG] microsoft_outlook_single_tenant: Migration to 15.0
  microsoft_outlook_single_tenant/README.rst
  microsoft_outlook_single_tenant/__init__.py
  microsoft_outlook_single_tenant/__manifest__.py
  microsoft_outlook_single_tenant/i18n/microsoft_outlook_single_tenant.pot
  microsoft_outlook_single_tenant/models/__init__.py
  microsoft_outlook_single_tenant/models/microsoft_outlook_mixin.py
  microsoft_outlook_single_tenant/models/res_config_settings.py
  microsoft_outlook_single_tenant/readme/CONFIGURE.rst
  microsoft_outlook_single_tenant/readme/CONTRIBUTORS.rst
  microsoft_outlook_single_tenant/readme/DESCRIPTION.rst
  microsoft_outlook_single_tenant/static/description/icon.png
  microsoft_outlook_single_tenant/static/description/index.html
  microsoft_outlook_single_tenant/tests/__init__.py
  microsoft_outlook_single_tenant/tests/test_fetchmail_outlook.py
  microsoft_outlook_single_tenant/views/res_config_settings_views.xml
  setup/microsoft_outlook_single_tenant/odoo/addons/microsoft_outlook_single_tenant
  setup/microsoft_outlook_single_tenant/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1046 [IMP] mail_drop_target: Use OWL definition
  mail_drop_target/__manifest__.py
  mail_drop_target/static/src/js/mail_drop_target.js
  mail_drop_target/static/src/xml/chatter.xml
Labels: approved, bot is merging ⏳

#1048 [14.0][IMP] mail_tracking_mailgun: mass mailing manual tracking
  mail_tracking/models/mail_tracking_email.py
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/views/mail_tracking_email.xml
  mail_tracking_mass_mailing/models/mail_tracking_email.py
Labels: approved, bot is merging ⏳

#1052 [13.0][FIX] mail_tracking: failed message compute performance
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_tracking_email.py
Labels: approved, bot is merging ⏳

#1047 [14.0][FIX] mail_tracking: forward ports
  mail_tracking/controllers/main.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/mail_tracking_event.py
  mail_tracking/models/res_partner.py
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/mail_tracking_email_view.xml
  mail_tracking/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1054 [15.0] [IMP] `mail_activity_team`: Allow to set a team on server actions
  mail_activity_team/__manifest__.py
  mail_activity_team/models/__init__.py
  mail_activity_team/models/ir_actions_server.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/ir_actions_server_views.xml
Labels: approved, bot is merging ⏳

#1056 [15.0][IMP] mail_tracking_mailgun: mass mailing manual tracking
  mail_tracking/models/mail_tracking_email.py
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/views/mail_tracking_email.xml
Labels: approved, bot is merging ⏳
