Repository OCA/social, pull requests merged in 2023-07, with the labels that each got.

#1078 [15.0][FIX] mail_tracking: Crash to add malformed emails to recipients suggestions
  mail_tracking/models/mail_thread.py
Labels: bot is merging ⏳, stale

#1144 [16.0] [MIG] mail_layout_preview: Migrate to version 16.0
  mail_layout_preview/README.rst
  mail_layout_preview/__init__.py
  mail_layout_preview/__manifest__.py
  mail_layout_preview/controllers/__init__.py
  mail_layout_preview/controllers/layout_preview.py
  mail_layout_preview/i18n/mail_layout_preview.pot
  mail_layout_preview/readme/CONTRIBUTORS.rst
  mail_layout_preview/readme/CREDITS.rst
  mail_layout_preview/readme/DESCRIPTION.rst
  mail_layout_preview/readme/USAGE.rst
  mail_layout_preview/static/description/icon.png
  mail_layout_preview/static/description/index.html
  mail_layout_preview/templates/email_preview.xml
  mail_layout_preview/tests/__init__.py
  mail_layout_preview/tests/test_layout_preview.py
  mail_layout_preview/wizard/__init__.py
  mail_layout_preview/wizard/email_template_preview.py
  mail_layout_preview/wizard/email_template_preview.xml
  setup/mail_layout_preview/odoo/addons/mail_layout_preview
  setup/mail_layout_preview/setup.py
Labels: bot is merging ⏳

#1160 [ADD] mail_composer_cc_bcc: send email to cc, bcc addresses
  mail_composer_cc_bcc/README.rst
  mail_composer_cc_bcc/__init__.py
  mail_composer_cc_bcc/__manifest__.py
  mail_composer_cc_bcc/models/__init__.py
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/models/mail_message.py
  mail_composer_cc_bcc/models/mail_template.py
  mail_composer_cc_bcc/models/mail_thread.py
  mail_composer_cc_bcc/models/res_company.py
  mail_composer_cc_bcc/readme/CONFIGURE.rst
  mail_composer_cc_bcc/readme/CONTRIBUTORS.rst
  mail_composer_cc_bcc/readme/CREDITS.rst
  mail_composer_cc_bcc/readme/DESCRIPTION.rst
  mail_composer_cc_bcc/readme/USAGE.rst
  mail_composer_cc_bcc/static/description/index.html
  mail_composer_cc_bcc/static/img/email_template_form_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_default_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_template_cc_bcc.png
  mail_composer_cc_bcc/static/img/res_company_form_default_cc_bcc.png
  mail_composer_cc_bcc/tests/__init__.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mail_composer_cc_bcc/views/mail_mail_views.xml
  mail_composer_cc_bcc/views/mail_message_views.xml
  mail_composer_cc_bcc/views/mail_template_views.xml
  mail_composer_cc_bcc/views/res_company_views.xml
  mail_composer_cc_bcc/wizards/__init__.py
  mail_composer_cc_bcc/wizards/account_invoice_send_views.xml
  mail_composer_cc_bcc/wizards/mail_compose_message.py
  mail_composer_cc_bcc/wizards/mail_compose_message_view.xml
  setup/mail_composer_cc_bcc/odoo/addons/mail_composer_cc_bcc
  setup/mail_composer_cc_bcc/setup.py
Labels: approved, bot is merging ⏳

#930 [ADD] mail_activity_fetchmail: Add in 15.0
  fetchmail_mail_activity_team_activity/README.rst
  fetchmail_mail_activity_team_activity/__init__.py
  fetchmail_mail_activity_team_activity/__manifest__.py
  fetchmail_mail_activity_team_activity/models/__init__.py
  fetchmail_mail_activity_team_activity/models/mail_thread.py
  fetchmail_mail_activity_team_activity/tests/__init__.py
  fetchmail_mail_activity_team_activity/tests/test_activity.py
  setup/fetchmail_mail_activity_team_activity/odoo/addons/fetchmail_mail_activity_team_activity
  setup/fetchmail_mail_activity_team_activity/setup.py
Labels: bot is merging ⏳

#1186 [14][FIX] base_search_mail_content: Avoid CacheMiss errors
  base_search_mail_content/models/mail_thread.py
Labels: needs review, bot is merging ⏳

#1180 [15.0][IMP] mail_activity_board: Add group so that the activity dashboard is only visible if the user has the permission.
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/es.po
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/mail_activity.py
  mail_activity_board/security/groups.xml
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, bot is merging ⏳

#1188 [16.0][IMP] mail_activity_board: Add group so that the activity dashboard is only visible if the user has the permission.
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/es.po
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/mail_activity.py
  mail_activity_board/security/groups.xml
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, bot is merging ⏳

#1190 [15.0][FIX] mail_tracking_mailgun: bounces error
  mail_tracking_mailgun/models/res_partner.py
Labels: approved, bot is merging ⏳
