Repository OCA/social, pull requests merged in 2023-02, with the labels that each got.

#993 13.0 mail_activity_team fix string 'test field'
  mail_activity_team/models/mail_activity_mixin.py
Labels: approved, bot is merging ⏳

#1063 [15.0] Deprecate microsoft_outlook_single_tenant
  microsoft_outlook_single_tenant/__init__.py
  microsoft_outlook_single_tenant/__manifest__.py
  microsoft_outlook_single_tenant/hooks.py
  microsoft_outlook_single_tenant/tests/test_fetchmail_outlook.py
Labels: bot is merging ⏳

#1062 [14.0] Deprecate microsoft_outlook_single_tenant
  microsoft_outlook_single_tenant/__init__.py
  microsoft_outlook_single_tenant/__manifest__.py
  microsoft_outlook_single_tenant/hooks.py
  microsoft_outlook_single_tenant/tests/test_fetchmail_outlook.py
Labels: bot is merging ⏳

#1057 [15.0][FIX] mail_tracking: forward ports
  mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.esm.js
  mail_tracking/__init__.py
  mail_tracking/__manifest__.py
  mail_tracking/controllers/main.py
  mail_tracking/hooks.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/mail_tracking_event.py
  mail_tracking/models/res_partner.py
  mail_tracking/static/src/js/chatter.esm.js
  mail_tracking/static/src/js/discuss/discuss.esm.js
  mail_tracking/static/src/js/failed_message/mail_failed_box.esm.js
  mail_tracking/static/src/js/models/thread.esm.js
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/mail_tracking_email_view.xml
  mail_tracking/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1022 [15.0][MIG] mail_tracking_mass_mailing: Migration to version 15.0
  mail_tracking_mass_mailing/README.rst
  mail_tracking_mass_mailing/__init__.py
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/hooks.py
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/da.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/el_GR.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/es_CO.po
  mail_tracking_mass_mailing/i18n/eu.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/gl.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/hr_HR.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/i18n/nb_NO.po
  mail_tracking_mass_mailing/i18n/nl.po
  mail_tracking_mass_mailing/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/pl.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/pt_BR.po
  mail_tracking_mass_mailing/i18n/ro.po
  mail_tracking_mass_mailing/i18n/ru.po
  mail_tracking_mass_mailing/i18n/sl.po
  mail_tracking_mass_mailing/i18n/tr.po
  mail_tracking_mass_mailing/models/__init__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mail_tracking_email.py
  mail_tracking_mass_mailing/models/mail_tracking_event.py
  mail_tracking_mass_mailing/models/mailing_contact.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/readme/CONTRIBUTORS.rst
  mail_tracking_mass_mailing/readme/DESCRIPTION.rst
  mail_tracking_mass_mailing/readme/INSTALL.rst
  mail_tracking_mass_mailing/readme/USAGE.rst
  mail_tracking_mass_mailing/static/description/icon.png
  mail_tracking_mass_mailing/static/description/index.html
  mail_tracking_mass_mailing/tests/__init__.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mail_tracking_mass_mailing/views/mail_mass_mailing_view.xml
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mail_tracking_mass_mailing/views/mail_tracking_email_view.xml
  mail_tracking_mass_mailing/views/mailing_contact_view.xml
  setup/mail_tracking_mass_mailing/odoo/addons/mail_tracking_mass_mailing
  setup/mail_tracking_mass_mailing/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1058 [15.0][FIX] mail_activity_team: warning Two fields have same label
  mail_activity_team/models/mail_activity.py
Labels: approved, bot is merging ⏳

#939 [15.0][FIX] mail_debrand issues
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_render_mixin.py
  mail_debrand/readme/HISTORY.rst
  mail_debrand/tests/test_mail_debrand_digest.py
Labels: needs review, approved, bot is merging ⏳

#994 [15.0] [FIX] `mail_activity_done`: Remove broken and apparently unused js file
  mail_activity_done/__manifest__.py
  mail_activity_done/static/src/js/mail_activity.esm.js
Labels: approved, bot is merging ⏳

#941 [14.0][mail_tracking] [IMP] Add option to keep aliases in mail tracking
  mail_tracking/__manifest__.py
  mail_tracking/models/__init__.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_thread.py
  mail_tracking/models/res_company.py
  mail_tracking/models/res_config_settings.py
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#1053 [15.0][FIX] mail_tracking: mixed classes
  mail_tracking/controllers/__init__.py
  mail_tracking/controllers/discuss.py
  mail_tracking/controllers/main.py
Labels: bot is merging ⏳

#973 [15.0][MIG] mail_layout_force
  mail_layout_force/README.rst
  mail_layout_force/__init__.py
  mail_layout_force/__manifest__.py
  mail_layout_force/data/mail_layout.xml
  mail_layout_force/demo/mail_layout.xml
  mail_layout_force/i18n/mail_layout_force.pot
  mail_layout_force/models/__init__.py
  mail_layout_force/models/mail_template.py
  mail_layout_force/models/mail_thread.py
  mail_layout_force/readme/CONFIGURE.rst
  mail_layout_force/readme/CONTRIBUTORS.rst
  mail_layout_force/readme/DESCRIPTION.rst
  mail_layout_force/static/description/icon.png
  mail_layout_force/static/description/index.html
  mail_layout_force/tests/__init__.py
  mail_layout_force/tests/test_mail_layout_force.py
  mail_layout_force/views/mail_template.xml
  mail_layout_force/wizards/__init__.py
  mail_layout_force/wizards/mail_compose_message.py
  setup/mail_layout_force/odoo/addons/mail_layout_force
  setup/mail_layout_force/setup.py
Labels: approved, ready to merge, bot is merging ⏳
