Repository OCA/social, pull requests merged in 2023-09, with the labels that each got.

#1213 [MIG+IMP] mail_post_defer: migrate to 16.0, allow editing messages
  mail_post_defer/README.rst
  mail_post_defer/__init__.py
  mail_post_defer/__manifest__.py
  mail_post_defer/hooks.py
  mail_post_defer/i18n/mail_post_defer.pot
  mail_post_defer/models/__init__.py
  mail_post_defer/models/mail_message.py
  mail_post_defer/models/mail_thread.py
  mail_post_defer/readme/CONFIGURE.rst
  mail_post_defer/readme/CONTRIBUTORS.rst
  mail_post_defer/readme/DESCRIPTION.rst
  mail_post_defer/readme/ROADMAP.rst
  mail_post_defer/readme/USAGE.rst
  mail_post_defer/static/description/icon.png
  mail_post_defer/static/description/index.html
  mail_post_defer/static/src/js/message.esm.js
  mail_post_defer/tests/__init__.py
  mail_post_defer/tests/test_install.py
  mail_post_defer/tests/test_mail.py
  setup/mail_post_defer/odoo/addons/mail_post_defer
  setup/mail_post_defer/setup.py
Labels: needs review, bot is merging ⏳

#1132 [16.0][MIG] mail_show_follower
  mail_show_follower/README.rst
  mail_show_follower/__init__.py
  mail_show_follower/__manifest__.py
  mail_show_follower/i18n/fr.po
  mail_show_follower/i18n/mail_show_follower.pot
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/models/res_users.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/readme/DESCRIPTION.rst
  mail_show_follower/readme/USAGE.rst
  mail_show_follower/static/description/icon.png
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
  mail_show_follower/views/res_users.xml
  setup/mail_show_follower/odoo/addons/mail_show_follower
  setup/mail_show_follower/setup.py
Labels: approved, bot is merging ⏳

#1168 [16.0][MIG] mail_activity_done: Migration to 16.0
  mail_activity_done/README.rst
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/i18n/hu.po
  mail_activity_done/i18n/mail_activity_done.pot
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/readme/CONTRIBUTORS.rst
  mail_activity_done/readme/DESCRIPTION.rst
  mail_activity_done/readme/USAGE.rst
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/description/index.html
  mail_activity_done/static/src/js/mail_activity.esm.js
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
  setup/mail_activity_done/odoo/addons/mail_activity_done
  setup/mail_activity_done/setup.py
Labels: approved, bot is merging ⏳

#1214 [16.0][FIX] mail_activity_done: patch _action_done in a more reliable way
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/tests/test_mail_activity_done.py
Labels: approved, ready to merge

#1011 [13.0][FIX] mail_activity_done: patch _action_done in a more reliable way
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/tests/test_mail_activity_done.py
Labels: bot is merging ⏳
