Repository OCA/social, pull requests merged in 2023-05, with the labels that each got.

#1139 [14.0][FIX] mail tracking bounce notification not logged
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳

#1140 [15.0][FWP] Fix mail tracking bounce notification not logged
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳

#1141 [15.0][FIX] mail_tracking: thread permissions
  mail_tracking/models/mail_thread.py
Labels: approved, bot is merging ⏳

#1111 [16.0][MIG] email_template_qweb: Migration to 16.0
  email_template_qweb/README.rst
  email_template_qweb/__init__.py
  email_template_qweb/__manifest__.py
  email_template_qweb/demo/ir_ui_view.xml
  email_template_qweb/demo/mail_template.xml
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/email_template_qweb.pot
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/fr_FR.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/nl_NL.po
  email_template_qweb/i18n/pt_BR.po
  email_template_qweb/i18n/zh_CN.po
  email_template_qweb/models/__init__.py
  email_template_qweb/models/mail_template.py
  email_template_qweb/readme/CONTRIBUTORS.rst
  email_template_qweb/readme/CREDITS.rst
  email_template_qweb/readme/DESCRIPTION.rst
  email_template_qweb/readme/USAGE.rst
  email_template_qweb/static/description/icon.png
  email_template_qweb/static/description/index.html
  email_template_qweb/tests/__init__.py
  email_template_qweb/tests/test_mail_template_qweb.py
  email_template_qweb/views/mail_template.xml
  setup/email_template_qweb/odoo/addons/email_template_qweb
  setup/email_template_qweb/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1149 [15.0][FIX] mail_tracking: allowed trackings compute
  mail_tracking/models/mail_tracking_email.py
Labels: bot is merging ⏳

#1142 [15.0][MIG] mail_send_copy (rebased)
  mail_send_copy/README.rst
  mail_send_copy/__init__.py
  mail_send_copy/__manifest__.py
  mail_send_copy/i18n/fr.po
  mail_send_copy/i18n/mail_send_copy.pot
  mail_send_copy/models/__init__.py
  mail_send_copy/models/ir_mail_server.py
  mail_send_copy/readme/CONTRIBUTORS.rst
  mail_send_copy/readme/DESCRIPTION.rst
  mail_send_copy/readme/ROADMAP.rst
  mail_send_copy/static/description/icon.png
  mail_send_copy/static/description/index.html
  setup/mail_send_copy/odoo/addons/mail_send_copy
  setup/mail_send_copy/setup.py
Labels: approved, bot is merging ⏳
