Repository OCA/social, pull requests merged in 2024-03, with the labels that each got.

#1124 [16.0][MIG] mail_inline_css: Migrate to version 16.0
  mail_inline_css/README.rst
  mail_inline_css/__init__.py
  mail_inline_css/__manifest__.py
  mail_inline_css/demo/demo_mail_template.xml
  mail_inline_css/demo/demo_template.xml
  mail_inline_css/i18n/de.po
  mail_inline_css/i18n/es.po
  mail_inline_css/i18n/es_MX.po
  mail_inline_css/i18n/fr.po
  mail_inline_css/i18n/hr.po
  mail_inline_css/i18n/it.po
  mail_inline_css/i18n/mail_inline_css.pot
  mail_inline_css/i18n/nl_NL.po
  mail_inline_css/i18n/zh_CN.po
  mail_inline_css/models/__init__.py
  mail_inline_css/models/mail_template.py
  mail_inline_css/readme/CONTRIBUTORS.rst
  mail_inline_css/readme/CREDITS.rst
  mail_inline_css/readme/DESCRIPTION.rst
  mail_inline_css/static/description/icon.png
  mail_inline_css/static/description/index.html
  mail_inline_css/tests/__init__.py
  mail_inline_css/tests/test_mail_inline_styles.py
  requirements.txt
  setup/mail_inline_css/odoo/addons/mail_inline_css
  setup/mail_inline_css/setup.py
Labels: bot is merging ⏳

#1322 [15.0][IMP] mail_activity_plan: Improve js code with MailActivityPlanExtension (used in ListController and FormController)
  mail_activity_plan/static/src/js/mail_activity_plan.js
Labels: approved, bot is merging ⏳

#1332 [16.0][FIX] mail_tracking: be closer to what Odoo does in a nodb environment
  mail_tracking/README.rst
  mail_tracking/readme/INSTALL.rst
  mail_tracking/static/description/index.html
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳

#1329 [16.0][MIG] fetchmail_thread_default
  fetchmail_thread_default/README.rst
  fetchmail_thread_default/__init__.py
  fetchmail_thread_default/__manifest__.py
  fetchmail_thread_default/demo/data.xml
  fetchmail_thread_default/i18n/.empty
  fetchmail_thread_default/i18n/ca.po
  fetchmail_thread_default/i18n/de.po
  fetchmail_thread_default/i18n/es.po
  fetchmail_thread_default/i18n/fetchmail_thread_default.pot
  fetchmail_thread_default/i18n/fr.po
  fetchmail_thread_default/i18n/hr.po
  fetchmail_thread_default/i18n/it.po
  fetchmail_thread_default/i18n/pt_BR.po
  fetchmail_thread_default/i18n/pt_PT.po
  fetchmail_thread_default/i18n/sl.po
  fetchmail_thread_default/i18n/tr.po
  fetchmail_thread_default/i18n/zh_CN.po
  fetchmail_thread_default/models/__init__.py
  fetchmail_thread_default/models/fetchmail_server.py
  fetchmail_thread_default/models/mail_thread.py
  fetchmail_thread_default/readme/CONFIGURE.rst
  fetchmail_thread_default/readme/CONTRIBUTORS.rst
  fetchmail_thread_default/readme/DESCRIPTION.rst
  fetchmail_thread_default/readme/USAGE.rst
  fetchmail_thread_default/static/description/icon.png
  fetchmail_thread_default/static/description/index.html
  fetchmail_thread_default/tests/__init__.py
  fetchmail_thread_default/tests/test_fetchmail.py
  fetchmail_thread_default/views/fetchmail_server_view.xml
  setup/fetchmail_thread_default/odoo/addons/fetchmail_thread_default
  setup/fetchmail_thread_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1335 [16.0][MIG] mail_activity_plan: Migration to 16.0
  mail_activity_plan/README.rst
  mail_activity_plan/__init__.py
  mail_activity_plan/__manifest__.py
  mail_activity_plan/demo/mail_activity_plan_demo.xml
  mail_activity_plan/i18n/es.po
  mail_activity_plan/i18n/mail_activity_plan.pot
  mail_activity_plan/models/__init__.py
  mail_activity_plan/models/mail_activity_plan.py
  mail_activity_plan/readme/CONFIGURE.rst
  mail_activity_plan/readme/CONTRIBUTORS.rst
  mail_activity_plan/readme/DESCRIPTION.rst
  mail_activity_plan/readme/USAGE.rst
  mail_activity_plan/security/ir.model.access.csv
  mail_activity_plan/security/security.xml
  mail_activity_plan/static/description/icon.png
  mail_activity_plan/static/description/index.html
  mail_activity_plan/static/src/js/mail_activity_plan.esm.js
  mail_activity_plan/tests/__init__.py
  mail_activity_plan/tests/test_mail_activity_plan.py
  mail_activity_plan/views/mail_activity_plan_views.xml
  mail_activity_plan/wizards/__init__.py
  mail_activity_plan/wizards/wizard_mail_activity_plan.py
  mail_activity_plan/wizards/wizard_mail_activity_views.xml
  setup/mail_activity_plan/odoo/addons/mail_activity_plan
  setup/mail_activity_plan/setup.py
Labels: approved, bot is merging ⏳

#1325 [17.0][UPD] copier version 1.20
  .copier-answers.yml
  .pre-commit-config.yaml
  .ruff.toml
  mail_activity_board/__manifest__.py
  mail_outbound_static/tests/test_ir_mail_server.py
  mail_partner_forwarding/models/res_partner.py
Labels: approved, bot is merging ⏳

#1334 [FIX] mail_drop_target: remove carriage returns and newlines from msg id
  mail_drop_target/models/mail_thread.py
Labels: approved, ready to merge, bot is merging ⏳
