Repository OCA/social, pull requests merged in 2024-05, with the labels that each got.

#1355 [15.0][ADD] outgoing_email_by_model
  outgoing_email_by_model/README.rst
  outgoing_email_by_model/__init__.py
  outgoing_email_by_model/__manifest__.py
  outgoing_email_by_model/models/__init__.py
  outgoing_email_by_model/models/ir_model.py
  outgoing_email_by_model/models/mail_thread.py
  outgoing_email_by_model/readme/CONFIGURE.rst
  outgoing_email_by_model/readme/CONTRIBUTORS.rst
  outgoing_email_by_model/readme/DESCRIPTION.rst
  outgoing_email_by_model/static/description/index.html
  outgoing_email_by_model/tests/__init__.py
  outgoing_email_by_model/tests/models.py
  outgoing_email_by_model/tests/test_mailserver_by_model.py
  outgoing_email_by_model/views/ir_model.xml
  setup/outgoing_email_by_model/odoo/addons/outgoing_email_by_model
  setup/outgoing_email_by_model/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1362 [17.0][MIG] mail_optional_autofollow
  mail_optional_autofollow/README.rst
  mail_optional_autofollow/__init__.py
  mail_optional_autofollow/__manifest__.py
  mail_optional_autofollow/i18n/ca.po
  mail_optional_autofollow/i18n/de.po
  mail_optional_autofollow/i18n/es.po
  mail_optional_autofollow/i18n/es_CO.po
  mail_optional_autofollow/i18n/fr.po
  mail_optional_autofollow/i18n/hr.po
  mail_optional_autofollow/i18n/it.po
  mail_optional_autofollow/i18n/mail_optional_autofollow.pot
  mail_optional_autofollow/i18n/pt_BR.po
  mail_optional_autofollow/i18n/sl.po
  mail_optional_autofollow/pyproject.toml
  mail_optional_autofollow/static/description/autofollow.png
  mail_optional_autofollow/static/description/icon.png
  mail_optional_autofollow/tests/__init__.py
  mail_optional_autofollow/tests/test_mail_optional_autofollow.py
  mail_optional_autofollow/wizard/__init__.py
  mail_optional_autofollow/wizard/mail_compose_message.py
  mail_optional_autofollow/wizard/mail_compose_message_view.xml
Labels: approved, bot is merging ⏳

#1155 [15.0][IMP]mail_quoted_reply: format mail date
  mail_quoted_reply/models/mail_message.py
  mail_quoted_reply/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳, stale

#1094 [16.0][MIG] mail_template_multi_attachment
  mail_template_multi_attachment/README.rst
  mail_template_multi_attachment/__init__.py
  mail_template_multi_attachment/__manifest__.py
  mail_template_multi_attachment/i18n/mail_template_multi_attachment.pot
  mail_template_multi_attachment/models/__init__.py
  mail_template_multi_attachment/models/mail_template.py
  mail_template_multi_attachment/models/mail_template_report.py
  mail_template_multi_attachment/readme/CONFIGURE.rst
  mail_template_multi_attachment/readme/CONTRIBUTORS.rst
  mail_template_multi_attachment/readme/DESCRIPTION.rst
  mail_template_multi_attachment/readme/USAGE.rst
  mail_template_multi_attachment/security/mail_template_report.xml
  mail_template_multi_attachment/static/description/icon.png
  mail_template_multi_attachment/static/description/index.html
  mail_template_multi_attachment/tests/__init__.py
  mail_template_multi_attachment/tests/test_mail_template.py
  mail_template_multi_attachment/views/mail_template.xml
  mail_template_multi_attachment/views/mail_template_report.xml
  setup/mail_template_multi_attachment/odoo/addons/mail_template_multi_attachment
  setup/mail_template_multi_attachment/setup.py
Labels: approved, bot is merging ⏳

#1372 [IMP] mail_post_defer: defer more mails
  .copier-answers.yml
  .github/workflows/test.yml
  mail_post_defer/models/__init__.py
  mail_post_defer/models/mail_message_schedule.py
  mail_post_defer/models/mail_thread.py
  mail_post_defer/static/description/index.html
  mail_post_defer/tests/test_mail.py
Labels: enhancement, bot is merging ⏳
