Repository OCA/social, pull requests merged in 2024-09, with the labels that each got.

#1415 [14.0][IMP] generate attachment name regarding partner lang
  mail_template_multi_attachment/models/mail_template.py
Labels: approved, ready to merge, bot is merging ⏳

#1432 [16.0][FIX] mail_template_substitute: Corrected method name override _onchange_template_id_wrapper
  mail_template_substitute/tests/test_mail_template_substitute.py
  mail_template_substitute/wizards/mail_compose_message.py
Labels: approved, ready to merge, bot is merging ⏳

#1444 [16.0][FIX] mail_gateway: Pass company in order to ensure that it is executed properly
  mail_gateway/controllers/gateway.py
  mail_gateway/models/mail_gateway.py
Labels: bot is merging ⏳

#1439 [14.0] Port mail_autogenerated_header
  mail_autogenerated_header/README.rst
  mail_autogenerated_header/__init__.py
  mail_autogenerated_header/__manifest__.py
  mail_autogenerated_header/i18n/mail_autogenerated_header.pot
  mail_autogenerated_header/models/__init__.py
  mail_autogenerated_header/models/ir_mail_server.py
  mail_autogenerated_header/models/mail_thread.py
  mail_autogenerated_header/readme/CONTRIBUTORS.rst
  mail_autogenerated_header/readme/DESCRIPTION.rst
  mail_autogenerated_header/readme/USAGE.rst
  mail_autogenerated_header/readme/newsfragments/.gitkeep
  mail_autogenerated_header/static/description/icon.png
  mail_autogenerated_header/static/description/index.html
  mail_autogenerated_header/tests/__init__.py
  mail_autogenerated_header/tests/test_mail_autogenerated_header.py
  setup/mail_autogenerated_header/odoo/addons/mail_autogenerated_header
  setup/mail_autogenerated_header/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1449 [16.0][IMP] mail_activity_plan: Remove warning by several names with the same label
  mail_activity_plan/models/mail_activity_plan.py
Labels: bot is merging ⏳
