Repository OCA/social, pull requests merged in 2024-07, with the labels that each got.

#1408 [15.0][FIX] mail_composer_cc_bcc: adapt to changes upstream
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, bot is merging ⏳

#1407 [16.0][FIX] mail_composer_cc_bcc: adapt to changes upstream
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, bot is merging ⏳

#1406 [16.0][FIX] mail_tracking: bounces and others
  mail_tracking/controllers/main.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_thread.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/static/src/components/message/message.xml
  mail_tracking/tests/test_mail_tracking.py
Labels: bot is merging ⏳

#1391 [16.0][FIX][REF] mail_show_follower: internal notes
  mail_show_follower/README.rst
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_partner.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/static/description/index.html
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1412 [17.0][MIG] mail_tracking_mass_mailing: Migration to 17.0
  mail_tracking_mass_mailing/README.rst
  mail_tracking_mass_mailing/__init__.py
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/da.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/el_GR.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/es_CO.po
  mail_tracking_mass_mailing/i18n/eu.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/gl.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/hr_HR.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/mail_tracking_mass_mailing.pot
  mail_tracking_mass_mailing/i18n/nb_NO.po
  mail_tracking_mass_mailing/i18n/nl.po
  mail_tracking_mass_mailing/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/pl.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/pt_BR.po
  mail_tracking_mass_mailing/i18n/ro.po
  mail_tracking_mass_mailing/i18n/ru.po
  mail_tracking_mass_mailing/i18n/sl.po
  mail_tracking_mass_mailing/i18n/tr.po
  mail_tracking_mass_mailing/models/__init__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mail_tracking_email.py
  mail_tracking_mass_mailing/models/mail_tracking_event.py
  mail_tracking_mass_mailing/models/mailing_contact.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/pyproject.toml
  mail_tracking_mass_mailing/readme/CONTRIBUTORS.md
  mail_tracking_mass_mailing/readme/DESCRIPTION.md
  mail_tracking_mass_mailing/readme/INSTALL.md
  mail_tracking_mass_mailing/readme/USAGE.md
  mail_tracking_mass_mailing/static/description/icon.png
  mail_tracking_mass_mailing/static/description/index.html
  mail_tracking_mass_mailing/tests/__init__.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
  mail_tracking_mass_mailing/views/mail_mass_mailing_view.xml
  mail_tracking_mass_mailing/views/mail_trace_view.xml
  mail_tracking_mass_mailing/views/mail_tracking_email_view.xml
  mail_tracking_mass_mailing/views/mailing_contact_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1417 [16.0][FIX] mail_tracking_mailgun: discard non Odoo events
  mail_tracking_mailgun/models/mail_tracking_email.py
  mail_tracking_mailgun/tests/test_mailgun.py
Labels: approved, bot is merging ⏳

#1399 [16.0] Replace 'Camptocamp SA' with 'Camptocamp'
  mail_autosubscribe/__manifest__.py
  mail_composer_cc_bcc/__manifest__.py
  mail_composer_cc_bcc_account/__manifest__.py
  mail_layout_preview/__manifest__.py
Labels: bot is merging ⏳

#1387 [17.0][MIG] mail_activity_done: Migration to 17.0
  mail_activity_done/README.rst
  mail_activity_done/__init__.py
  mail_activity_done/__manifest__.py
  mail_activity_done/hooks.py
  mail_activity_done/i18n/es.po
  mail_activity_done/i18n/fi.po
  mail_activity_done/i18n/fr.po
  mail_activity_done/i18n/hu.po
  mail_activity_done/i18n/it.po
  mail_activity_done/i18n/mail_activity_done.pot
  mail_activity_done/models/__init__.py
  mail_activity_done/models/mail_activity.py
  mail_activity_done/models/res_users.py
  mail_activity_done/pyproject.toml
  mail_activity_done/readme/CONTRIBUTORS.md
  mail_activity_done/readme/DESCRIPTION.md
  mail_activity_done/readme/USAGE.md
  mail_activity_done/static/description/icon.png
  mail_activity_done/static/description/index.html
  mail_activity_done/tests/__init__.py
  mail_activity_done/tests/test_mail_activity_done.py
  mail_activity_done/views/mail_activity_views.xml
Labels: approved, bot is merging ⏳

#1397 [15.0] Replace 'Camptocamp SA' with 'Camptocamp'
  mail_autosubscribe/__manifest__.py
  mail_composer_cc_bcc/__manifest__.py
  mail_layout_preview/__manifest__.py
  outgoing_email_by_model/__manifest__.py
Labels: bot is merging ⏳

#1398 [13.0] Replace 'Camptocamp SA' with 'Camptocamp'
  mail_autosubscribe/__manifest__.py
  mail_layout_preview/__manifest__.py
Labels: bot is merging ⏳

#1396 [14.0] Replace 'Camptocamp SA' with 'Camptocamp'
  mail_autosubscribe/__manifest__.py
  mail_layout_preview/__manifest__.py
  mail_notification_with_history/__manifest__.py
  mail_thread_create_nolog/__manifest__.py
Labels: bot is merging ⏳

#1312 [17.0][MIG] mail_composer_cc_bcc: Migration to 17.0
  mail_composer_cc_bcc/README.rst
  mail_composer_cc_bcc/__init__.py
  mail_composer_cc_bcc/__manifest__.py
  mail_composer_cc_bcc/i18n/es.po
  mail_composer_cc_bcc/i18n/it.po
  mail_composer_cc_bcc/i18n/mail_composer_cc_bcc.pot
  mail_composer_cc_bcc/models/__init__.py
  mail_composer_cc_bcc/models/ir_mail_server.py
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/models/mail_message.py
  mail_composer_cc_bcc/models/mail_template.py
  mail_composer_cc_bcc/models/mail_thread.py
  mail_composer_cc_bcc/models/res_company.py
  mail_composer_cc_bcc/pyproject.toml
  mail_composer_cc_bcc/readme/CONFIGURE.md
  mail_composer_cc_bcc/readme/CONTRIBUTORS.md
  mail_composer_cc_bcc/readme/CREDITS.md
  mail_composer_cc_bcc/readme/DESCRIPTION.md
  mail_composer_cc_bcc/readme/ROADMAP.md
  mail_composer_cc_bcc/readme/USAGE.md
  mail_composer_cc_bcc/static/description/icon.png
  mail_composer_cc_bcc/static/description/index.html
  mail_composer_cc_bcc/static/img/email_template_form_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_default_cc_bcc.png
  mail_composer_cc_bcc/static/img/mail_compose_message_template_cc_bcc.png
  mail_composer_cc_bcc/static/img/res_company_form_default_cc_bcc.png
  mail_composer_cc_bcc/tests/__init__.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mail_composer_cc_bcc/views/mail_mail_views.xml
  mail_composer_cc_bcc/views/mail_message_views.xml
  mail_composer_cc_bcc/views/mail_template_views.xml
  mail_composer_cc_bcc/views/res_company_views.xml
  mail_composer_cc_bcc/wizards/__init__.py
  mail_composer_cc_bcc/wizards/mail_compose_message.py
  mail_composer_cc_bcc/wizards/mail_compose_message_view.xml
  mail_composer_cc_bcc_account/README.rst
  mail_composer_cc_bcc_account/__init__.py
  mail_composer_cc_bcc_account/__manifest__.py
  mail_composer_cc_bcc_account/i18n/it.po
  mail_composer_cc_bcc_account/i18n/mail_composer_cc_bcc_account.pot
  mail_composer_cc_bcc_account/models/__init__.py
  mail_composer_cc_bcc_account/models/mail_thread.py
  mail_composer_cc_bcc_account/pyproject.toml
  mail_composer_cc_bcc_account/readme/CONFIGURE.md
  mail_composer_cc_bcc_account/readme/CONTRIBUTORS.md
  mail_composer_cc_bcc_account/readme/CREDITS.md
  mail_composer_cc_bcc_account/readme/DESCRIPTION.md
  mail_composer_cc_bcc_account/readme/USAGE.md
  mail_composer_cc_bcc_account/static/description/icon.png
  mail_composer_cc_bcc_account/static/description/index.html
  mail_composer_cc_bcc_account/static/img/email_template_form_cc_bcc.png
  mail_composer_cc_bcc_account/static/img/mail_compose_message_default_cc_bcc.png
  mail_composer_cc_bcc_account/static/img/mail_compose_message_template_cc_bcc.png
  mail_composer_cc_bcc_account/static/img/res_company_form_default_cc_bcc.png
  mail_composer_cc_bcc_account/tests/__init__.py
  mail_composer_cc_bcc_account/tests/test_mail_cc_bcc.py
  mail_composer_cc_bcc_account/wizards/__init__.py
  mail_composer_cc_bcc_account/wizards/account_move_send.py
  mail_composer_cc_bcc_account/wizards/account_move_send.xml
Labels: approved, bot is merging ⏳

#1424 [14.0] [IMP] mail_optional_follower_notification: Add default notify followers in general settings
  mail_optional_follower_notification/README.rst
  mail_optional_follower_notification/__manifest__.py
  mail_optional_follower_notification/models/__init__.py
  mail_optional_follower_notification/models/res_company.py
  mail_optional_follower_notification/models/res_config_settings.py
  mail_optional_follower_notification/readme/CONTRIBUTORS.rst
  mail_optional_follower_notification/readme/USAGE.rst
  mail_optional_follower_notification/static/description/index.html
  mail_optional_follower_notification/static/description/optional_follower_003.png
  mail_optional_follower_notification/views/res_config_settings_view.xml
  mail_optional_follower_notification/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳
