Repository OCA/social, pull requests merged in 2024-01, with the labels that each got.

#1273 [16.0][FIX] mail_composer_cc_bcc: make test work in the new year
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mass_mailing_unique/tests/test_mass_mailing_unique.py
Labels: approved, bot is merging ⏳

#1277 [15.0][FIX] mail_composer_cc_bcc: find invoice regardless of the current year
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, bot is merging ⏳

#1268 [16.0][FIX] mail_tracking debug mode t-key error
  mail_tracking/__manifest__.py
  mail_tracking/static/src/components/failed_message/failed_message.xml
Labels: approved, ready to merge, bot is merging ⏳

#1272 [16.0][FIX] mail_debrand: fix translated branding
  mail_debrand/README.rst
  mail_debrand/models/mail_mail.py
  mail_debrand/models/mail_render_mixin.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/readme/ROADMAP.rst
  mail_debrand/static/description/index.html
  mail_debrand/tests/__init__.py
  mail_debrand/tests/test_mail_debrand.py
  mail_debrand/tests/test_mail_debrand_signup.py
Labels: bot is merging ⏳

#1165 [16.0] [MIG] mail_quoted_reply
  mail_quoted_reply/README.rst
  mail_quoted_reply/__init__.py
  mail_quoted_reply/__manifest__.py
  mail_quoted_reply/i18n/ca.po
  mail_quoted_reply/i18n/es.po
  mail_quoted_reply/i18n/mail_quoted_reply.pot
  mail_quoted_reply/models/__init__.py
  mail_quoted_reply/models/mail_compose_message.py
  mail_quoted_reply/models/mail_message.py
  mail_quoted_reply/readme/CONTRIBUTORS.rst
  mail_quoted_reply/readme/DESCRIPTION.rst
  mail_quoted_reply/readme/USAGE.rst
  mail_quoted_reply/static/description/icon.png
  mail_quoted_reply/static/description/index.html
  mail_quoted_reply/static/src/models/message.esm.js
  mail_quoted_reply/static/src/models/message_action.esm.js
  mail_quoted_reply/static/src/models/message_action_list.esm.js
  mail_quoted_reply/static/src/models/message_action_view.esm.js
  mail_quoted_reply/tests/__init__.py
  mail_quoted_reply/tests/test_reply.py
  setup/mail_quoted_reply/odoo/addons/mail_quoted_reply
  setup/mail_quoted_reply/setup.py
Labels: approved, migration, bot is merging ⏳

#1162 [FIX] mail_attach_existing_attachment: fix wizard view
  mail_attach_existing_attachment/wizard/mail_compose_message_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1279 [16.0][FIX] mail_quoted_reply: Use standard paragraph element to enter text
  mail_quoted_reply/models/mail_message.py
Labels: approved, bot is merging ⏳

#961 [15.0][ADD] base_user_signature
  base_user_signature/README.rst
  base_user_signature/__init__.py
  base_user_signature/__manifest__.py
  base_user_signature/i18n/base_user_signature.pot
  base_user_signature/i18n/fr.po
  base_user_signature/models/__init__.py
  base_user_signature/models/res_users.py
  base_user_signature/readme/CONTRIBUTORS.rst
  base_user_signature/readme/DESCRIPTION.rst
  base_user_signature/readme/USAGE.rst
  base_user_signature/static/description/index.html
  base_user_signature/views/res_users_view.xml
  setup/base_user_signature/odoo/addons/base_user_signature
  setup/base_user_signature/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#881 [15.0][MIG] mail_drop_target
  mail_drop_target/README.rst
  mail_drop_target/__init__.py
  mail_drop_target/__manifest__.py
  mail_drop_target/i18n/mail_drop_target.pot
  mail_drop_target/models/__init__.py
  mail_drop_target/models/mail_thread.py
  mail_drop_target/models/res_config_settings.py
  mail_drop_target/readme/CONFIGURATION.rst
  mail_drop_target/readme/CONTRIBUTORS.rst
  mail_drop_target/readme/DESCRIPTION.rst
  mail_drop_target/readme/ROADMAP.rst
  mail_drop_target/readme/USAGE.rst
  mail_drop_target/static/description/icon.png
  mail_drop_target/static/description/index.html
  mail_drop_target/static/lib/base64js.min.js
  mail_drop_target/static/src/css/mail_drop_target.css
  mail_drop_target/static/src/js/mail_drop_target.esm.js
  mail_drop_target/static/src/xml/chatter.xml
  mail_drop_target/tests/__init__.py
  mail_drop_target/tests/sample.eml
  mail_drop_target/tests/sample.msg
  mail_drop_target/tests/test_mail_drop_target.py
  mail_drop_target/views/res_config_settings_views.xml
  requirements.txt
  setup/mail_drop_target/odoo/addons/mail_drop_target
  setup/mail_drop_target/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, stale

#1270 [17.0] [MIG] mail_partner_forwarding
  mail_partner_forwarding/README.rst
  mail_partner_forwarding/__init__.py
  mail_partner_forwarding/__manifest__.py
  mail_partner_forwarding/i18n/mail_partner_forwarding.pot
  mail_partner_forwarding/models/__init__.py
  mail_partner_forwarding/models/mail_thread.py
  mail_partner_forwarding/models/res_partner.py
  mail_partner_forwarding/models/res_user.py
  mail_partner_forwarding/pyproject.toml
  mail_partner_forwarding/readme/CONTRIBUTORS.md
  mail_partner_forwarding/readme/DESCRIPTION.md
  mail_partner_forwarding/readme/HISTORY.md
  mail_partner_forwarding/readme/USAGE.md
  mail_partner_forwarding/static/description/icon.png
  mail_partner_forwarding/static/description/index.html
  mail_partner_forwarding/tests/__init__.py
  mail_partner_forwarding/tests/models/__init__.py
  mail_partner_forwarding/tests/models/fake_order.py
  mail_partner_forwarding/tests/test_mail_forwarding.py
  mail_partner_forwarding/views/res_partner_views.xml
  mail_partner_forwarding/views/res_user_views.xml
  test-requirements.txt
Labels: bot is merging ⏳
