Repository OCA/social, pull requests merged in 2024-11, with the labels that each got.

#1463 [18.0][MIG] mail_notification_with_history: Migration to 18.0
  mail_notification_with_history/README.rst
  mail_notification_with_history/__init__.py
  mail_notification_with_history/__manifest__.py
  mail_notification_with_history/data/mail_data.xml
  mail_notification_with_history/i18n/es.po
  mail_notification_with_history/i18n/mail_notification_with_history.pot
  mail_notification_with_history/models/__init__.py
  mail_notification_with_history/models/mail_message.py
  mail_notification_with_history/models/mail_thread.py
  mail_notification_with_history/pyproject.toml
  mail_notification_with_history/readme/CONTRIBUTORS.md
  mail_notification_with_history/readme/CREDITS.md
  mail_notification_with_history/readme/DESCRIPTION.md
  mail_notification_with_history/readme/INSTALL.md
  mail_notification_with_history/static/description/icon.png
  mail_notification_with_history/static/description/index.html
  mail_notification_with_history/tests/__init__.py
  mail_notification_with_history/tests/test_mail_notification_with_history.py
Labels: approved, ready to merge, bot is merging ⏳

#1486 [16.0][FW][FIX] mail_show_follower: Use company from the document to render messages correctly + proper lang handle
  mail_show_follower/models/mail_mail.py
Labels: approved, bot is merging ⏳

#1293 [15.0][IMP] mail_composer_cc_bcc: filter out partner with no email address and set "" for partner with no name
  mail_composer_cc_bcc/models/mail_mail.py
Labels: approved, bot is merging ⏳, stale

#1487 [15.0][ADD] mail_save_as_template_security
  mail_save_as_template_security/README.rst
  mail_save_as_template_security/__init__.py
  mail_save_as_template_security/__manifest__.py
  mail_save_as_template_security/readme/CONFIGURE.md
  mail_save_as_template_security/readme/CONTRIBUTORS.md
  mail_save_as_template_security/readme/DESCRIPTION.md
  mail_save_as_template_security/readme/USAGE.md
  mail_save_as_template_security/security/mail_save_as_template_security.xml
  mail_save_as_template_security/static/description/icon.png
  mail_save_as_template_security/static/description/icon.svg
  mail_save_as_template_security/static/description/index.html
  mail_save_as_template_security/tests/__init__.py
  mail_save_as_template_security/tests/test_mail_save_as_template_security.py
  mail_save_as_template_security/wizard/mail_compose_message_view.xml
  setup/mail_save_as_template_security/odoo/addons/mail_save_as_template_security
  setup/mail_save_as_template_security/setup.py
Labels: approved, bot is merging ⏳

#1491 [15.0][FIX] mail_show_follower: More models to exclude
  mail_show_follower/data/config_parameter_data.xml
Labels: approved, bot is merging ⏳

#1505 [16.0][FIX] mail_composer_cc_bcc: adapt to changes upstream
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: bot is merging ⏳

#1500 [16.0][IMP] mail_show_follower: Add an option to exclude specific models from the CC note
  mail_show_follower/README.rst
  mail_show_follower/__manifest__.py
  mail_show_follower/data/config_parameter_data.xml
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
Labels: bot is merging ⏳

#1468 [17.0][FIX] mail_activity_board: hide button if has no activities
  mail_activity_board/static/src/components/chatter/chatter.xml
Labels: approved, ready to merge, bot is merging ⏳

#1442 [17.0] port mail_autogenerated_header
  mail_autogenerated_header/README.rst
  mail_autogenerated_header/__init__.py
  mail_autogenerated_header/__manifest__.py
  mail_autogenerated_header/i18n/mail_autogenerated_header.pot
  mail_autogenerated_header/models/__init__.py
  mail_autogenerated_header/models/ir_mail_server.py
  mail_autogenerated_header/models/mail_thread.py
  mail_autogenerated_header/pyproject.toml
  mail_autogenerated_header/readme/CONTRIBUTORS.md
  mail_autogenerated_header/readme/DESCRIPTION.md
  mail_autogenerated_header/readme/USAGE.md
  mail_autogenerated_header/readme/newsfragments/.gitkeep
  mail_autogenerated_header/static/description/icon.png
  mail_autogenerated_header/static/description/index.html
  mail_autogenerated_header/tests/__init__.py
  mail_autogenerated_header/tests/test_mail_autogenerated_header.py
Labels: approved, ready to merge, bot is merging ⏳

#1475 [17.0][FW] Port missing commits
  .oca/oca-port/blacklist/mail_tracking.json
  mail_tracking/__manifest__.py
  mail_tracking/models/__init__.py
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_thread.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/res_company.py
  mail_tracking/models/res_config_settings.py
  mail_tracking/static/description/index.html
  mail_tracking/tests/__init__.py
  mail_tracking/tests/test_gc_mail_tracking_email.py
  mail_tracking/tests/test_mail_tracking.py
  mail_tracking/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#1331 [16.0][IMP] mail_tracking: display internal notifications status
  mail_tracking/models/mail_message.py
  mail_tracking/readme/CONTRIBUTORS.rst
  mail_tracking/readme/USAGE.rst
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, stale
