Repository OCA/social, pull requests merged in 2024-10, with the labels that each got.

#1423 [ADD] New module mail_discuss_security to hide 'Discuss' Application by default
  mail_discuss_security/README.rst
  mail_discuss_security/__init__.py
  mail_discuss_security/__manifest__.py
  mail_discuss_security/i18n/fr.po
  mail_discuss_security/readme/CONTRIBUTORS.rst
  mail_discuss_security/readme/DESCRIPTION.rst
  mail_discuss_security/security/res_groups.xml
  mail_discuss_security/static/description/index.html
  mail_discuss_security/static/description/menu_list.png
  mail_discuss_security/static/description/systray.png
  mail_discuss_security/static/src/js/systray_service.esm.js
  mail_discuss_security/views/menu.xml
  setup/mail_discuss_security/odoo/addons/mail_discuss_security
  setup/mail_discuss_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1453 [15.0][ADD] mail_print: new module to print messages from chatter
  mail_print/README.rst
  mail_print/__init__.py
  mail_print/__manifest__.py
  mail_print/data/report_paperformat_data.xml
  mail_print/i18n/es.po
  mail_print/i18n/mail_print.pot
  mail_print/readme/DESCRIPTION.rst
  mail_print/readme/USAGE.rst
  mail_print/reports/report_mail_message.xml
  mail_print/reports/reports.xml
  mail_print/static/description/index.html
  mail_print/static/src/components/message_action_list/message_action_list.xml
  mail_print/static/src/components/print_message/print_message.esm.js
  mail_print/static/src/components/print_message/print_message.xml
  mail_print/static/tests/tours/mail_print.esm.js
  mail_print/tests/__init__.py
  mail_print/tests/test_mail_print.py
  setup/mail_print/odoo/addons/mail_print
  setup/mail_print/setup.py
Labels: approved, bot is merging ⏳

#1455 [15.0][ADD] mail_forward: new module to forward messages from the chatter
  mail_forward/README.rst
  mail_forward/__init__.py
  mail_forward/__manifest__.py
  mail_forward/i18n/es.po
  mail_forward/i18n/mail_forward.pot
  mail_forward/models/__init__.py
  mail_forward/models/mail_message.py
  mail_forward/models/mail_thread.py
  mail_forward/readme/CONTRIBUTORS.rst
  mail_forward/readme/DESCRIPTION.rst
  mail_forward/readme/USAGE.rst
  mail_forward/static/description/index.html
  mail_forward/static/src/components/forward_message/forward_message.esm.js
  mail_forward/static/src/components/forward_message/forward_message.xml
  mail_forward/static/src/components/message_action_list/message_action_list.xml
  mail_forward/static/tests/tours/mail_forward.esm.js
  mail_forward/tests/__init__.py
  mail_forward/tests/test_mail_forward.py
  mail_forward/wizards/__init__.py
  mail_forward/wizards/mail_compose_message.py
  mail_forward/wizards/mail_compose_message_view.xml
  setup/mail_forward/odoo/addons/mail_forward
  setup/mail_forward/setup.py
Labels: approved, merged 🎉

#1457 [15.0][FIX] mail_print,mail_forward: prevent errors during the test tour when web_responsive is installed.
  mail_forward/static/tests/tours/mail_forward.esm.js
  mail_print/static/tests/tours/mail_print.esm.js
Labels: approved, bot is merging ⏳

#1454 [16.0][MIG] mail_notification_custom_subject
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es.po
  mail_notification_custom_subject/i18n/es_ES.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.rst
  mail_notification_custom_subject/readme/CONTRIBUTORS.rst
  mail_notification_custom_subject/readme/DESCRIPTION.rst
  mail_notification_custom_subject/readme/USAGE.rst
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/icon.png
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
  setup/mail_notification_custom_subject/odoo/addons/mail_notification_custom_subject
  setup/mail_notification_custom_subject/setup.py
Labels: approved, bot is merging ⏳

#1464 [15.0][FIX] mail_show_follower: Use company from the document to render messages correctly
  mail_show_follower/README.rst
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_partner.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/static/description/index.html
Labels: approved, bot is merging ⏳

#1473 [15.0][IMP] mail_print: Allow printing messages from incoming mail
  mail_print/static/src/components/message_action_list/message_action_list.xml
Labels: approved, bot is merging ⏳

#1460 [17.0][ADD]mute_notification_user_autosubscribe: Do not send notification to users autosubscribed through user_id field
  mute_notification_user_autosubscribe/README.rst
  mute_notification_user_autosubscribe/__init__.py
  mute_notification_user_autosubscribe/__manifest__.py
  mute_notification_user_autosubscribe/data/mail_message_subtype_data.xml
  mute_notification_user_autosubscribe/models/__init__.py
  mute_notification_user_autosubscribe/models/mail_thread.py
  mute_notification_user_autosubscribe/models/res_users.py
  mute_notification_user_autosubscribe/models/user_autosubscribe_mute.py
  mute_notification_user_autosubscribe/pyproject.toml
  mute_notification_user_autosubscribe/readme/CONFIGURE.md
  mute_notification_user_autosubscribe/readme/CONTRIBUTORS.md
  mute_notification_user_autosubscribe/readme/DESCRIPTION.md
  mute_notification_user_autosubscribe/readme/ROADMAP.md
  mute_notification_user_autosubscribe/readme/USAGE.md
  mute_notification_user_autosubscribe/security/ir.model.access.csv
  mute_notification_user_autosubscribe/static/description/icon.png
  mute_notification_user_autosubscribe/static/description/index.html
  mute_notification_user_autosubscribe/tests/__init__.py
  mute_notification_user_autosubscribe/tests/test_mute_user_sutosubscribe.py
  mute_notification_user_autosubscribe/views/user_autosubscribe_mute_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1481 [18.0][MIG] mail_thread_create_nolog: Migration to 18.0
  mail_thread_create_nolog/README.rst
  mail_thread_create_nolog/__init__.py
  mail_thread_create_nolog/__manifest__.py
  mail_thread_create_nolog/controllers/__init__.py
  mail_thread_create_nolog/controllers/thread.py
  mail_thread_create_nolog/i18n/es.po
  mail_thread_create_nolog/i18n/mail_thread_create_nolog.pot
  mail_thread_create_nolog/models/__init__.py
  mail_thread_create_nolog/models/mail_message.py
  mail_thread_create_nolog/models/mail_thread.py
  mail_thread_create_nolog/pyproject.toml
  mail_thread_create_nolog/readme/CONTRIBUTORS.md
  mail_thread_create_nolog/readme/CREDITS.md
  mail_thread_create_nolog/readme/DESCRIPTION.md
  mail_thread_create_nolog/readme/ROADMAP.md
  mail_thread_create_nolog/static/description/icon.png
  mail_thread_create_nolog/static/description/index.html
  mail_thread_create_nolog/tests/__init__.py
  mail_thread_create_nolog/tests/test_create_nolog.py
Labels: bot is merging ⏳

#1483 [15.0][IMP] mail_show_follower: Add an option to exclude specific models from the CC note.
  mail_show_follower/README.rst
  mail_show_follower/__manifest__.py
  mail_show_follower/data/config_parameter_data.xml
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
Labels: approved, bot is merging ⏳
