Repository OCA/social, pull requests merged in 2024-06, with the labels that each got.

#1380 [FIX] mail_post_defer: notify from non-thread models and to author
  mail_post_defer/models/mail_message_schedule.py
  mail_post_defer/models/mail_thread.py
  mail_post_defer/tests/test_mail.py
Labels: bug, bot is merging ⏳

#1382 [FIX] mail_post_defer: recover "view $model" button
  mail_post_defer/models/mail_message_schedule.py
  mail_post_defer/tests/test_mail.py
Labels: bug, bot is merging ⏳

#1205 [16.0][FIX] base_search_mail_content: Allow messsage_content search only for internal users
  base_search_mail_content/README.rst
  base_search_mail_content/models/mail_thread.py
  base_search_mail_content/readme/ROADMAP.rst
  base_search_mail_content/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1379 [15.0][ADD] mail_no_user_assign_notification: New module
  mail_no_user_assign_notification/README.rst
  mail_no_user_assign_notification/__init__.py
  mail_no_user_assign_notification/__manifest__.py
  mail_no_user_assign_notification/data/ir_config_parameter.xml
  mail_no_user_assign_notification/i18n/es.po
  mail_no_user_assign_notification/i18n/mail_no_user_assign_notification.pot
  mail_no_user_assign_notification/models/__init__.py
  mail_no_user_assign_notification/models/mail_thread.py
  mail_no_user_assign_notification/readme/CONFIGURE.rst
  mail_no_user_assign_notification/readme/CONTRIBUTORS.rst
  mail_no_user_assign_notification/readme/DESCRIPTION.rst
  mail_no_user_assign_notification/readme/ROADMAP.rst
  mail_no_user_assign_notification/readme/USAGE.rst
  mail_no_user_assign_notification/static/description/icon.png
  mail_no_user_assign_notification/static/description/index.html
  mail_no_user_assign_notification/tests/__init__.py
  mail_no_user_assign_notification/tests/test_mail_no_user_assign_notification.py
  setup/mail_no_user_assign_notification/odoo/addons/mail_no_user_assign_notification
  setup/mail_no_user_assign_notification/setup.py
Labels: approved, bot is merging ⏳

#1394 [16.0][FIX] mail_gateway_telegram: Description has been deprecated
  mail_gateway_telegram/models/mail_gateway_telegram.py
Labels: bot is merging ⏳

#1386 [16.0][FIX] mail_activity_done: Remove broken and apparently unused js file
  mail_activity_done/__manifest__.py
  mail_activity_done/static/src/js/mail_activity.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#1365 [16.0][MIG] base_user_signature
  base_user_signature/README.rst
  base_user_signature/__init__.py
  base_user_signature/__manifest__.py
  base_user_signature/i18n/base_user_signature.pot
  base_user_signature/i18n/fr.po
  base_user_signature/models/__init__.py
  base_user_signature/models/res_users.py
  base_user_signature/readme/CONTRIBUTORS.rst
  base_user_signature/readme/DESCRIPTION.rst
  base_user_signature/readme/USAGE.rst
  base_user_signature/static/description/icon.png
  base_user_signature/static/description/index.html
  base_user_signature/views/res_users_view.xml
  setup/base_user_signature/odoo/addons/base_user_signature
  setup/base_user_signature/setup.py
Labels: approved, bot is merging ⏳
