Repository OCA/social, pull requests merged in 2025-02, with the labels that each got.

#1548 [17.0][IMP] mail_notification_custom_subject: Do not replace the subject if it is already defined + add inside replace option
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/readme/CONFIGURE.md
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
Labels: bot is merging ⏳

#1571 [16.0][FIX] mass_mailing_custom_unsubscribe: portal user permissions
  mail_composer_cc_bcc/models/mail_mail.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
  mass_mailing_custom_unsubscribe/security/ir.model.access.csv
  mass_mailing_custom_unsubscribe/static/src/js/contact.tour.esm.js
  mass_mailing_custom_unsubscribe/static/src/js/partner.tour.esm.js
Labels: approved, bot is merging ⏳

#1278 [14.0][ADD] email_template_configurator
  email_template_configurator/__init__.py
  email_template_configurator/__manifest__.py
  email_template_configurator/models/__init__.py
  email_template_configurator/models/email_template_placeholder.py
  email_template_configurator/models/mail_template.py
  email_template_configurator/readme/CONFIGURATION.rst
  email_template_configurator/readme/CONTRIBUTORS.rst
  email_template_configurator/readme/DESCRIPTION.rst
  email_template_configurator/readme/USAGE.rst
  email_template_configurator/security/email_template_placeholder.xml
  email_template_configurator/security/groups.xml
  email_template_configurator/tests/__init__.py
  email_template_configurator/tests/test_configurator.py
  email_template_configurator/views/email_template_placeholder.xml
  email_template_configurator/views/mail_template.xml
  setup/email_template_configurator/odoo/addons/email_template_configurator
  setup/email_template_configurator/setup.py
Labels: bot is merging ⏳

#1569 [17.0][FIX] mail_activity_team: singleton in _compute_activity_team_id()
  mail_activity_team/readme/CONTRIBUTORS.md
  mail_activity_team/wizard/mail_activity_schedule.py
Labels: approved, ready to merge, bot is merging ⏳

#1588 [17.0][FIX] mail_forward: Avoid error when forwarding a message while readireading the view
  mail_forward/models/mail_message.py
  mail_forward/tests/test_mail_forward.py
Labels: bot is merging ⏳

#1589 [15.0][FIX] mail_forward: Avoid error when forwarding a message while reading the view
  mail_forward/models/mail_message.py
  mail_forward/tests/test_mail_forward.py
Labels: bot is merging ⏳

#1582 [15.0] [IMP] mail_optional_follower_notification: default notify followers
  mail_optional_follower_notification/README.rst
  mail_optional_follower_notification/__manifest__.py
  mail_optional_follower_notification/models/__init__.py
  mail_optional_follower_notification/models/res_company.py
  mail_optional_follower_notification/models/res_config_settings.py
  mail_optional_follower_notification/readme/CONTRIBUTORS.rst
  mail_optional_follower_notification/readme/USAGE.rst
  mail_optional_follower_notification/static/description/index.html
  mail_optional_follower_notification/static/description/optional_follower_003.png
  mail_optional_follower_notification/views/res_config_settings_view.xml
  mail_optional_follower_notification/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳

#1570 [17.0][MIG] mail_show_follower: Migration to 17.0
  mail_show_follower/README.rst
  mail_show_follower/__init__.py
  mail_show_follower/__manifest__.py
  mail_show_follower/data/config_parameter_data.xml
  mail_show_follower/i18n/es.po
  mail_show_follower/i18n/fr.po
  mail_show_follower/i18n/it.po
  mail_show_follower/i18n/mail_show_follower.pot
  mail_show_follower/i18n/pt_BR.po
  mail_show_follower/models/__init__.py
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/models/res_partner.py
  mail_show_follower/models/res_users.py
  mail_show_follower/pyproject.toml
  mail_show_follower/readme/CONFIGURE.md
  mail_show_follower/readme/CONTRIBUTORS.md
  mail_show_follower/readme/DESCRIPTION.md
  mail_show_follower/readme/USAGE.md
  mail_show_follower/static/description/icon.png
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
  mail_show_follower/views/res_users.xml
Labels: approved, bot is merging ⏳

#1583 [16.0] [IMP] mail_optional_follower_notification: default notify followers
  mail_optional_follower_notification/README.rst
  mail_optional_follower_notification/__manifest__.py
  mail_optional_follower_notification/models/__init__.py
  mail_optional_follower_notification/models/res_company.py
  mail_optional_follower_notification/models/res_config_settings.py
  mail_optional_follower_notification/readme/CONTRIBUTORS.rst
  mail_optional_follower_notification/readme/USAGE.rst
  mail_optional_follower_notification/static/description/index.html
  mail_optional_follower_notification/static/description/optional_follower_003.png
  mail_optional_follower_notification/views/res_config_settings_view.xml
  mail_optional_follower_notification/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳

#1584 [17.0] [IMP] mail_optional_follower_notification: default notify followers
  mail_optional_follower_notification/README.rst
  mail_optional_follower_notification/__manifest__.py
  mail_optional_follower_notification/models/__init__.py
  mail_optional_follower_notification/models/res_company.py
  mail_optional_follower_notification/models/res_config_settings.py
  mail_optional_follower_notification/readme/CONTRIBUTORS.md
  mail_optional_follower_notification/readme/USAGE.md
  mail_optional_follower_notification/static/description/index.html
  mail_optional_follower_notification/static/description/optional_follower_003.png
  mail_optional_follower_notification/views/res_config_settings_view.xml
  mail_optional_follower_notification/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳

#1577 [18.0][MIG] mail_notification_custom_subject: Migration to 18.0
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__init__.py
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/i18n/es.po
  mail_notification_custom_subject/i18n/it.po
  mail_notification_custom_subject/i18n/mail_notification_custom_subject.pot
  mail_notification_custom_subject/models/__init__.py
  mail_notification_custom_subject/models/mail_message_custom_subject.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/pyproject.toml
  mail_notification_custom_subject/readme/CONFIGURE.md
  mail_notification_custom_subject/readme/CONTRIBUTORS.md
  mail_notification_custom_subject/readme/DESCRIPTION.md
  mail_notification_custom_subject/readme/USAGE.md
  mail_notification_custom_subject/security/ir.model.access.csv
  mail_notification_custom_subject/static/description/icon.png
  mail_notification_custom_subject/static/description/index.html
  mail_notification_custom_subject/tests/__init__.py
  mail_notification_custom_subject/tests/test_mail_notification_custom_subject.py
  mail_notification_custom_subject/views/mail_notification_custom_subject_views.xml
Labels: approved, bot is merging ⏳

#1595 [17.0][FIX] mail_debrand: Avoid odoo.sh links removal (url like my-customer.odoo.com)
  mail_debrand/models/mail_render_mixin.py
Labels: bot is merging ⏳

#1578 [17.0] [ADD] mail_disable_follower_notification
  mail_disable_follower_notification/README.rst
  mail_disable_follower_notification/__init__.py
  mail_disable_follower_notification/__manifest__.py
  mail_disable_follower_notification/pyproject.toml
  mail_disable_follower_notification/readme/CONTRIBUTORS.md
  mail_disable_follower_notification/readme/DESCRIPTION.md
  mail_disable_follower_notification/readme/USAGE.md
  mail_disable_follower_notification/static/description/icon.png
  mail_disable_follower_notification/static/description/icon.svg
  mail_disable_follower_notification/static/description/index.html
  mail_disable_follower_notification/wizards/__init__.py
  mail_disable_follower_notification/wizards/mail_wizard_invite.py
Labels: approved, ready to merge, bot is merging ⏳

#1599 [17.0][ADD] mail_activity_cancel_tracking: New module
  mail_activity_cancel_tracking/README.rst
  mail_activity_cancel_tracking/__init__.py
  mail_activity_cancel_tracking/__manifest__.py
  mail_activity_cancel_tracking/data/mail_template_data.xml
  mail_activity_cancel_tracking/i18n/es.po
  mail_activity_cancel_tracking/i18n/mail_activity_cancel_tracking.pot
  mail_activity_cancel_tracking/models/__init__.py
  mail_activity_cancel_tracking/models/mail_activity.py
  mail_activity_cancel_tracking/pyproject.toml
  mail_activity_cancel_tracking/readme/CONTRIBUTORS.md
  mail_activity_cancel_tracking/readme/DESCRIPTION.md
  mail_activity_cancel_tracking/readme/USAGE.md
  mail_activity_cancel_tracking/static/description/icon.png
  mail_activity_cancel_tracking/static/description/index.html
  mail_activity_cancel_tracking/static/tests/tours/mail_activity_cancel_tracking.esm.js
  mail_activity_cancel_tracking/tests/__init__.py
  mail_activity_cancel_tracking/tests/test_mail_activity_cancel_tracking.py
Labels: approved, bot is merging ⏳

#1597 [16.0][MIG] mail_activity_unlink_log: Migration to 16.0
  mail_activity_unlink_log/README.rst
  mail_activity_unlink_log/__init__.py
  mail_activity_unlink_log/__manifest__.py
  mail_activity_unlink_log/data/unlink_message.xml
  mail_activity_unlink_log/i18n/es.po
  mail_activity_unlink_log/i18n/it.po
  mail_activity_unlink_log/i18n/mail_activity_unlink_log.pot
  mail_activity_unlink_log/models/__init__.py
  mail_activity_unlink_log/models/mail_activity.py
  mail_activity_unlink_log/readme/CONTRIBUTORS.rst
  mail_activity_unlink_log/readme/DESCRIPTION.rst
  mail_activity_unlink_log/static/description/icon.png
  mail_activity_unlink_log/static/description/index.html
  mail_activity_unlink_log/tests/__init__.py
  mail_activity_unlink_log/tests/test_activity_unlink.py
  setup/mail_activity_unlink_log/odoo/addons/mail_activity_unlink_log
  setup/mail_activity_unlink_log/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1602 [17.0][OU-ADD] mail_activity_cancel_tracking: Remove noupdate=1 records from mail_activity_unlink_log
  mail_activity_cancel_tracking/migrations/17.0.1.0.0/post-migration.py
Labels: approved

#1601 [17.0][MIG] mail_no_user_assign_notification: Migration to version 17.0
  mail_no_user_assign_notification/README.rst
  mail_no_user_assign_notification/__init__.py
  mail_no_user_assign_notification/__manifest__.py
  mail_no_user_assign_notification/data/ir_config_parameter.xml
  mail_no_user_assign_notification/i18n/es.po
  mail_no_user_assign_notification/i18n/mail_no_user_assign_notification.pot
  mail_no_user_assign_notification/models/__init__.py
  mail_no_user_assign_notification/models/mail_thread.py
  mail_no_user_assign_notification/pyproject.toml
  mail_no_user_assign_notification/readme/CONFIGURE.md
  mail_no_user_assign_notification/readme/CONTRIBUTORS.md
  mail_no_user_assign_notification/readme/DESCRIPTION.md
  mail_no_user_assign_notification/readme/ROADMAP.md
  mail_no_user_assign_notification/readme/USAGE.md
  mail_no_user_assign_notification/static/description/icon.png
  mail_no_user_assign_notification/static/description/index.html
  mail_no_user_assign_notification/tests/__init__.py
  mail_no_user_assign_notification/tests/test_mail_no_user_assign_notification.py
Labels: bot is merging ⏳

#1594 [IMP] mail_activity_team: Upgrade module to Beta
  mail_activity_team/README.rst
  mail_activity_team/__manifest__.py
  mail_activity_team/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1522 [16.0][FIX] mail_activity_board: add no_open to avoid accessing the record and using the open_origin function instead.
  mail_activity_board/views/mail_activity_view.xml
Labels: approved, bot is merging ⏳

#1469 [16.0][IMP] mail_activity_team: Add responsible as activity team leader if exists on server actions
  mail_activity_team/models/ir_actions_server.py
  mail_activity_team/tests/test_mail_activity_team.py
Labels: approved, bot is merging ⏳
