Repository OCA/social, pull requests merged in 2025-01, with the labels that each got.

#1497 [16.0][IMP] mail_gateway_whatsapp: Add support for WhatsApp templates
  mail_gateway/models/mail_gateway.py
  mail_gateway_telegram/tests/test_mail_gateway_telegram.py
  mail_gateway_whatsapp/README.rst
  mail_gateway_whatsapp/__init__.py
  mail_gateway_whatsapp/__manifest__.py
  mail_gateway_whatsapp/models/__init__.py
  mail_gateway_whatsapp/models/mail_gateway.py
  mail_gateway_whatsapp/models/mail_gateway_whatsapp.py
  mail_gateway_whatsapp/models/mail_whatsapp_template.py
  mail_gateway_whatsapp/readme/CONFIGURE.rst
  mail_gateway_whatsapp/readme/CONTRIBUTORS.rst
  mail_gateway_whatsapp/readme/ROADMAP.rst
  mail_gateway_whatsapp/security/ir.model.access.csv
  mail_gateway_whatsapp/security/security.xml
  mail_gateway_whatsapp/static/description/index.html
  mail_gateway_whatsapp/tests/__init__.py
  mail_gateway_whatsapp/tests/test_mail_gateway_whatsapp.py
  mail_gateway_whatsapp/tests/test_mail_whatsapp_template.py
  mail_gateway_whatsapp/tools/__init__.py
  mail_gateway_whatsapp/tools/const.py
  mail_gateway_whatsapp/views/mail_gateway.xml
  mail_gateway_whatsapp/views/mail_whatsapp_template_views.xml
  mail_gateway_whatsapp/wizards/__init__.py
  mail_gateway_whatsapp/wizards/mail_compose_gateway_message.py
  mail_gateway_whatsapp/wizards/mail_compose_gateway_message.xml
  mail_gateway_whatsapp/wizards/whatsapp_composer.py
  mail_gateway_whatsapp/wizards/whatsapp_composer.xml
Labels: approved, bot is merging ⏳

#1474 [17.0][REF] mail_activity_team: use mail.activity.schedule wizard
  mail_activity_team/README.rst
  mail_activity_team/__init__.py
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/readme/CONTRIBUTORS.md
  mail_activity_team/static/description/index.html
  mail_activity_team/static/src/core/web/activity.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/wizard/__init__.py
  mail_activity_team/wizard/mail_activity_schedule.py
  mail_activity_team/wizard/mail_activity_schedule.xml
Labels: approved, bot is merging ⏳

#1532 [17.0][MIG] mail_print: Migration to version 17.0
  mail_print/README.rst
  mail_print/__init__.py
  mail_print/__manifest__.py
  mail_print/data/report_paperformat_data.xml
  mail_print/i18n/es.po
  mail_print/i18n/mail_print.pot
  mail_print/pyproject.toml
  mail_print/readme/DESCRIPTION.md
  mail_print/readme/USAGE.md
  mail_print/reports/report_mail_message.xml
  mail_print/reports/reports.xml
  mail_print/static/description/icon.png
  mail_print/static/description/index.html
  mail_print/static/src/components/print_message/print_message.esm.js
  mail_print/static/src/components/print_message/print_message.xml
  mail_print/static/src/core/common/message_actions.esm.js
  mail_print/static/tests/tours/mail_print.esm.js
  mail_print/tests/__init__.py
  mail_print/tests/test_mail_print.py
Labels: approved, bot is merging ⏳

#1550 [17.0][FIX] mail_tracking: remove deprecation warning
  mail_tracking/models/mail_mail.py
  mail_tracking/models/mail_tracking_email.py
  mail_tracking/models/mail_tracking_event.py
Labels: approved, bot is merging ⏳

#1536 [17.0][MIG] mail_forward: Migration to version 17.0
  mail_forward/README.rst
  mail_forward/__init__.py
  mail_forward/__manifest__.py
  mail_forward/i18n/es.po
  mail_forward/i18n/mail_forward.pot
  mail_forward/models/__init__.py
  mail_forward/models/mail_message.py
  mail_forward/models/mail_thread.py
  mail_forward/pyproject.toml
  mail_forward/readme/CONTRIBUTORS.md
  mail_forward/readme/DESCRIPTION.md
  mail_forward/readme/USAGE.md
  mail_forward/static/description/icon.png
  mail_forward/static/description/index.html
  mail_forward/static/src/components/forward_message/forward_message.esm.js
  mail_forward/static/src/components/forward_message/forward_message.xml
  mail_forward/static/src/core/common/message.xml
  mail_forward/static/src/core/common/message_actions.esm.js
  mail_forward/static/tests/tours/mail_forward.esm.js
  mail_forward/tests/__init__.py
  mail_forward/tests/test_mail_forward.py
  mail_forward/wizards/__init__.py
  mail_forward/wizards/mail_compose_message.py
  mail_forward/wizards/mail_compose_message_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1556 [17.0][FIX] mail_forward: Render message actions correctly with callComponent
  mail_forward/static/src/core/common/message.xml
  mail_forward/static/src/core/common/message_actions.esm.js
Labels: approved, bot is merging ⏳

#1450 [17.0][FIX] mail_composer_cc_bcc_account: use _get_partner_ids_from_mail method
  mail_composer_cc_bcc_account/wizards/account_move_send.py
Labels: approved

#1557 [17.0][IMP] mail_forward: Add option to forward a message to another thread
  mail_forward/README.rst
  mail_forward/__manifest__.py
  mail_forward/i18n/es.po
  mail_forward/i18n/mail_forward.pot
  mail_forward/models/__init__.py
  mail_forward/models/ir_model.py
  mail_forward/models/mail_message.py
  mail_forward/models/mail_thread.py
  mail_forward/readme/CONFIGURE.md
  mail_forward/readme/DESCRIPTION.md
  mail_forward/readme/USAGE.md
  mail_forward/static/description/index.html
  mail_forward/tests/test_mail_forward.py
  mail_forward/views/ir_model_views.xml
  mail_forward/wizards/mail_compose_message.py
  mail_forward/wizards/mail_compose_message_view.xml
Labels: approved, bot is merging ⏳
