Repository OCA/social, pull requests merged in 2025-05, with the labels that each got.

#1527 [FIX] mail_send_copy: work with existing BCC+adding tests
  mail_send_copy/models/ir_mail_server.py
  mail_send_copy/static/description/index.html
  mail_send_copy/tests/__init__.py
  mail_send_copy/tests/test_mail_send_copy.py
Labels: approved, ready to merge, bot is merging ⏳

#1636 [16.0][FIX] mass_mailing_list_dynamic: prevent put in queue with errors
  mass_mailing_list_dynamic/models/mailing.py
  mass_mailing_list_dynamic/tests/test_dynamic_lists.py
Labels: approved, ready to merge, bot is merging ⏳

#1646 [17.0][FIX] mail_notification_custom_subject: Public user can not post messages in portal for models that have a customised subject defined
  mail_notification_custom_subject/README.rst
  mail_notification_custom_subject/__manifest__.py
  mail_notification_custom_subject/models/mail_thread.py
  mail_notification_custom_subject/static/description/index.html
Labels: approved, bot is merging ⏳

#1648 [16.0][FIX] mail_composer_cc_bcc: don't break tests on changed upstream, on warn
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, bot is merging ⏳

#1523 [FIX] mail_composer_cc_bcc: fix test scripts
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: bot is merging ⏳

#1610 [17.0][FIX] mail_activity_cancel_tracking: Allow to delete a record (with activities)
  mail_activity_cancel_tracking/models/mail_activity.py
  mail_activity_cancel_tracking/tests/test_mail_activity_cancel_tracking.py
Labels: approved, bot is merging ⏳

#1651 [FIX] Email normalization
  mail_composer_cc_bcc/models/mail_mail.py
Labels: approved, bot is merging ⏳

#1653 [16.0][FIX] mass_mailing_unique: constraint message
  mass_mailing_unique/models/mailing_contact.py
Labels: approved, bot is merging ⏳

#1644 [16.0][FIX] mail_compose_cc_bcc allow to send cc to follower
  mail_composer_cc_bcc/__manifest__.py
  mail_composer_cc_bcc/models/mail_thread.py
  mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
Labels: approved, ready to merge, bot is merging ⏳

#1627 [16.0][IMP] base_search_mail_content: Use the GIN index correctly
  base_search_mail_content/README.rst
  base_search_mail_content/models/mail_thread.py
  base_search_mail_content/readme/ROADMAP.rst
  base_search_mail_content/static/description/index.html
  base_search_mail_content/tests/test_base_search_mail_content.py
Labels: approved, bot is merging ⏳
