Repository OCA/social, pull requests merged in 2025-08, with the labels that each got.

#1695 [16.0][IMP] mail_tracking: Use handler instead of Store object and recover mark all as reviewed button
  mail_tracking/README.rst
  mail_tracking/__manifest__.py
  mail_tracking/i18n/es.po
  mail_tracking/i18n/mail_tracking.pot
  mail_tracking/models/mail_message.py
  mail_tracking/models/mail_resend_message.py
  mail_tracking/readme/CONTRIBUTORS.rst
  mail_tracking/static/description/index.html
  mail_tracking/static/src/client_actions/failed_message_storage.esm.js
  mail_tracking/static/src/components/discuss/discuss.xml
  mail_tracking/static/src/components/discuss_sidebar_mailbox/discuss_sidebar_mailbox.esm.js
  mail_tracking/static/src/components/discuss_sidebar_mailbox/discuss_sidebar_mailbox.xml
  mail_tracking/static/src/components/failed_message_list/failed_message_list.xml
  mail_tracking/static/src/components/message/message.esm.js
  mail_tracking/static/src/components/message/message.xml
  mail_tracking/static/src/components/message_list/message_list.esm.js
  mail_tracking/static/src/models/message.esm.js
  mail_tracking/static/src/models/messaging_notification_handler.esm.js
  mail_tracking/static/src/models/thread_view_topbar.esm.js
Labels: approved, bot is merging ⏳

#1234 [15.0][ADD] mail_send_confirmation
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mail_send_confirmation/README.rst
  mail_send_confirmation/__init__.py
  mail_send_confirmation/__manifest__.py
  mail_send_confirmation/readme/CONTRIBUTORS.rst
  mail_send_confirmation/readme/DESCRIPTION.rst
  mail_send_confirmation/static/description/icon.png
  mail_send_confirmation/static/description/index.html
  mail_send_confirmation/static/src/components/composer/composer.esm.js
  setup/mail_send_confirmation/odoo/addons/mail_send_confirmation
  setup/mail_send_confirmation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1669 [17.0][FIX] mail_activity_team: open team activities from systray
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/tests/test_mail_activity_team.py
Labels: approved, bot is merging ⏳

#1637 [ADD] mail_activity_meeting_reminder
  mail_activity_meeting_reminder/README.rst
  mail_activity_meeting_reminder/__init__.py
  mail_activity_meeting_reminder/__manifest__.py
  mail_activity_meeting_reminder/models/__init__.py
  mail_activity_meeting_reminder/models/mail_activity.py
  mail_activity_meeting_reminder/models/mail_activity_type.py
  mail_activity_meeting_reminder/readme/CONTRIBUTORS.md
  mail_activity_meeting_reminder/readme/DESCRIPTION.md
  mail_activity_meeting_reminder/static/description/icon.png
  mail_activity_meeting_reminder/static/description/index.html
  mail_activity_meeting_reminder/views/mail_activity_type.xml
  setup/mail_activity_meeting_reminder/odoo/addons/mail_activity_meeting_reminder
  setup/mail_activity_meeting_reminder/setup.py
Labels: approved, bot is merging ⏳, stale

#1712 [17.0][FIX] mail_thread: Duplicated suggestions when email_cc set
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳

#1713 [16.0][FIX] mail_thread: Duplicated suggestions when email_cc set
  mail_tracking/models/mail_thread.py
  mail_tracking/tests/test_mail_tracking.py
Labels: approved, bot is merging ⏳
